# Debian image with go installed and configured at /go
FROM golang as base

# Adding src and building
COPY go.mod go.sum /go/potionDB/
RUN cd potionDB && go mod download
ADD src/ /go/potionDB/potionDB/
ADD tpch_helper/ /go/tpch_data_processor/tpch/
RUN cd potionDB/potionDB/main && go build


#Final image
FROM rabbitmq

#Apps needed for the image
RUN apt-get update && apt-get install -y iproute2 && apt install -y iputils-ping

#Copy both go and potionDB binaries
COPY --from=base /usr/local/go/bin/ /go/
COPY --from=base /go/potionDB/potionDB/main/main /go/bin/

#Add start script
ADD dockerStuff/start.sh /go/bin/

#Default listen port
EXPOSE 8087
#RabbitMQ port
EXPOSE 5672

#Arguments. You can add here more that you need, check dockerStuff/start.sh and src/main/protoServer.go, method loadConfigs().
ENV CONFIG "/go/bin/configs/cluster/default"
ENV RABBITMQ_WAIT 10s
ENV BUCKETS "none"
ENV POOL_MAX "none"
ENV POTIONDB_WAIT 0s
ENV TOPK_SIZE 100
ENV DO_DATALOAD false
ENV SCALE 1
ENV DATALOC "go/data/"
ENV REGION "none"

#If RabbitMQ takes a long time to start, add some delay to PotionDB startup
#ENV RABBITMQ_VHOST /crdts
#ENV POTIONDB_WAIT 0s

#Add config folders late to avoid having to rebuild multiple images
ADD dockerStuff/rabbitmq.conf /etc/rabbitmq/
ADD configs /go/bin/configs

# Run the protoserver
#CMD ["sh", "-c", "go/bin/start.sh $CONFIG"]
CMD ["bash", "go/bin/start.sh"]