// Code generated by protoc-gen-go. DO NOT EDIT.
// source: replicator.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProtoStableClock struct {
	SenderID             *int32   `protobuf:"varint,1,req,name=senderID" json:"senderID,omitempty"`
	ReplicaTs            *int64   `protobuf:"varint,2,req,name=replicaTs" json:"replicaTs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoStableClock) Reset()         { *m = ProtoStableClock{} }
func (m *ProtoStableClock) String() string { return proto.CompactTextString(m) }
func (*ProtoStableClock) ProtoMessage()    {}
func (*ProtoStableClock) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{0}
}

func (m *ProtoStableClock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoStableClock.Unmarshal(m, b)
}
func (m *ProtoStableClock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoStableClock.Marshal(b, m, deterministic)
}
func (m *ProtoStableClock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoStableClock.Merge(m, src)
}
func (m *ProtoStableClock) XXX_Size() int {
	return xxx_messageInfo_ProtoStableClock.Size(m)
}
func (m *ProtoStableClock) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoStableClock.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoStableClock proto.InternalMessageInfo

func (m *ProtoStableClock) GetSenderID() int32 {
	if m != nil && m.SenderID != nil {
		return *m.SenderID
	}
	return 0
}

func (m *ProtoStableClock) GetReplicaTs() int64 {
	if m != nil && m.ReplicaTs != nil {
		return *m.ReplicaTs
	}
	return 0
}

type ProtoReplicatePart struct {
	SenderID             *int32          `protobuf:"varint,1,req,name=senderID" json:"senderID,omitempty"`
	Txn                  *ProtoRemoteTxn `protobuf:"bytes,2,req,name=txn" json:"txn,omitempty"`
	PartitionID          *int64          `protobuf:"varint,3,req,name=partitionID" json:"partitionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ProtoReplicatePart) Reset()         { *m = ProtoReplicatePart{} }
func (m *ProtoReplicatePart) String() string { return proto.CompactTextString(m) }
func (*ProtoReplicatePart) ProtoMessage()    {}
func (*ProtoReplicatePart) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{1}
}

func (m *ProtoReplicatePart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoReplicatePart.Unmarshal(m, b)
}
func (m *ProtoReplicatePart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoReplicatePart.Marshal(b, m, deterministic)
}
func (m *ProtoReplicatePart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoReplicatePart.Merge(m, src)
}
func (m *ProtoReplicatePart) XXX_Size() int {
	return xxx_messageInfo_ProtoReplicatePart.Size(m)
}
func (m *ProtoReplicatePart) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoReplicatePart.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoReplicatePart proto.InternalMessageInfo

func (m *ProtoReplicatePart) GetSenderID() int32 {
	if m != nil && m.SenderID != nil {
		return *m.SenderID
	}
	return 0
}

func (m *ProtoReplicatePart) GetTxn() *ProtoRemoteTxn {
	if m != nil {
		return m.Txn
	}
	return nil
}

func (m *ProtoReplicatePart) GetPartitionID() int64 {
	if m != nil && m.PartitionID != nil {
		return *m.PartitionID
	}
	return 0
}

type ProtoRemoteTxn struct {
	Timestamp            []byte                `protobuf:"bytes,1,req,name=timestamp" json:"timestamp,omitempty"`
	Upds                 []*ProtoDownstreamUpd `protobuf:"bytes,2,rep,name=upds" json:"upds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ProtoRemoteTxn) Reset()         { *m = ProtoRemoteTxn{} }
func (m *ProtoRemoteTxn) String() string { return proto.CompactTextString(m) }
func (*ProtoRemoteTxn) ProtoMessage()    {}
func (*ProtoRemoteTxn) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{2}
}

func (m *ProtoRemoteTxn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoRemoteTxn.Unmarshal(m, b)
}
func (m *ProtoRemoteTxn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoRemoteTxn.Marshal(b, m, deterministic)
}
func (m *ProtoRemoteTxn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoRemoteTxn.Merge(m, src)
}
func (m *ProtoRemoteTxn) XXX_Size() int {
	return xxx_messageInfo_ProtoRemoteTxn.Size(m)
}
func (m *ProtoRemoteTxn) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoRemoteTxn.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoRemoteTxn proto.InternalMessageInfo

func (m *ProtoRemoteTxn) GetTimestamp() []byte {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *ProtoRemoteTxn) GetUpds() []*ProtoDownstreamUpd {
	if m != nil {
		return m.Upds
	}
	return nil
}

type ProtoDownstreamUpd struct {
	KeyParams            *ApbBoundObject    `protobuf:"bytes,1,req,name=keyParams" json:"keyParams,omitempty"`
	Op                   *ProtoOpDownstream `protobuf:"bytes,2,req,name=op" json:"op,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ProtoDownstreamUpd) Reset()         { *m = ProtoDownstreamUpd{} }
func (m *ProtoDownstreamUpd) String() string { return proto.CompactTextString(m) }
func (*ProtoDownstreamUpd) ProtoMessage()    {}
func (*ProtoDownstreamUpd) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{3}
}

func (m *ProtoDownstreamUpd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoDownstreamUpd.Unmarshal(m, b)
}
func (m *ProtoDownstreamUpd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoDownstreamUpd.Marshal(b, m, deterministic)
}
func (m *ProtoDownstreamUpd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoDownstreamUpd.Merge(m, src)
}
func (m *ProtoDownstreamUpd) XXX_Size() int {
	return xxx_messageInfo_ProtoDownstreamUpd.Size(m)
}
func (m *ProtoDownstreamUpd) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoDownstreamUpd.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoDownstreamUpd proto.InternalMessageInfo

func (m *ProtoDownstreamUpd) GetKeyParams() *ApbBoundObject {
	if m != nil {
		return m.KeyParams
	}
	return nil
}

func (m *ProtoDownstreamUpd) GetOp() *ProtoOpDownstream {
	if m != nil {
		return m.Op
	}
	return nil
}

type ProtoOpDownstream struct {
	CounterOp            *ProtoCounterDownstream     `protobuf:"bytes,1,opt,name=counterOp" json:"counterOp,omitempty"`
	SetOp                *ProtoSetDownstream         `protobuf:"bytes,2,opt,name=setOp" json:"setOp,omitempty"`
	TopkrmvOp            *ProtoTopKRmvDownstream     `protobuf:"bytes,3,opt,name=topkrmvOp" json:"topkrmvOp,omitempty"`
	LwwregOp             *ProtoLWWRegisterDownstream `protobuf:"bytes,4,opt,name=lwwregOp" json:"lwwregOp,omitempty"`
	OrmapOp              *ProtoORMapDownstream       `protobuf:"bytes,5,opt,name=ormapOp" json:"ormapOp,omitempty"`
	AvgOp                *ProtoAvgDownstream         `protobuf:"bytes,6,opt,name=avgOp" json:"avgOp,omitempty"`
	MaxminOp             *ProtoMaxMinDownstream      `protobuf:"bytes,7,opt,name=maxminOp" json:"maxminOp,omitempty"`
	RwembmapOp           *ProtoRWEmbMapDownstream    `protobuf:"bytes,8,opt,name=rwembmapOp" json:"rwembmapOp,omitempty"`
	ResetOp              *ProtoResetDownstream       `protobuf:"bytes,15,opt,name=resetOp" json:"resetOp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ProtoOpDownstream) Reset()         { *m = ProtoOpDownstream{} }
func (m *ProtoOpDownstream) String() string { return proto.CompactTextString(m) }
func (*ProtoOpDownstream) ProtoMessage()    {}
func (*ProtoOpDownstream) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{4}
}

func (m *ProtoOpDownstream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoOpDownstream.Unmarshal(m, b)
}
func (m *ProtoOpDownstream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoOpDownstream.Marshal(b, m, deterministic)
}
func (m *ProtoOpDownstream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoOpDownstream.Merge(m, src)
}
func (m *ProtoOpDownstream) XXX_Size() int {
	return xxx_messageInfo_ProtoOpDownstream.Size(m)
}
func (m *ProtoOpDownstream) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoOpDownstream.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoOpDownstream proto.InternalMessageInfo

func (m *ProtoOpDownstream) GetCounterOp() *ProtoCounterDownstream {
	if m != nil {
		return m.CounterOp
	}
	return nil
}

func (m *ProtoOpDownstream) GetSetOp() *ProtoSetDownstream {
	if m != nil {
		return m.SetOp
	}
	return nil
}

func (m *ProtoOpDownstream) GetTopkrmvOp() *ProtoTopKRmvDownstream {
	if m != nil {
		return m.TopkrmvOp
	}
	return nil
}

func (m *ProtoOpDownstream) GetLwwregOp() *ProtoLWWRegisterDownstream {
	if m != nil {
		return m.LwwregOp
	}
	return nil
}

func (m *ProtoOpDownstream) GetOrmapOp() *ProtoORMapDownstream {
	if m != nil {
		return m.OrmapOp
	}
	return nil
}

func (m *ProtoOpDownstream) GetAvgOp() *ProtoAvgDownstream {
	if m != nil {
		return m.AvgOp
	}
	return nil
}

func (m *ProtoOpDownstream) GetMaxminOp() *ProtoMaxMinDownstream {
	if m != nil {
		return m.MaxminOp
	}
	return nil
}

func (m *ProtoOpDownstream) GetRwembmapOp() *ProtoRWEmbMapDownstream {
	if m != nil {
		return m.RwembmapOp
	}
	return nil
}

func (m *ProtoOpDownstream) GetResetOp() *ProtoResetDownstream {
	if m != nil {
		return m.ResetOp
	}
	return nil
}

type ProtoCounterDownstream struct {
	IsInc                *bool    `protobuf:"varint,1,req,name=isInc" json:"isInc,omitempty"`
	Change               *int32   `protobuf:"varint,2,req,name=change" json:"change,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoCounterDownstream) Reset()         { *m = ProtoCounterDownstream{} }
func (m *ProtoCounterDownstream) String() string { return proto.CompactTextString(m) }
func (*ProtoCounterDownstream) ProtoMessage()    {}
func (*ProtoCounterDownstream) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{5}
}

func (m *ProtoCounterDownstream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoCounterDownstream.Unmarshal(m, b)
}
func (m *ProtoCounterDownstream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoCounterDownstream.Marshal(b, m, deterministic)
}
func (m *ProtoCounterDownstream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoCounterDownstream.Merge(m, src)
}
func (m *ProtoCounterDownstream) XXX_Size() int {
	return xxx_messageInfo_ProtoCounterDownstream.Size(m)
}
func (m *ProtoCounterDownstream) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoCounterDownstream.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoCounterDownstream proto.InternalMessageInfo

func (m *ProtoCounterDownstream) GetIsInc() bool {
	if m != nil && m.IsInc != nil {
		return *m.IsInc
	}
	return false
}

func (m *ProtoCounterDownstream) GetChange() int32 {
	if m != nil && m.Change != nil {
		return *m.Change
	}
	return 0
}

type ProtoLWWRegisterDownstream struct {
	Value                []byte   `protobuf:"bytes,1,req,name=value" json:"value,omitempty"`
	Ts                   *int64   `protobuf:"varint,2,req,name=ts" json:"ts,omitempty"`
	ReplicaID            *int32   `protobuf:"varint,3,req,name=replicaID" json:"replicaID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoLWWRegisterDownstream) Reset()         { *m = ProtoLWWRegisterDownstream{} }
func (m *ProtoLWWRegisterDownstream) String() string { return proto.CompactTextString(m) }
func (*ProtoLWWRegisterDownstream) ProtoMessage()    {}
func (*ProtoLWWRegisterDownstream) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{6}
}

func (m *ProtoLWWRegisterDownstream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoLWWRegisterDownstream.Unmarshal(m, b)
}
func (m *ProtoLWWRegisterDownstream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoLWWRegisterDownstream.Marshal(b, m, deterministic)
}
func (m *ProtoLWWRegisterDownstream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoLWWRegisterDownstream.Merge(m, src)
}
func (m *ProtoLWWRegisterDownstream) XXX_Size() int {
	return xxx_messageInfo_ProtoLWWRegisterDownstream.Size(m)
}
func (m *ProtoLWWRegisterDownstream) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoLWWRegisterDownstream.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoLWWRegisterDownstream proto.InternalMessageInfo

func (m *ProtoLWWRegisterDownstream) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ProtoLWWRegisterDownstream) GetTs() int64 {
	if m != nil && m.Ts != nil {
		return *m.Ts
	}
	return 0
}

func (m *ProtoLWWRegisterDownstream) GetReplicaID() int32 {
	if m != nil && m.ReplicaID != nil {
		return *m.ReplicaID
	}
	return 0
}

type ProtoSetDownstream struct {
	Adds                 []*ProtoValueUnique  `protobuf:"bytes,1,rep,name=adds" json:"adds,omitempty"`
	Rems                 []*ProtoValueUniques `protobuf:"bytes,2,rep,name=rems" json:"rems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ProtoSetDownstream) Reset()         { *m = ProtoSetDownstream{} }
func (m *ProtoSetDownstream) String() string { return proto.CompactTextString(m) }
func (*ProtoSetDownstream) ProtoMessage()    {}
func (*ProtoSetDownstream) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{7}
}

func (m *ProtoSetDownstream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoSetDownstream.Unmarshal(m, b)
}
func (m *ProtoSetDownstream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoSetDownstream.Marshal(b, m, deterministic)
}
func (m *ProtoSetDownstream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoSetDownstream.Merge(m, src)
}
func (m *ProtoSetDownstream) XXX_Size() int {
	return xxx_messageInfo_ProtoSetDownstream.Size(m)
}
func (m *ProtoSetDownstream) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoSetDownstream.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoSetDownstream proto.InternalMessageInfo

func (m *ProtoSetDownstream) GetAdds() []*ProtoValueUnique {
	if m != nil {
		return m.Adds
	}
	return nil
}

func (m *ProtoSetDownstream) GetRems() []*ProtoValueUniques {
	if m != nil {
		return m.Rems
	}
	return nil
}

type ProtoORMapDownstream struct {
	Adds                 []*ProtoKeyValueUnique `protobuf:"bytes,1,rep,name=adds" json:"adds,omitempty"`
	Rems                 []*ProtoORMapRemove    `protobuf:"bytes,2,rep,name=rems" json:"rems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ProtoORMapDownstream) Reset()         { *m = ProtoORMapDownstream{} }
func (m *ProtoORMapDownstream) String() string { return proto.CompactTextString(m) }
func (*ProtoORMapDownstream) ProtoMessage()    {}
func (*ProtoORMapDownstream) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{8}
}

func (m *ProtoORMapDownstream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoORMapDownstream.Unmarshal(m, b)
}
func (m *ProtoORMapDownstream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoORMapDownstream.Marshal(b, m, deterministic)
}
func (m *ProtoORMapDownstream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoORMapDownstream.Merge(m, src)
}
func (m *ProtoORMapDownstream) XXX_Size() int {
	return xxx_messageInfo_ProtoORMapDownstream.Size(m)
}
func (m *ProtoORMapDownstream) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoORMapDownstream.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoORMapDownstream proto.InternalMessageInfo

func (m *ProtoORMapDownstream) GetAdds() []*ProtoKeyValueUnique {
	if m != nil {
		return m.Adds
	}
	return nil
}

func (m *ProtoORMapDownstream) GetRems() []*ProtoORMapRemove {
	if m != nil {
		return m.Rems
	}
	return nil
}

type ProtoTopKRmvDownstream struct {
	Adds                 []*ProtoTopKElement `protobuf:"bytes,1,rep,name=adds" json:"adds,omitempty"`
	Rems                 *ProtoTopKRmvRemove `protobuf:"bytes,2,opt,name=rems" json:"rems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ProtoTopKRmvDownstream) Reset()         { *m = ProtoTopKRmvDownstream{} }
func (m *ProtoTopKRmvDownstream) String() string { return proto.CompactTextString(m) }
func (*ProtoTopKRmvDownstream) ProtoMessage()    {}
func (*ProtoTopKRmvDownstream) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{9}
}

func (m *ProtoTopKRmvDownstream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoTopKRmvDownstream.Unmarshal(m, b)
}
func (m *ProtoTopKRmvDownstream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoTopKRmvDownstream.Marshal(b, m, deterministic)
}
func (m *ProtoTopKRmvDownstream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoTopKRmvDownstream.Merge(m, src)
}
func (m *ProtoTopKRmvDownstream) XXX_Size() int {
	return xxx_messageInfo_ProtoTopKRmvDownstream.Size(m)
}
func (m *ProtoTopKRmvDownstream) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoTopKRmvDownstream.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoTopKRmvDownstream proto.InternalMessageInfo

func (m *ProtoTopKRmvDownstream) GetAdds() []*ProtoTopKElement {
	if m != nil {
		return m.Adds
	}
	return nil
}

func (m *ProtoTopKRmvDownstream) GetRems() *ProtoTopKRmvRemove {
	if m != nil {
		return m.Rems
	}
	return nil
}

type ProtoTopKRmvRemove struct {
	Vcs                  [][]byte `protobuf:"bytes,1,rep,name=vcs" json:"vcs,omitempty"`
	Ids                  []int32  `protobuf:"varint,2,rep,name=ids" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoTopKRmvRemove) Reset()         { *m = ProtoTopKRmvRemove{} }
func (m *ProtoTopKRmvRemove) String() string { return proto.CompactTextString(m) }
func (*ProtoTopKRmvRemove) ProtoMessage()    {}
func (*ProtoTopKRmvRemove) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{10}
}

func (m *ProtoTopKRmvRemove) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoTopKRmvRemove.Unmarshal(m, b)
}
func (m *ProtoTopKRmvRemove) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoTopKRmvRemove.Marshal(b, m, deterministic)
}
func (m *ProtoTopKRmvRemove) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoTopKRmvRemove.Merge(m, src)
}
func (m *ProtoTopKRmvRemove) XXX_Size() int {
	return xxx_messageInfo_ProtoTopKRmvRemove.Size(m)
}
func (m *ProtoTopKRmvRemove) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoTopKRmvRemove.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoTopKRmvRemove proto.InternalMessageInfo

func (m *ProtoTopKRmvRemove) GetVcs() [][]byte {
	if m != nil {
		return m.Vcs
	}
	return nil
}

func (m *ProtoTopKRmvRemove) GetIds() []int32 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type ProtoAvgDownstream struct {
	SumValue             *int64   `protobuf:"varint,1,req,name=sumValue" json:"sumValue,omitempty"`
	NAdds                *int64   `protobuf:"varint,2,req,name=nAdds" json:"nAdds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoAvgDownstream) Reset()         { *m = ProtoAvgDownstream{} }
func (m *ProtoAvgDownstream) String() string { return proto.CompactTextString(m) }
func (*ProtoAvgDownstream) ProtoMessage()    {}
func (*ProtoAvgDownstream) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{11}
}

func (m *ProtoAvgDownstream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoAvgDownstream.Unmarshal(m, b)
}
func (m *ProtoAvgDownstream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoAvgDownstream.Marshal(b, m, deterministic)
}
func (m *ProtoAvgDownstream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoAvgDownstream.Merge(m, src)
}
func (m *ProtoAvgDownstream) XXX_Size() int {
	return xxx_messageInfo_ProtoAvgDownstream.Size(m)
}
func (m *ProtoAvgDownstream) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoAvgDownstream.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoAvgDownstream proto.InternalMessageInfo

func (m *ProtoAvgDownstream) GetSumValue() int64 {
	if m != nil && m.SumValue != nil {
		return *m.SumValue
	}
	return 0
}

func (m *ProtoAvgDownstream) GetNAdds() int64 {
	if m != nil && m.NAdds != nil {
		return *m.NAdds
	}
	return 0
}

type ProtoMaxMinDownstream struct {
	Max                  *ProtoMaxDownstream `protobuf:"bytes,1,opt,name=max" json:"max,omitempty"`
	Min                  *ProtoMinDownstream `protobuf:"bytes,2,opt,name=min" json:"min,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ProtoMaxMinDownstream) Reset()         { *m = ProtoMaxMinDownstream{} }
func (m *ProtoMaxMinDownstream) String() string { return proto.CompactTextString(m) }
func (*ProtoMaxMinDownstream) ProtoMessage()    {}
func (*ProtoMaxMinDownstream) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{12}
}

func (m *ProtoMaxMinDownstream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoMaxMinDownstream.Unmarshal(m, b)
}
func (m *ProtoMaxMinDownstream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoMaxMinDownstream.Marshal(b, m, deterministic)
}
func (m *ProtoMaxMinDownstream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoMaxMinDownstream.Merge(m, src)
}
func (m *ProtoMaxMinDownstream) XXX_Size() int {
	return xxx_messageInfo_ProtoMaxMinDownstream.Size(m)
}
func (m *ProtoMaxMinDownstream) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoMaxMinDownstream.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoMaxMinDownstream proto.InternalMessageInfo

func (m *ProtoMaxMinDownstream) GetMax() *ProtoMaxDownstream {
	if m != nil {
		return m.Max
	}
	return nil
}

func (m *ProtoMaxMinDownstream) GetMin() *ProtoMinDownstream {
	if m != nil {
		return m.Min
	}
	return nil
}

type ProtoMaxDownstream struct {
	Value                *int64   `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoMaxDownstream) Reset()         { *m = ProtoMaxDownstream{} }
func (m *ProtoMaxDownstream) String() string { return proto.CompactTextString(m) }
func (*ProtoMaxDownstream) ProtoMessage()    {}
func (*ProtoMaxDownstream) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{13}
}

func (m *ProtoMaxDownstream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoMaxDownstream.Unmarshal(m, b)
}
func (m *ProtoMaxDownstream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoMaxDownstream.Marshal(b, m, deterministic)
}
func (m *ProtoMaxDownstream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoMaxDownstream.Merge(m, src)
}
func (m *ProtoMaxDownstream) XXX_Size() int {
	return xxx_messageInfo_ProtoMaxDownstream.Size(m)
}
func (m *ProtoMaxDownstream) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoMaxDownstream.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoMaxDownstream proto.InternalMessageInfo

func (m *ProtoMaxDownstream) GetValue() int64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

type ProtoMinDownstream struct {
	Value                *int64   `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoMinDownstream) Reset()         { *m = ProtoMinDownstream{} }
func (m *ProtoMinDownstream) String() string { return proto.CompactTextString(m) }
func (*ProtoMinDownstream) ProtoMessage()    {}
func (*ProtoMinDownstream) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{14}
}

func (m *ProtoMinDownstream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoMinDownstream.Unmarshal(m, b)
}
func (m *ProtoMinDownstream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoMinDownstream.Marshal(b, m, deterministic)
}
func (m *ProtoMinDownstream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoMinDownstream.Merge(m, src)
}
func (m *ProtoMinDownstream) XXX_Size() int {
	return xxx_messageInfo_ProtoMinDownstream.Size(m)
}
func (m *ProtoMinDownstream) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoMinDownstream.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoMinDownstream proto.InternalMessageInfo

func (m *ProtoMinDownstream) GetValue() int64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

type ProtoValueUnique struct {
	Value                []byte   `protobuf:"bytes,1,req,name=value" json:"value,omitempty"`
	Unique               *uint64  `protobuf:"varint,2,req,name=unique" json:"unique,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoValueUnique) Reset()         { *m = ProtoValueUnique{} }
func (m *ProtoValueUnique) String() string { return proto.CompactTextString(m) }
func (*ProtoValueUnique) ProtoMessage()    {}
func (*ProtoValueUnique) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{15}
}

func (m *ProtoValueUnique) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoValueUnique.Unmarshal(m, b)
}
func (m *ProtoValueUnique) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoValueUnique.Marshal(b, m, deterministic)
}
func (m *ProtoValueUnique) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoValueUnique.Merge(m, src)
}
func (m *ProtoValueUnique) XXX_Size() int {
	return xxx_messageInfo_ProtoValueUnique.Size(m)
}
func (m *ProtoValueUnique) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoValueUnique.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoValueUnique proto.InternalMessageInfo

func (m *ProtoValueUnique) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ProtoValueUnique) GetUnique() uint64 {
	if m != nil && m.Unique != nil {
		return *m.Unique
	}
	return 0
}

type ProtoValueUniques struct {
	Value                []byte   `protobuf:"bytes,1,req,name=value" json:"value,omitempty"`
	Uniques              []uint64 `protobuf:"varint,2,rep,name=uniques" json:"uniques,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoValueUniques) Reset()         { *m = ProtoValueUniques{} }
func (m *ProtoValueUniques) String() string { return proto.CompactTextString(m) }
func (*ProtoValueUniques) ProtoMessage()    {}
func (*ProtoValueUniques) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{16}
}

func (m *ProtoValueUniques) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoValueUniques.Unmarshal(m, b)
}
func (m *ProtoValueUniques) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoValueUniques.Marshal(b, m, deterministic)
}
func (m *ProtoValueUniques) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoValueUniques.Merge(m, src)
}
func (m *ProtoValueUniques) XXX_Size() int {
	return xxx_messageInfo_ProtoValueUniques.Size(m)
}
func (m *ProtoValueUniques) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoValueUniques.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoValueUniques proto.InternalMessageInfo

func (m *ProtoValueUniques) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ProtoValueUniques) GetUniques() []uint64 {
	if m != nil {
		return m.Uniques
	}
	return nil
}

type ProtoKeyValueUnique struct {
	Key                  []byte   `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Element              []byte   `protobuf:"bytes,2,req,name=element" json:"element,omitempty"`
	Unique               *uint64  `protobuf:"varint,3,req,name=unique" json:"unique,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoKeyValueUnique) Reset()         { *m = ProtoKeyValueUnique{} }
func (m *ProtoKeyValueUnique) String() string { return proto.CompactTextString(m) }
func (*ProtoKeyValueUnique) ProtoMessage()    {}
func (*ProtoKeyValueUnique) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{17}
}

func (m *ProtoKeyValueUnique) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoKeyValueUnique.Unmarshal(m, b)
}
func (m *ProtoKeyValueUnique) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoKeyValueUnique.Marshal(b, m, deterministic)
}
func (m *ProtoKeyValueUnique) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoKeyValueUnique.Merge(m, src)
}
func (m *ProtoKeyValueUnique) XXX_Size() int {
	return xxx_messageInfo_ProtoKeyValueUnique.Size(m)
}
func (m *ProtoKeyValueUnique) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoKeyValueUnique.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoKeyValueUnique proto.InternalMessageInfo

func (m *ProtoKeyValueUnique) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ProtoKeyValueUnique) GetElement() []byte {
	if m != nil {
		return m.Element
	}
	return nil
}

func (m *ProtoKeyValueUnique) GetUnique() uint64 {
	if m != nil && m.Unique != nil {
		return *m.Unique
	}
	return 0
}

type ProtoORMapRemove struct {
	Key                  []byte               `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Elems                []*ProtoValueUniques `protobuf:"bytes,2,rep,name=elems" json:"elems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ProtoORMapRemove) Reset()         { *m = ProtoORMapRemove{} }
func (m *ProtoORMapRemove) String() string { return proto.CompactTextString(m) }
func (*ProtoORMapRemove) ProtoMessage()    {}
func (*ProtoORMapRemove) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{18}
}

func (m *ProtoORMapRemove) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoORMapRemove.Unmarshal(m, b)
}
func (m *ProtoORMapRemove) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoORMapRemove.Marshal(b, m, deterministic)
}
func (m *ProtoORMapRemove) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoORMapRemove.Merge(m, src)
}
func (m *ProtoORMapRemove) XXX_Size() int {
	return xxx_messageInfo_ProtoORMapRemove.Size(m)
}
func (m *ProtoORMapRemove) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoORMapRemove.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoORMapRemove proto.InternalMessageInfo

func (m *ProtoORMapRemove) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ProtoORMapRemove) GetElems() []*ProtoValueUniques {
	if m != nil {
		return m.Elems
	}
	return nil
}

type ProtoTopKElement struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Score                *int32   `protobuf:"varint,2,req,name=score" json:"score,omitempty"`
	Ts                   *int64   `protobuf:"varint,3,req,name=ts" json:"ts,omitempty"`
	ReplicaID            *int32   `protobuf:"varint,4,req,name=replicaID" json:"replicaID,omitempty"`
	Data                 []byte   `protobuf:"bytes,5,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoTopKElement) Reset()         { *m = ProtoTopKElement{} }
func (m *ProtoTopKElement) String() string { return proto.CompactTextString(m) }
func (*ProtoTopKElement) ProtoMessage()    {}
func (*ProtoTopKElement) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{19}
}

func (m *ProtoTopKElement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoTopKElement.Unmarshal(m, b)
}
func (m *ProtoTopKElement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoTopKElement.Marshal(b, m, deterministic)
}
func (m *ProtoTopKElement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoTopKElement.Merge(m, src)
}
func (m *ProtoTopKElement) XXX_Size() int {
	return xxx_messageInfo_ProtoTopKElement.Size(m)
}
func (m *ProtoTopKElement) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoTopKElement.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoTopKElement proto.InternalMessageInfo

func (m *ProtoTopKElement) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ProtoTopKElement) GetScore() int32 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *ProtoTopKElement) GetTs() int64 {
	if m != nil && m.Ts != nil {
		return *m.Ts
	}
	return 0
}

func (m *ProtoTopKElement) GetReplicaID() int32 {
	if m != nil && m.ReplicaID != nil {
		return *m.ReplicaID
	}
	return 0
}

func (m *ProtoTopKElement) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ProtoTopKIdVc struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Vc                   []byte   `protobuf:"bytes,2,req,name=vc" json:"vc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoTopKIdVc) Reset()         { *m = ProtoTopKIdVc{} }
func (m *ProtoTopKIdVc) String() string { return proto.CompactTextString(m) }
func (*ProtoTopKIdVc) ProtoMessage()    {}
func (*ProtoTopKIdVc) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{20}
}

func (m *ProtoTopKIdVc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoTopKIdVc.Unmarshal(m, b)
}
func (m *ProtoTopKIdVc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoTopKIdVc.Marshal(b, m, deterministic)
}
func (m *ProtoTopKIdVc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoTopKIdVc.Merge(m, src)
}
func (m *ProtoTopKIdVc) XXX_Size() int {
	return xxx_messageInfo_ProtoTopKIdVc.Size(m)
}
func (m *ProtoTopKIdVc) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoTopKIdVc.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoTopKIdVc proto.InternalMessageInfo

func (m *ProtoTopKIdVc) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ProtoTopKIdVc) GetVc() []byte {
	if m != nil {
		return m.Vc
	}
	return nil
}

type ProtoRWEmbMapDownstream struct {
	Adds                 *ProtoRWEmbMapUpdates `protobuf:"bytes,1,opt,name=adds" json:"adds,omitempty"`
	Rems                 *ProtoRWEmbMapRemoves `protobuf:"bytes,2,opt,name=rems" json:"rems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ProtoRWEmbMapDownstream) Reset()         { *m = ProtoRWEmbMapDownstream{} }
func (m *ProtoRWEmbMapDownstream) String() string { return proto.CompactTextString(m) }
func (*ProtoRWEmbMapDownstream) ProtoMessage()    {}
func (*ProtoRWEmbMapDownstream) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{21}
}

func (m *ProtoRWEmbMapDownstream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoRWEmbMapDownstream.Unmarshal(m, b)
}
func (m *ProtoRWEmbMapDownstream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoRWEmbMapDownstream.Marshal(b, m, deterministic)
}
func (m *ProtoRWEmbMapDownstream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoRWEmbMapDownstream.Merge(m, src)
}
func (m *ProtoRWEmbMapDownstream) XXX_Size() int {
	return xxx_messageInfo_ProtoRWEmbMapDownstream.Size(m)
}
func (m *ProtoRWEmbMapDownstream) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoRWEmbMapDownstream.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoRWEmbMapDownstream proto.InternalMessageInfo

func (m *ProtoRWEmbMapDownstream) GetAdds() *ProtoRWEmbMapUpdates {
	if m != nil {
		return m.Adds
	}
	return nil
}

func (m *ProtoRWEmbMapDownstream) GetRems() *ProtoRWEmbMapRemoves {
	if m != nil {
		return m.Rems
	}
	return nil
}

type ProtoRWEmbMapUpdates struct {
	Upds                 []*ProtoEmbMapUpd   `protobuf:"bytes,1,rep,name=upds" json:"upds,omitempty"`
	Vc                   []*ProtoStableClock `protobuf:"bytes,2,rep,name=vc" json:"vc,omitempty"`
	ReplicaID            *int32              `protobuf:"varint,3,req,name=replicaID" json:"replicaID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ProtoRWEmbMapUpdates) Reset()         { *m = ProtoRWEmbMapUpdates{} }
func (m *ProtoRWEmbMapUpdates) String() string { return proto.CompactTextString(m) }
func (*ProtoRWEmbMapUpdates) ProtoMessage()    {}
func (*ProtoRWEmbMapUpdates) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{22}
}

func (m *ProtoRWEmbMapUpdates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoRWEmbMapUpdates.Unmarshal(m, b)
}
func (m *ProtoRWEmbMapUpdates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoRWEmbMapUpdates.Marshal(b, m, deterministic)
}
func (m *ProtoRWEmbMapUpdates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoRWEmbMapUpdates.Merge(m, src)
}
func (m *ProtoRWEmbMapUpdates) XXX_Size() int {
	return xxx_messageInfo_ProtoRWEmbMapUpdates.Size(m)
}
func (m *ProtoRWEmbMapUpdates) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoRWEmbMapUpdates.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoRWEmbMapUpdates proto.InternalMessageInfo

func (m *ProtoRWEmbMapUpdates) GetUpds() []*ProtoEmbMapUpd {
	if m != nil {
		return m.Upds
	}
	return nil
}

func (m *ProtoRWEmbMapUpdates) GetVc() []*ProtoStableClock {
	if m != nil {
		return m.Vc
	}
	return nil
}

func (m *ProtoRWEmbMapUpdates) GetReplicaID() int32 {
	if m != nil && m.ReplicaID != nil {
		return *m.ReplicaID
	}
	return 0
}

type ProtoRWEmbMapRemoves struct {
	Keys                 []string `protobuf:"bytes,1,rep,name=keys" json:"keys,omitempty"`
	Ts                   *int64   `protobuf:"varint,2,req,name=ts" json:"ts,omitempty"`
	ReplicaID            *int32   `protobuf:"varint,3,req,name=replicaID" json:"replicaID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoRWEmbMapRemoves) Reset()         { *m = ProtoRWEmbMapRemoves{} }
func (m *ProtoRWEmbMapRemoves) String() string { return proto.CompactTextString(m) }
func (*ProtoRWEmbMapRemoves) ProtoMessage()    {}
func (*ProtoRWEmbMapRemoves) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{23}
}

func (m *ProtoRWEmbMapRemoves) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoRWEmbMapRemoves.Unmarshal(m, b)
}
func (m *ProtoRWEmbMapRemoves) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoRWEmbMapRemoves.Marshal(b, m, deterministic)
}
func (m *ProtoRWEmbMapRemoves) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoRWEmbMapRemoves.Merge(m, src)
}
func (m *ProtoRWEmbMapRemoves) XXX_Size() int {
	return xxx_messageInfo_ProtoRWEmbMapRemoves.Size(m)
}
func (m *ProtoRWEmbMapRemoves) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoRWEmbMapRemoves.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoRWEmbMapRemoves proto.InternalMessageInfo

func (m *ProtoRWEmbMapRemoves) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *ProtoRWEmbMapRemoves) GetTs() int64 {
	if m != nil && m.Ts != nil {
		return *m.Ts
	}
	return 0
}

func (m *ProtoRWEmbMapRemoves) GetReplicaID() int32 {
	if m != nil && m.ReplicaID != nil {
		return *m.ReplicaID
	}
	return 0
}

type ProtoEmbMapUpd struct {
	Key                  []byte             `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Type                 *CRDTType          `protobuf:"varint,2,req,name=type,enum=CRDTType" json:"type,omitempty"`
	Upd                  *ProtoOpDownstream `protobuf:"bytes,3,req,name=upd" json:"upd,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ProtoEmbMapUpd) Reset()         { *m = ProtoEmbMapUpd{} }
func (m *ProtoEmbMapUpd) String() string { return proto.CompactTextString(m) }
func (*ProtoEmbMapUpd) ProtoMessage()    {}
func (*ProtoEmbMapUpd) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{24}
}

func (m *ProtoEmbMapUpd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoEmbMapUpd.Unmarshal(m, b)
}
func (m *ProtoEmbMapUpd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoEmbMapUpd.Marshal(b, m, deterministic)
}
func (m *ProtoEmbMapUpd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoEmbMapUpd.Merge(m, src)
}
func (m *ProtoEmbMapUpd) XXX_Size() int {
	return xxx_messageInfo_ProtoEmbMapUpd.Size(m)
}
func (m *ProtoEmbMapUpd) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoEmbMapUpd.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoEmbMapUpd proto.InternalMessageInfo

func (m *ProtoEmbMapUpd) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ProtoEmbMapUpd) GetType() CRDTType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return CRDTType_COUNTER
}

func (m *ProtoEmbMapUpd) GetUpd() *ProtoOpDownstream {
	if m != nil {
		return m.Upd
	}
	return nil
}

type ProtoResetDownstream struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoResetDownstream) Reset()         { *m = ProtoResetDownstream{} }
func (m *ProtoResetDownstream) String() string { return proto.CompactTextString(m) }
func (*ProtoResetDownstream) ProtoMessage()    {}
func (*ProtoResetDownstream) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{25}
}

func (m *ProtoResetDownstream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoResetDownstream.Unmarshal(m, b)
}
func (m *ProtoResetDownstream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoResetDownstream.Marshal(b, m, deterministic)
}
func (m *ProtoResetDownstream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoResetDownstream.Merge(m, src)
}
func (m *ProtoResetDownstream) XXX_Size() int {
	return xxx_messageInfo_ProtoResetDownstream.Size(m)
}
func (m *ProtoResetDownstream) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoResetDownstream.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoResetDownstream proto.InternalMessageInfo

type ProtoRemoteID struct {
	ReplicaID            *int32   `protobuf:"varint,1,req,name=replicaID" json:"replicaID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoRemoteID) Reset()         { *m = ProtoRemoteID{} }
func (m *ProtoRemoteID) String() string { return proto.CompactTextString(m) }
func (*ProtoRemoteID) ProtoMessage()    {}
func (*ProtoRemoteID) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{26}
}

func (m *ProtoRemoteID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoRemoteID.Unmarshal(m, b)
}
func (m *ProtoRemoteID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoRemoteID.Marshal(b, m, deterministic)
}
func (m *ProtoRemoteID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoRemoteID.Merge(m, src)
}
func (m *ProtoRemoteID) XXX_Size() int {
	return xxx_messageInfo_ProtoRemoteID.Size(m)
}
func (m *ProtoRemoteID) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoRemoteID.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoRemoteID proto.InternalMessageInfo

func (m *ProtoRemoteID) GetReplicaID() int32 {
	if m != nil && m.ReplicaID != nil {
		return *m.ReplicaID
	}
	return 0
}

type ProtoJoin struct {
	Buckets              []string `protobuf:"bytes,1,rep,name=buckets" json:"buckets,omitempty"`
	ReplicaID            *int32   `protobuf:"varint,2,req,name=replicaID" json:"replicaID,omitempty"`
	ReplicaIP            *string  `protobuf:"bytes,3,req,name=replicaIP" json:"replicaIP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoJoin) Reset()         { *m = ProtoJoin{} }
func (m *ProtoJoin) String() string { return proto.CompactTextString(m) }
func (*ProtoJoin) ProtoMessage()    {}
func (*ProtoJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{27}
}

func (m *ProtoJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoJoin.Unmarshal(m, b)
}
func (m *ProtoJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoJoin.Marshal(b, m, deterministic)
}
func (m *ProtoJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoJoin.Merge(m, src)
}
func (m *ProtoJoin) XXX_Size() int {
	return xxx_messageInfo_ProtoJoin.Size(m)
}
func (m *ProtoJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoJoin.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoJoin proto.InternalMessageInfo

func (m *ProtoJoin) GetBuckets() []string {
	if m != nil {
		return m.Buckets
	}
	return nil
}

func (m *ProtoJoin) GetReplicaID() int32 {
	if m != nil && m.ReplicaID != nil {
		return *m.ReplicaID
	}
	return 0
}

func (m *ProtoJoin) GetReplicaIP() string {
	if m != nil && m.ReplicaIP != nil {
		return *m.ReplicaIP
	}
	return ""
}

type ProtoReplyJoin struct {
	Buckets []string `protobuf:"bytes,1,rep,name=buckets" json:"buckets,omitempty"`
	//repeated ProtoClock partsClk = 2;
	PartsClk  [][]byte `protobuf:"bytes,2,rep,name=partsClk" json:"partsClk,omitempty"`
	ReplicaID *int32   `protobuf:"varint,3,req,name=replicaID" json:"replicaID,omitempty"`
	//required int32 connID = 4;  //Used to know which connection to request the buckets from.
	ReplicaIP            *string  `protobuf:"bytes,4,req,name=replicaIP" json:"replicaIP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoReplyJoin) Reset()         { *m = ProtoReplyJoin{} }
func (m *ProtoReplyJoin) String() string { return proto.CompactTextString(m) }
func (*ProtoReplyJoin) ProtoMessage()    {}
func (*ProtoReplyJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{28}
}

func (m *ProtoReplyJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoReplyJoin.Unmarshal(m, b)
}
func (m *ProtoReplyJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoReplyJoin.Marshal(b, m, deterministic)
}
func (m *ProtoReplyJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoReplyJoin.Merge(m, src)
}
func (m *ProtoReplyJoin) XXX_Size() int {
	return xxx_messageInfo_ProtoReplyJoin.Size(m)
}
func (m *ProtoReplyJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoReplyJoin.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoReplyJoin proto.InternalMessageInfo

func (m *ProtoReplyJoin) GetBuckets() []string {
	if m != nil {
		return m.Buckets
	}
	return nil
}

func (m *ProtoReplyJoin) GetPartsClk() [][]byte {
	if m != nil {
		return m.PartsClk
	}
	return nil
}

func (m *ProtoReplyJoin) GetReplicaID() int32 {
	if m != nil && m.ReplicaID != nil {
		return *m.ReplicaID
	}
	return 0
}

func (m *ProtoReplyJoin) GetReplicaIP() string {
	if m != nil && m.ReplicaIP != nil {
		return *m.ReplicaIP
	}
	return ""
}

type ProtoRequestBucket struct {
	Buckets []string `protobuf:"bytes,1,rep,name=buckets" json:"buckets,omitempty"`
	//repeated ProtoClock partsClk = 2;
	//repeated bytes partsClk = 2;
	ReplicaID            *int32   `protobuf:"varint,2,req,name=replicaID" json:"replicaID,omitempty"`
	ReplicaIP            *string  `protobuf:"bytes,3,req,name=replicaIP" json:"replicaIP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoRequestBucket) Reset()         { *m = ProtoRequestBucket{} }
func (m *ProtoRequestBucket) String() string { return proto.CompactTextString(m) }
func (*ProtoRequestBucket) ProtoMessage()    {}
func (*ProtoRequestBucket) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{29}
}

func (m *ProtoRequestBucket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoRequestBucket.Unmarshal(m, b)
}
func (m *ProtoRequestBucket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoRequestBucket.Marshal(b, m, deterministic)
}
func (m *ProtoRequestBucket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoRequestBucket.Merge(m, src)
}
func (m *ProtoRequestBucket) XXX_Size() int {
	return xxx_messageInfo_ProtoRequestBucket.Size(m)
}
func (m *ProtoRequestBucket) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoRequestBucket.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoRequestBucket proto.InternalMessageInfo

func (m *ProtoRequestBucket) GetBuckets() []string {
	if m != nil {
		return m.Buckets
	}
	return nil
}

func (m *ProtoRequestBucket) GetReplicaID() int32 {
	if m != nil && m.ReplicaID != nil {
		return *m.ReplicaID
	}
	return 0
}

func (m *ProtoRequestBucket) GetReplicaIP() string {
	if m != nil && m.ReplicaIP != nil {
		return *m.ReplicaIP
	}
	return ""
}

//This contains CRDTs for all the buckets requested, not just one bucket.
type ProtoReplyBucket struct {
	ReplicaID            *int32            `protobuf:"varint,1,req,name=replicaID" json:"replicaID,omitempty"`
	Clk                  []byte            `protobuf:"bytes,2,req,name=clk" json:"clk,omitempty"`
	Parts                []*ProtoPartition `protobuf:"bytes,3,rep,name=parts" json:"parts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ProtoReplyBucket) Reset()         { *m = ProtoReplyBucket{} }
func (m *ProtoReplyBucket) String() string { return proto.CompactTextString(m) }
func (*ProtoReplyBucket) ProtoMessage()    {}
func (*ProtoReplyBucket) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{30}
}

func (m *ProtoReplyBucket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoReplyBucket.Unmarshal(m, b)
}
func (m *ProtoReplyBucket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoReplyBucket.Marshal(b, m, deterministic)
}
func (m *ProtoReplyBucket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoReplyBucket.Merge(m, src)
}
func (m *ProtoReplyBucket) XXX_Size() int {
	return xxx_messageInfo_ProtoReplyBucket.Size(m)
}
func (m *ProtoReplyBucket) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoReplyBucket.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoReplyBucket proto.InternalMessageInfo

func (m *ProtoReplyBucket) GetReplicaID() int32 {
	if m != nil && m.ReplicaID != nil {
		return *m.ReplicaID
	}
	return 0
}

func (m *ProtoReplyBucket) GetClk() []byte {
	if m != nil {
		return m.Clk
	}
	return nil
}

func (m *ProtoReplyBucket) GetParts() []*ProtoPartition {
	if m != nil {
		return m.Parts
	}
	return nil
}

type ProtoPartition struct {
	States               []*ProtoCRDT `protobuf:"bytes,1,rep,name=states" json:"states,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ProtoPartition) Reset()         { *m = ProtoPartition{} }
func (m *ProtoPartition) String() string { return proto.CompactTextString(m) }
func (*ProtoPartition) ProtoMessage()    {}
func (*ProtoPartition) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{31}
}

func (m *ProtoPartition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoPartition.Unmarshal(m, b)
}
func (m *ProtoPartition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoPartition.Marshal(b, m, deterministic)
}
func (m *ProtoPartition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoPartition.Merge(m, src)
}
func (m *ProtoPartition) XXX_Size() int {
	return xxx_messageInfo_ProtoPartition.Size(m)
}
func (m *ProtoPartition) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoPartition.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoPartition proto.InternalMessageInfo

func (m *ProtoPartition) GetStates() []*ProtoCRDT {
	if m != nil {
		return m.States
	}
	return nil
}

type ProtoCRDT struct {
	KeyHash              *uint64     `protobuf:"varint,1,req,name=keyHash" json:"keyHash,omitempty"`
	Type                 *CRDTType   `protobuf:"varint,2,req,name=type,enum=CRDTType" json:"type,omitempty"`
	State                *ProtoState `protobuf:"bytes,3,req,name=state" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ProtoCRDT) Reset()         { *m = ProtoCRDT{} }
func (m *ProtoCRDT) String() string { return proto.CompactTextString(m) }
func (*ProtoCRDT) ProtoMessage()    {}
func (*ProtoCRDT) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{32}
}

func (m *ProtoCRDT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoCRDT.Unmarshal(m, b)
}
func (m *ProtoCRDT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoCRDT.Marshal(b, m, deterministic)
}
func (m *ProtoCRDT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoCRDT.Merge(m, src)
}
func (m *ProtoCRDT) XXX_Size() int {
	return xxx_messageInfo_ProtoCRDT.Size(m)
}
func (m *ProtoCRDT) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoCRDT.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoCRDT proto.InternalMessageInfo

func (m *ProtoCRDT) GetKeyHash() uint64 {
	if m != nil && m.KeyHash != nil {
		return *m.KeyHash
	}
	return 0
}

func (m *ProtoCRDT) GetType() CRDTType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return CRDTType_COUNTER
}

func (m *ProtoCRDT) GetState() *ProtoState {
	if m != nil {
		return m.State
	}
	return nil
}

//TODO: Clock for genericInversibleCRDT initialization? And replicaID.
type ProtoState struct {
	Counter              *ProtoCounterState `protobuf:"bytes,1,opt,name=counter" json:"counter,omitempty"`
	Lwwreg               *ProtoLWWRegState  `protobuf:"bytes,2,opt,name=lwwreg" json:"lwwreg,omitempty"`
	Awset                *ProtoAWSetState   `protobuf:"bytes,3,opt,name=awset" json:"awset,omitempty"`
	Ormap                *ProtoORMapState   `protobuf:"bytes,4,opt,name=ormap" json:"ormap,omitempty"`
	Embmap               *ProtoEmbMapState  `protobuf:"bytes,5,opt,name=embmap" json:"embmap,omitempty"`
	Maxmin               *ProtoMaxMinState  `protobuf:"bytes,6,opt,name=maxmin" json:"maxmin,omitempty"`
	Topk                 *ProtoTopKState    `protobuf:"bytes,7,opt,name=topk" json:"topk,omitempty"`
	Avg                  *ProtoAvgState     `protobuf:"bytes,8,opt,name=avg" json:"avg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ProtoState) Reset()         { *m = ProtoState{} }
func (m *ProtoState) String() string { return proto.CompactTextString(m) }
func (*ProtoState) ProtoMessage()    {}
func (*ProtoState) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{33}
}

func (m *ProtoState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoState.Unmarshal(m, b)
}
func (m *ProtoState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoState.Marshal(b, m, deterministic)
}
func (m *ProtoState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoState.Merge(m, src)
}
func (m *ProtoState) XXX_Size() int {
	return xxx_messageInfo_ProtoState.Size(m)
}
func (m *ProtoState) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoState.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoState proto.InternalMessageInfo

func (m *ProtoState) GetCounter() *ProtoCounterState {
	if m != nil {
		return m.Counter
	}
	return nil
}

func (m *ProtoState) GetLwwreg() *ProtoLWWRegState {
	if m != nil {
		return m.Lwwreg
	}
	return nil
}

func (m *ProtoState) GetAwset() *ProtoAWSetState {
	if m != nil {
		return m.Awset
	}
	return nil
}

func (m *ProtoState) GetOrmap() *ProtoORMapState {
	if m != nil {
		return m.Ormap
	}
	return nil
}

func (m *ProtoState) GetEmbmap() *ProtoEmbMapState {
	if m != nil {
		return m.Embmap
	}
	return nil
}

func (m *ProtoState) GetMaxmin() *ProtoMaxMinState {
	if m != nil {
		return m.Maxmin
	}
	return nil
}

func (m *ProtoState) GetTopk() *ProtoTopKState {
	if m != nil {
		return m.Topk
	}
	return nil
}

func (m *ProtoState) GetAvg() *ProtoAvgState {
	if m != nil {
		return m.Avg
	}
	return nil
}

type ProtoReplyEmpty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoReplyEmpty) Reset()         { *m = ProtoReplyEmpty{} }
func (m *ProtoReplyEmpty) String() string { return proto.CompactTextString(m) }
func (*ProtoReplyEmpty) ProtoMessage()    {}
func (*ProtoReplyEmpty) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{34}
}

func (m *ProtoReplyEmpty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoReplyEmpty.Unmarshal(m, b)
}
func (m *ProtoReplyEmpty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoReplyEmpty.Marshal(b, m, deterministic)
}
func (m *ProtoReplyEmpty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoReplyEmpty.Merge(m, src)
}
func (m *ProtoReplyEmpty) XXX_Size() int {
	return xxx_messageInfo_ProtoReplyEmpty.Size(m)
}
func (m *ProtoReplyEmpty) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoReplyEmpty.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoReplyEmpty proto.InternalMessageInfo

//*****STATES*****
type ProtoCounterState struct {
	Value                *int32   `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoCounterState) Reset()         { *m = ProtoCounterState{} }
func (m *ProtoCounterState) String() string { return proto.CompactTextString(m) }
func (*ProtoCounterState) ProtoMessage()    {}
func (*ProtoCounterState) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{35}
}

func (m *ProtoCounterState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoCounterState.Unmarshal(m, b)
}
func (m *ProtoCounterState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoCounterState.Marshal(b, m, deterministic)
}
func (m *ProtoCounterState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoCounterState.Merge(m, src)
}
func (m *ProtoCounterState) XXX_Size() int {
	return xxx_messageInfo_ProtoCounterState.Size(m)
}
func (m *ProtoCounterState) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoCounterState.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoCounterState proto.InternalMessageInfo

func (m *ProtoCounterState) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

type ProtoLWWRegState struct {
	Value                []byte   `protobuf:"bytes,1,req,name=value" json:"value,omitempty"`
	Ts                   *int64   `protobuf:"varint,2,req,name=ts" json:"ts,omitempty"`
	ReplicaID            *int32   `protobuf:"varint,3,req,name=replicaID" json:"replicaID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoLWWRegState) Reset()         { *m = ProtoLWWRegState{} }
func (m *ProtoLWWRegState) String() string { return proto.CompactTextString(m) }
func (*ProtoLWWRegState) ProtoMessage()    {}
func (*ProtoLWWRegState) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{36}
}

func (m *ProtoLWWRegState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoLWWRegState.Unmarshal(m, b)
}
func (m *ProtoLWWRegState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoLWWRegState.Marshal(b, m, deterministic)
}
func (m *ProtoLWWRegState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoLWWRegState.Merge(m, src)
}
func (m *ProtoLWWRegState) XXX_Size() int {
	return xxx_messageInfo_ProtoLWWRegState.Size(m)
}
func (m *ProtoLWWRegState) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoLWWRegState.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoLWWRegState proto.InternalMessageInfo

func (m *ProtoLWWRegState) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ProtoLWWRegState) GetTs() int64 {
	if m != nil && m.Ts != nil {
		return *m.Ts
	}
	return 0
}

func (m *ProtoLWWRegState) GetReplicaID() int32 {
	if m != nil && m.ReplicaID != nil {
		return *m.ReplicaID
	}
	return 0
}

type ProtoAWSetState struct {
	Elems                []*ProtoValueUniques `protobuf:"bytes,1,rep,name=elems" json:"elems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ProtoAWSetState) Reset()         { *m = ProtoAWSetState{} }
func (m *ProtoAWSetState) String() string { return proto.CompactTextString(m) }
func (*ProtoAWSetState) ProtoMessage()    {}
func (*ProtoAWSetState) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{37}
}

func (m *ProtoAWSetState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoAWSetState.Unmarshal(m, b)
}
func (m *ProtoAWSetState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoAWSetState.Marshal(b, m, deterministic)
}
func (m *ProtoAWSetState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoAWSetState.Merge(m, src)
}
func (m *ProtoAWSetState) XXX_Size() int {
	return xxx_messageInfo_ProtoAWSetState.Size(m)
}
func (m *ProtoAWSetState) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoAWSetState.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoAWSetState proto.InternalMessageInfo

func (m *ProtoAWSetState) GetElems() []*ProtoValueUniques {
	if m != nil {
		return m.Elems
	}
	return nil
}

type ProtoORMapState struct {
	Entries              []*ProtoORMapRemove `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ProtoORMapState) Reset()         { *m = ProtoORMapState{} }
func (m *ProtoORMapState) String() string { return proto.CompactTextString(m) }
func (*ProtoORMapState) ProtoMessage()    {}
func (*ProtoORMapState) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{38}
}

func (m *ProtoORMapState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoORMapState.Unmarshal(m, b)
}
func (m *ProtoORMapState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoORMapState.Marshal(b, m, deterministic)
}
func (m *ProtoORMapState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoORMapState.Merge(m, src)
}
func (m *ProtoORMapState) XXX_Size() int {
	return xxx_messageInfo_ProtoORMapState.Size(m)
}
func (m *ProtoORMapState) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoORMapState.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoORMapState proto.InternalMessageInfo

func (m *ProtoORMapState) GetEntries() []*ProtoORMapRemove {
	if m != nil {
		return m.Entries
	}
	return nil
}

type ProtoEmbMapState struct {
	Crdts   []*ProtoEmbMapEntry  `protobuf:"bytes,1,rep,name=crdts" json:"crdts,omitempty"`
	Removes []*ProtoEmbMapRemove `protobuf:"bytes,2,rep,name=removes" json:"removes,omitempty"`
	//required ProtoClock rmvClock = 3;
	RmvClock             []byte   `protobuf:"bytes,3,req,name=rmvClock" json:"rmvClock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoEmbMapState) Reset()         { *m = ProtoEmbMapState{} }
func (m *ProtoEmbMapState) String() string { return proto.CompactTextString(m) }
func (*ProtoEmbMapState) ProtoMessage()    {}
func (*ProtoEmbMapState) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{39}
}

func (m *ProtoEmbMapState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoEmbMapState.Unmarshal(m, b)
}
func (m *ProtoEmbMapState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoEmbMapState.Marshal(b, m, deterministic)
}
func (m *ProtoEmbMapState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoEmbMapState.Merge(m, src)
}
func (m *ProtoEmbMapState) XXX_Size() int {
	return xxx_messageInfo_ProtoEmbMapState.Size(m)
}
func (m *ProtoEmbMapState) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoEmbMapState.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoEmbMapState proto.InternalMessageInfo

func (m *ProtoEmbMapState) GetCrdts() []*ProtoEmbMapEntry {
	if m != nil {
		return m.Crdts
	}
	return nil
}

func (m *ProtoEmbMapState) GetRemoves() []*ProtoEmbMapRemove {
	if m != nil {
		return m.Removes
	}
	return nil
}

func (m *ProtoEmbMapState) GetRmvClock() []byte {
	if m != nil {
		return m.RmvClock
	}
	return nil
}

type ProtoEmbMapEntry struct {
	Key                  *string     `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Type                 *CRDTType   `protobuf:"varint,2,req,name=type,enum=CRDTType" json:"type,omitempty"`
	State                *ProtoState `protobuf:"bytes,3,req,name=state" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ProtoEmbMapEntry) Reset()         { *m = ProtoEmbMapEntry{} }
func (m *ProtoEmbMapEntry) String() string { return proto.CompactTextString(m) }
func (*ProtoEmbMapEntry) ProtoMessage()    {}
func (*ProtoEmbMapEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{40}
}

func (m *ProtoEmbMapEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoEmbMapEntry.Unmarshal(m, b)
}
func (m *ProtoEmbMapEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoEmbMapEntry.Marshal(b, m, deterministic)
}
func (m *ProtoEmbMapEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoEmbMapEntry.Merge(m, src)
}
func (m *ProtoEmbMapEntry) XXX_Size() int {
	return xxx_messageInfo_ProtoEmbMapEntry.Size(m)
}
func (m *ProtoEmbMapEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoEmbMapEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoEmbMapEntry proto.InternalMessageInfo

func (m *ProtoEmbMapEntry) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *ProtoEmbMapEntry) GetType() CRDTType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return CRDTType_COUNTER
}

func (m *ProtoEmbMapEntry) GetState() *ProtoState {
	if m != nil {
		return m.State
	}
	return nil
}

type ProtoEmbMapRemove struct {
	Key *string `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	//TODO: Marks?
	Clks                 []*ProtoStableClock `protobuf:"bytes,2,rep,name=clks" json:"clks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ProtoEmbMapRemove) Reset()         { *m = ProtoEmbMapRemove{} }
func (m *ProtoEmbMapRemove) String() string { return proto.CompactTextString(m) }
func (*ProtoEmbMapRemove) ProtoMessage()    {}
func (*ProtoEmbMapRemove) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{41}
}

func (m *ProtoEmbMapRemove) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoEmbMapRemove.Unmarshal(m, b)
}
func (m *ProtoEmbMapRemove) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoEmbMapRemove.Marshal(b, m, deterministic)
}
func (m *ProtoEmbMapRemove) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoEmbMapRemove.Merge(m, src)
}
func (m *ProtoEmbMapRemove) XXX_Size() int {
	return xxx_messageInfo_ProtoEmbMapRemove.Size(m)
}
func (m *ProtoEmbMapRemove) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoEmbMapRemove.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoEmbMapRemove proto.InternalMessageInfo

func (m *ProtoEmbMapRemove) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *ProtoEmbMapRemove) GetClks() []*ProtoStableClock {
	if m != nil {
		return m.Clks
	}
	return nil
}

type ProtoMaxMinState struct {
	Value                *int64   `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoMaxMinState) Reset()         { *m = ProtoMaxMinState{} }
func (m *ProtoMaxMinState) String() string { return proto.CompactTextString(m) }
func (*ProtoMaxMinState) ProtoMessage()    {}
func (*ProtoMaxMinState) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{42}
}

func (m *ProtoMaxMinState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoMaxMinState.Unmarshal(m, b)
}
func (m *ProtoMaxMinState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoMaxMinState.Marshal(b, m, deterministic)
}
func (m *ProtoMaxMinState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoMaxMinState.Merge(m, src)
}
func (m *ProtoMaxMinState) XXX_Size() int {
	return xxx_messageInfo_ProtoMaxMinState.Size(m)
}
func (m *ProtoMaxMinState) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoMaxMinState.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoMaxMinState proto.InternalMessageInfo

func (m *ProtoMaxMinState) GetValue() int64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

type ProtoAvgState struct {
	Sum                  *int64   `protobuf:"varint,1,req,name=sum" json:"sum,omitempty"`
	NAdds                *int64   `protobuf:"varint,2,req,name=nAdds" json:"nAdds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoAvgState) Reset()         { *m = ProtoAvgState{} }
func (m *ProtoAvgState) String() string { return proto.CompactTextString(m) }
func (*ProtoAvgState) ProtoMessage()    {}
func (*ProtoAvgState) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{43}
}

func (m *ProtoAvgState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoAvgState.Unmarshal(m, b)
}
func (m *ProtoAvgState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoAvgState.Marshal(b, m, deterministic)
}
func (m *ProtoAvgState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoAvgState.Merge(m, src)
}
func (m *ProtoAvgState) XXX_Size() int {
	return xxx_messageInfo_ProtoAvgState.Size(m)
}
func (m *ProtoAvgState) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoAvgState.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoAvgState proto.InternalMessageInfo

func (m *ProtoAvgState) GetSum() int64 {
	if m != nil && m.Sum != nil {
		return *m.Sum
	}
	return 0
}

func (m *ProtoAvgState) GetNAdds() int64 {
	if m != nil && m.NAdds != nil {
		return *m.NAdds
	}
	return 0
}

//TODO: This one could be changed to just include the list of elements and maxElems,
//and then have everything else be calculated on the moment.
type ProtoTopKState struct {
	Elems []*ProtoTopKElement `protobuf:"bytes,1,rep,name=elems" json:"elems,omitempty"`
	Rems  []*ProtoTopKIdVc    `protobuf:"bytes,2,rep,name=rems" json:"rems,omitempty"`
	//notTop maybe deserves its own msg? Since the key will be repeated.
	NotTop               []*ProtoTopKElement `protobuf:"bytes,3,rep,name=notTop" json:"notTop,omitempty"`
	Smallest             *ProtoTopKElement   `protobuf:"bytes,4,opt,name=smallest" json:"smallest,omitempty"`
	MaxElems             *int32              `protobuf:"varint,5,req,name=maxElems" json:"maxElems,omitempty"`
	Vc                   []byte              `protobuf:"bytes,6,req,name=vc" json:"vc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ProtoTopKState) Reset()         { *m = ProtoTopKState{} }
func (m *ProtoTopKState) String() string { return proto.CompactTextString(m) }
func (*ProtoTopKState) ProtoMessage()    {}
func (*ProtoTopKState) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{44}
}

func (m *ProtoTopKState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoTopKState.Unmarshal(m, b)
}
func (m *ProtoTopKState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoTopKState.Marshal(b, m, deterministic)
}
func (m *ProtoTopKState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoTopKState.Merge(m, src)
}
func (m *ProtoTopKState) XXX_Size() int {
	return xxx_messageInfo_ProtoTopKState.Size(m)
}
func (m *ProtoTopKState) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoTopKState.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoTopKState proto.InternalMessageInfo

func (m *ProtoTopKState) GetElems() []*ProtoTopKElement {
	if m != nil {
		return m.Elems
	}
	return nil
}

func (m *ProtoTopKState) GetRems() []*ProtoTopKIdVc {
	if m != nil {
		return m.Rems
	}
	return nil
}

func (m *ProtoTopKState) GetNotTop() []*ProtoTopKElement {
	if m != nil {
		return m.NotTop
	}
	return nil
}

func (m *ProtoTopKState) GetSmallest() *ProtoTopKElement {
	if m != nil {
		return m.Smallest
	}
	return nil
}

func (m *ProtoTopKState) GetMaxElems() int32 {
	if m != nil && m.MaxElems != nil {
		return *m.MaxElems
	}
	return 0
}

func (m *ProtoTopKState) GetVc() []byte {
	if m != nil {
		return m.Vc
	}
	return nil
}

func init() {
	proto.RegisterType((*ProtoStableClock)(nil), "ProtoStableClock")
	proto.RegisterType((*ProtoReplicatePart)(nil), "ProtoReplicatePart")
	proto.RegisterType((*ProtoRemoteTxn)(nil), "ProtoRemoteTxn")
	proto.RegisterType((*ProtoDownstreamUpd)(nil), "ProtoDownstreamUpd")
	proto.RegisterType((*ProtoOpDownstream)(nil), "ProtoOpDownstream")
	proto.RegisterType((*ProtoCounterDownstream)(nil), "ProtoCounterDownstream")
	proto.RegisterType((*ProtoLWWRegisterDownstream)(nil), "ProtoLWWRegisterDownstream")
	proto.RegisterType((*ProtoSetDownstream)(nil), "ProtoSetDownstream")
	proto.RegisterType((*ProtoORMapDownstream)(nil), "ProtoORMapDownstream")
	proto.RegisterType((*ProtoTopKRmvDownstream)(nil), "ProtoTopKRmvDownstream")
	proto.RegisterType((*ProtoTopKRmvRemove)(nil), "ProtoTopKRmvRemove")
	proto.RegisterType((*ProtoAvgDownstream)(nil), "ProtoAvgDownstream")
	proto.RegisterType((*ProtoMaxMinDownstream)(nil), "ProtoMaxMinDownstream")
	proto.RegisterType((*ProtoMaxDownstream)(nil), "ProtoMaxDownstream")
	proto.RegisterType((*ProtoMinDownstream)(nil), "ProtoMinDownstream")
	proto.RegisterType((*ProtoValueUnique)(nil), "ProtoValueUnique")
	proto.RegisterType((*ProtoValueUniques)(nil), "ProtoValueUniques")
	proto.RegisterType((*ProtoKeyValueUnique)(nil), "ProtoKeyValueUnique")
	proto.RegisterType((*ProtoORMapRemove)(nil), "ProtoORMapRemove")
	proto.RegisterType((*ProtoTopKElement)(nil), "ProtoTopKElement")
	proto.RegisterType((*ProtoTopKIdVc)(nil), "ProtoTopKIdVc")
	proto.RegisterType((*ProtoRWEmbMapDownstream)(nil), "ProtoRWEmbMapDownstream")
	proto.RegisterType((*ProtoRWEmbMapUpdates)(nil), "ProtoRWEmbMapUpdates")
	proto.RegisterType((*ProtoRWEmbMapRemoves)(nil), "ProtoRWEmbMapRemoves")
	proto.RegisterType((*ProtoEmbMapUpd)(nil), "ProtoEmbMapUpd")
	proto.RegisterType((*ProtoResetDownstream)(nil), "ProtoResetDownstream")
	proto.RegisterType((*ProtoRemoteID)(nil), "ProtoRemoteID")
	proto.RegisterType((*ProtoJoin)(nil), "ProtoJoin")
	proto.RegisterType((*ProtoReplyJoin)(nil), "ProtoReplyJoin")
	proto.RegisterType((*ProtoRequestBucket)(nil), "ProtoRequestBucket")
	proto.RegisterType((*ProtoReplyBucket)(nil), "ProtoReplyBucket")
	proto.RegisterType((*ProtoPartition)(nil), "ProtoPartition")
	proto.RegisterType((*ProtoCRDT)(nil), "ProtoCRDT")
	proto.RegisterType((*ProtoState)(nil), "ProtoState")
	proto.RegisterType((*ProtoReplyEmpty)(nil), "ProtoReplyEmpty")
	proto.RegisterType((*ProtoCounterState)(nil), "ProtoCounterState")
	proto.RegisterType((*ProtoLWWRegState)(nil), "ProtoLWWRegState")
	proto.RegisterType((*ProtoAWSetState)(nil), "ProtoAWSetState")
	proto.RegisterType((*ProtoORMapState)(nil), "ProtoORMapState")
	proto.RegisterType((*ProtoEmbMapState)(nil), "ProtoEmbMapState")
	proto.RegisterType((*ProtoEmbMapEntry)(nil), "ProtoEmbMapEntry")
	proto.RegisterType((*ProtoEmbMapRemove)(nil), "ProtoEmbMapRemove")
	proto.RegisterType((*ProtoMaxMinState)(nil), "ProtoMaxMinState")
	proto.RegisterType((*ProtoAvgState)(nil), "ProtoAvgState")
	proto.RegisterType((*ProtoTopKState)(nil), "ProtoTopKState")
}

func init() { proto.RegisterFile("replicator.proto", fileDescriptor_e741e2c5586b74b6) }

var fileDescriptor_e741e2c5586b74b6 = []byte{
	// 1549 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0xeb, 0x6e, 0xdc, 0x44,
	0x14, 0x56, 0xd6, 0xeb, 0x5c, 0x4e, 0x42, 0x2e, 0xd3, 0x36, 0x5d, 0x05, 0x84, 0xd2, 0x81, 0xb4,
	0x09, 0xd0, 0x54, 0x8a, 0x40, 0xad, 0x84, 0x84, 0x68, 0x93, 0x54, 0x84, 0xb6, 0x6c, 0x34, 0x4d,
	0x13, 0xe0, 0x0f, 0x38, 0xf6, 0x68, 0xe3, 0xee, 0xfa, 0x82, 0x3d, 0xbb, 0xc9, 0x22, 0x7e, 0x21,
	0xf1, 0x82, 0x3c, 0x01, 0x12, 0x2f, 0x82, 0xce, 0xcc, 0xb1, 0x3d, 0xde, 0x38, 0x49, 0x91, 0xe0,
	0x9f, 0x67, 0xce, 0x37, 0xe7, 0x32, 0x73, 0x2e, 0xdf, 0x2e, 0x2c, 0x67, 0x32, 0x1d, 0x84, 0xbe,
	0xa7, 0x92, 0x6c, 0x3b, 0xcd, 0x12, 0x95, 0xac, 0x2d, 0x7a, 0xb1, 0x0a, 0x83, 0x44, 0x49, 0xb3,
	0xe6, 0x2f, 0x61, 0xf9, 0x10, 0x3f, 0x5e, 0x2b, 0xef, 0x74, 0x20, 0x77, 0x07, 0x89, 0xdf, 0x67,
	0x6b, 0x30, 0x9b, 0xcb, 0x38, 0x90, 0xd9, 0xc1, 0x5e, 0x67, 0x6a, 0xbd, 0xb5, 0xe9, 0x8a, 0x72,
	0xcd, 0x3e, 0x80, 0x39, 0xd2, 0x79, 0x94, 0x77, 0x5a, 0xeb, 0xad, 0x4d, 0x47, 0x54, 0x1b, 0x7c,
	0x08, 0x4c, 0x6b, 0x13, 0x64, 0x56, 0x1e, 0x7a, 0x99, 0xba, 0x56, 0xdf, 0x3d, 0x70, 0xd4, 0x45,
	0xac, 0x35, 0xcd, 0xef, 0x2c, 0x6d, 0xd3, 0xe9, 0x28, 0x51, 0xf2, 0xe8, 0x22, 0x16, 0x28, 0x63,
	0xeb, 0x30, 0x9f, 0x7a, 0x99, 0x0a, 0x55, 0x98, 0xc4, 0x07, 0x7b, 0x1d, 0x47, 0x1b, 0xb5, 0xb7,
	0xf8, 0x09, 0x2c, 0xd6, 0x0f, 0xa2, 0x9b, 0x2a, 0x8c, 0x64, 0xae, 0xbc, 0x28, 0xd5, 0x36, 0x17,
	0x44, 0xb5, 0xc1, 0x1e, 0x40, 0x7b, 0x98, 0x06, 0xe8, 0xbf, 0xb3, 0x39, 0xbf, 0x73, 0xcb, 0x58,
	0xdd, 0x4b, 0xce, 0xe3, 0x5c, 0x65, 0xd2, 0x8b, 0xde, 0xa4, 0x81, 0xd0, 0x00, 0xde, 0xa3, 0x78,
	0x6a, 0x32, 0xf6, 0x10, 0xe6, 0xfa, 0x72, 0x7c, 0xe8, 0x65, 0x5e, 0x94, 0x6b, 0xe5, 0xe8, 0xf9,
	0xd3, 0xf4, 0xf4, 0x59, 0x32, 0x8c, 0x83, 0xee, 0xe9, 0x5b, 0xe9, 0x2b, 0x51, 0x21, 0x18, 0x87,
	0x56, 0x92, 0x52, 0x84, 0xcc, 0xd8, 0xea, 0xa6, 0x95, 0x46, 0xd1, 0x4a, 0x52, 0xfe, 0x97, 0x03,
	0x2b, 0x97, 0x24, 0xec, 0x0b, 0x98, 0xf3, 0x93, 0x61, 0xac, 0x64, 0xd6, 0xc5, 0x28, 0xa6, 0x36,
	0xe7, 0x77, 0xee, 0x1a, 0x05, 0xbb, 0x66, 0xdb, 0xd2, 0x52, 0x21, 0xd9, 0x16, 0xb8, 0xb9, 0x54,
	0x5d, 0xb4, 0x39, 0x55, 0xc5, 0xf7, 0x5a, 0x2a, 0x0b, 0x6e, 0x10, 0x68, 0x41, 0x25, 0x69, 0x3f,
	0x8b, 0x46, 0xdd, 0xb4, 0xe3, 0xd8, 0x16, 0x8e, 0x92, 0xf4, 0x85, 0x88, 0x46, 0xb6, 0x85, 0x12,
	0xc9, 0x1e, 0xc3, 0xec, 0xe0, 0xfc, 0x3c, 0x93, 0xbd, 0x6e, 0xda, 0x69, 0xeb, 0x53, 0xef, 0x9b,
	0x53, 0x2f, 0x4f, 0x4e, 0x84, 0xec, 0x85, 0x79, 0xdd, 0xb7, 0x12, 0xcc, 0x1e, 0xc1, 0x4c, 0x92,
	0x45, 0x5e, 0xda, 0x4d, 0x3b, 0xae, 0x3e, 0x77, 0x87, 0x2e, 0x44, 0xbc, 0xf2, 0xec, 0x3b, 0x29,
	0x50, 0x18, 0x8b, 0x37, 0x42, 0x33, 0xd3, 0x76, 0x2c, 0x4f, 0x47, 0x3d, 0x3b, 0x16, 0x8d, 0x60,
	0x3b, 0x30, 0x1b, 0x79, 0x17, 0x51, 0x18, 0x77, 0xd3, 0xce, 0x8c, 0x46, 0xaf, 0x1a, 0xf4, 0x2b,
	0xef, 0xe2, 0x55, 0x18, 0xdb, 0xfe, 0x14, 0x38, 0xf6, 0x04, 0x20, 0x3b, 0x97, 0xd1, 0xa9, 0x71,
	0x69, 0x56, 0x9f, 0xea, 0x50, 0x16, 0x9e, 0xec, 0x47, 0xa7, 0x75, 0xaf, 0x2c, 0x2c, 0x46, 0x92,
	0x49, 0x73, 0xcd, 0x4b, 0x76, 0x24, 0x02, 0x37, 0xed, 0x48, 0x08, 0xc5, 0x9f, 0xc3, 0x6a, 0xf3,
	0xd3, 0xb1, 0xdb, 0xe0, 0x86, 0xf9, 0x41, 0xec, 0xeb, 0x5c, 0x9a, 0x15, 0x66, 0xc1, 0x56, 0x61,
	0xda, 0x3f, 0xf3, 0xe2, 0x9e, 0xd4, 0xa9, 0xe3, 0x0a, 0x5a, 0xf1, 0x9f, 0x61, 0xed, 0xea, 0xab,
	0x46, 0x5d, 0x23, 0x6f, 0x30, 0x94, 0x94, 0xf4, 0x66, 0xc1, 0x16, 0xa1, 0xa5, 0x8a, 0x72, 0x6d,
	0xa9, 0xdc, 0xaa, 0x62, 0x2a, 0x28, 0x57, 0x54, 0x1b, 0xdc, 0xa7, 0xac, 0xaf, 0x65, 0x0c, 0xdb,
	0x80, 0xb6, 0x17, 0x04, 0x98, 0xf0, 0x58, 0x34, 0x2b, 0x26, 0xda, 0x63, 0x54, 0xff, 0x26, 0x0e,
	0x7f, 0x19, 0x4a, 0xa1, 0xc5, 0xec, 0x3e, 0xb4, 0x33, 0x19, 0x15, 0xb5, 0xc5, 0x2e, 0xc1, 0x72,
	0xa1, 0xe5, 0xbc, 0x07, 0xb7, 0x9b, 0x5e, 0x9e, 0x6d, 0xd6, 0xcc, 0xdc, 0x36, 0xe7, 0x5f, 0xc8,
	0xf1, 0x65, 0x4b, 0x1b, 0x35, 0x4b, 0x2b, 0x56, 0x22, 0x61, 0x1f, 0x18, 0x49, 0x32, 0x74, 0x46,
	0xf7, 0x7e, 0x29, 0xa1, 0x9b, 0x23, 0x42, 0xd8, 0xfe, 0x40, 0x46, 0x32, 0x56, 0x64, 0xe7, 0x41,
	0x69, 0xc7, 0xca, 0x40, 0xd2, 0x56, 0xb3, 0xf4, 0x84, 0xee, 0xad, 0x26, 0x63, 0xcb, 0xe0, 0x8c,
	0x7c, 0x63, 0x64, 0x41, 0xe0, 0x27, 0xee, 0x84, 0xd4, 0x7d, 0x5c, 0x81, 0x9f, 0xfc, 0x39, 0x9d,
	0xac, 0xe5, 0xb5, 0xee, 0x9b, 0xc3, 0xe8, 0xb8, 0x7c, 0x4e, 0x47, 0x94, 0x6b, 0x7c, 0xe7, 0xf8,
	0x69, 0x10, 0x14, 0x8f, 0x6a, 0x16, 0x5c, 0xc2, 0x9d, 0xc6, 0x8c, 0x67, 0x1b, 0xe0, 0x44, 0xde,
	0x05, 0xf5, 0x90, 0x5b, 0x65, 0x59, 0x58, 0x79, 0x8a, 0x72, 0x0d, 0x0b, 0xe3, 0x7a, 0xa4, 0xf5,
	0xd2, 0x41, 0x39, 0xff, 0x84, 0xdc, 0xad, 0x69, 0xa8, 0xa7, 0x9e, 0x43, 0xa9, 0x57, 0x61, 0x6b,
	0xfe, 0x34, 0x63, 0xbf, 0xa6, 0x61, 0x64, 0xbd, 0xf5, 0x15, 0x09, 0xbd, 0x0a, 0xd3, 0x43, 0x2d,
	0xd7, 0xf1, 0xb7, 0x05, 0xad, 0xf8, 0x2e, 0xb5, 0x51, 0x3b, 0xe1, 0xae, 0x50, 0xd1, 0x81, 0x19,
	0x73, 0xc8, 0xbc, 0x44, 0x5b, 0x14, 0x4b, 0xfe, 0x03, 0xdc, 0x6a, 0xc8, 0x3a, 0x7c, 0xb6, 0xbe,
	0x1c, 0x93, 0x12, 0xfc, 0x44, 0x15, 0xd2, 0xa4, 0x8a, 0x76, 0x63, 0x41, 0x14, 0x4b, 0xcb, 0x3f,
	0xa7, 0xe6, 0xdf, 0x77, 0x14, 0xa1, 0x95, 0xa6, 0x0d, 0x7a, 0x37, 0xc1, 0x45, 0x45, 0xd7, 0x15,
	0x91, 0x01, 0xf0, 0x5f, 0x49, 0x9f, 0x95, 0xb5, 0x58, 0xec, 0x61, 0x40, 0x83, 0xb6, 0x15, 0x06,
	0x18, 0x7e, 0xee, 0x27, 0x59, 0xd1, 0x47, 0xcc, 0x82, 0x5a, 0x82, 0xd3, 0xdc, 0x12, 0xda, 0x13,
	0x2d, 0x81, 0x31, 0x68, 0x07, 0x9e, 0xf2, 0x74, 0xd3, 0x5e, 0x10, 0xfa, 0x9b, 0x3f, 0x82, 0xf7,
	0x4a, 0xdb, 0x07, 0xc1, 0xb1, 0x7f, 0xc9, 0xf0, 0x22, 0xb4, 0x46, 0x3e, 0xdd, 0x4c, 0x6b, 0xe4,
	0xf3, 0x04, 0xee, 0x5e, 0xd1, 0x59, 0xd9, 0x56, 0x59, 0x8a, 0x76, 0x2b, 0x25, 0xdc, 0x9b, 0x34,
	0xf0, 0x14, 0x36, 0x0e, 0x5d, 0x8e, 0x5b, 0xb5, 0x72, 0x9c, 0x80, 0x9a, 0x2b, 0x2d, 0x7a, 0xcc,
	0x6f, 0xd4, 0x63, 0x26, 0x14, 0xb1, 0x8f, 0x68, 0xfe, 0x9b, 0xc2, 0x27, 0xd6, 0x51, 0x42, 0xcc,
	0xec, 0x67, 0xf7, 0xc8, 0x7b, 0xab, 0x37, 0x58, 0x24, 0x09, 0x03, 0xba, 0xa1, 0x8d, 0x7e, 0x3f,
	0x61, 0x9d, 0x7c, 0xc3, 0xbb, 0xec, 0xcb, 0xb1, 0xb1, 0x3e, 0x27, 0xf4, 0xf7, 0xbf, 0x6c, 0xd0,
	0x67, 0xc4, 0x77, 0x4a, 0x97, 0x1b, 0x72, 0xe8, 0x43, 0x68, 0xab, 0x71, 0x6a, 0x1e, 0x7d, 0x71,
	0x07, 0xb6, 0x77, 0xc5, 0xde, 0xd1, 0x4f, 0xb8, 0x23, 0xf4, 0x3e, 0xfb, 0x18, 0x9c, 0x61, 0x1a,
	0x68, 0xdd, 0xcd, 0xb4, 0x04, 0xc5, 0x7c, 0xb5, 0x88, 0xa1, 0x3e, 0xd5, 0xf8, 0x43, 0x7a, 0x7b,
	0xc3, 0xb8, 0x6a, 0xbc, 0xb0, 0x24, 0x79, 0x96, 0xc3, 0x1e, 0xcc, 0x69, 0xf8, 0xb7, 0x49, 0x18,
	0x63, 0xd5, 0x9c, 0x0e, 0xfd, 0xbe, 0x54, 0xc5, 0x15, 0x14, 0xcb, 0xba, 0x92, 0xd6, 0x64, 0x0e,
	0x5a, 0xd2, 0x43, 0xed, 0xf7, 0x5c, 0x25, 0x3d, 0xe4, 0xbf, 0x4f, 0x95, 0x24, 0x30, 0x1d, 0x8c,
	0x6f, 0x30, 0xb4, 0x06, 0xb3, 0xc8, 0x1f, 0xf3, 0xdd, 0x41, 0x5f, 0xbf, 0xf0, 0x82, 0x28, 0xd7,
	0xd7, 0x5f, 0x7d, 0xdd, 0x89, 0xf6, 0xa4, 0x13, 0x6f, 0x4b, 0xfe, 0x8b, 0x45, 0xaa, 0x9e, 0x69,
	0x73, 0xff, 0x53, 0xc0, 0x21, 0x95, 0xbe, 0x8e, 0x97, 0x2c, 0x5d, 0xfb, 0x0a, 0x98, 0x24, 0xbe,
	0x0e, 0x58, 0x27, 0x89, 0x3f, 0xe8, 0xb3, 0x0d, 0x70, 0x75, 0xdc, 0x1d, 0xc7, 0xae, 0x84, 0xc3,
	0x82, 0x5a, 0x0b, 0x23, 0xe5, 0x9f, 0xd3, 0xd5, 0x96, 0x02, 0xc6, 0x61, 0x3a, 0x57, 0x58, 0x4b,
	0x54, 0x43, 0x40, 0xb4, 0x54, 0xec, 0x1d, 0x09, 0x92, 0xf0, 0x33, 0x7a, 0x74, 0xdc, 0xc4, 0x3b,
	0xe8, 0xcb, 0xf1, 0x37, 0x5e, 0x7e, 0xa6, 0xfd, 0x6a, 0x8b, 0x62, 0x79, 0x63, 0xa2, 0xde, 0x03,
	0x57, 0x2b, 0xa4, 0x54, 0x9d, 0x2f, 0x4b, 0x51, 0x49, 0x61, 0x24, 0xfc, 0xcf, 0x16, 0x40, 0xb5,
	0xcb, 0x3e, 0x83, 0x19, 0x22, 0xc3, 0xd4, 0x4f, 0x58, 0x8d, 0x34, 0x9b, 0xa3, 0x05, 0x84, 0x6d,
	0xc1, 0xb4, 0xa1, 0xa7, 0xd4, 0x51, 0x56, 0x6c, 0x26, 0x6b, 0xb0, 0x04, 0x60, 0xf7, 0xc1, 0xf5,
	0xce, 0x73, 0xa9, 0x88, 0x29, 0x2f, 0x13, 0x19, 0x3d, 0x79, 0x2d, 0x15, 0xf9, 0xa3, 0xc5, 0x88,
	0xd3, 0xfc, 0x95, 0xb8, 0xf1, 0xb2, 0x45, 0x4d, 0x08, 0xa7, 0xc5, 0x68, 0xda, 0xf0, 0x49, 0x22,
	0xc3, 0x2b, 0x76, 0x27, 0x22, 0xd3, 0x06, 0x80, 0x50, 0x43, 0x5a, 0x89, 0x08, 0xaf, 0xd8, 0xd4,
	0x96, 0xa0, 0x06, 0x80, 0xdd, 0x0d, 0x99, 0x3a, 0x71, 0xe0, 0xa5, 0x8a, 0xaf, 0x18, 0x98, 0x16,
	0xb2, 0x75, 0x70, 0xbc, 0x51, 0x8f, 0x18, 0xef, 0x62, 0xc9, 0xaa, 0x0d, 0x04, 0x45, 0x7c, 0x05,
	0x96, 0xaa, 0xfc, 0xda, 0x8f, 0x52, 0x35, 0xe6, 0x5b, 0x34, 0x5d, 0xed, 0x8b, 0xac, 0x4f, 0x57,
	0xb7, 0x18, 0xe5, 0xc7, 0x94, 0x9d, 0xd6, 0x35, 0xfe, 0x27, 0xdc, 0xf4, 0x4b, 0xf2, 0xaa, 0xba,
	0xf4, 0x6a, 0x5a, 0x4e, 0xdd, 0x34, 0x2d, 0xbf, 0xa2, 0xc3, 0xd5, 0x4b, 0xb0, 0x4f, 0x61, 0x46,
	0xc6, 0x2a, 0x0b, 0xe5, 0x04, 0x0d, 0xb4, 0x79, 0x64, 0x81, 0xe0, 0x7f, 0x4c, 0x51, 0x54, 0xd6,
	0x0b, 0xb1, 0x07, 0xe0, 0xfa, 0x59, 0xa0, 0x26, 0xce, 0x1b, 0xc4, 0x7e, 0xac, 0xb2, 0xb1, 0x30,
	0x72, 0x4c, 0xcb, 0xcc, 0x8c, 0x80, 0xfa, 0x5c, 0xb7, 0xa7, 0x83, 0x28, 0x20, 0xd8, 0xa2, 0xb2,
	0x68, 0xa4, 0x67, 0x8d, 0xbe, 0x85, 0x05, 0x51, 0xae, 0x79, 0xaf, 0xe6, 0x86, 0x36, 0x62, 0x4f,
	0x80, 0xb9, 0x77, 0x9b, 0x00, 0xef, 0x50, 0x58, 0x2f, 0xe9, 0xc1, 0x6d, 0x17, 0x1b, 0x2c, 0x6d,
	0x40, 0xdb, 0x1f, 0xf4, 0xf3, 0xab, 0x87, 0xa5, 0x16, 0xf3, 0x4d, 0x72, 0xdb, 0x4a, 0xda, 0x2b,
	0x88, 0xe0, 0x63, 0x1a, 0x2f, 0x45, 0x46, 0xa2, 0xcd, 0x7c, 0x18, 0x11, 0x08, 0x3f, 0xaf, 0x20,
	0xc0, 0x7f, 0x17, 0x53, 0xa0, 0xcc, 0x77, 0x7c, 0x1f, 0x3b, 0x3d, 0x1a, 0x68, 0xbe, 0x91, 0x33,
	0x5e, 0xfb, 0x3d, 0xb1, 0xb8, 0x5d, 0x23, 0x37, 0x86, 0x51, 0x60, 0x19, 0xc6, 0x89, 0x3a, 0x4a,
	0x52, 0xea, 0x98, 0x0d, 0xda, 0x08, 0xc0, 0x1e, 0xc2, 0x6c, 0x1e, 0x79, 0x83, 0x81, 0xcc, 0x15,
	0xf5, 0x81, 0x06, 0x70, 0x09, 0xc1, 0xf7, 0x8e, 0xbc, 0x8b, 0x7d, 0xed, 0xa9, 0x6b, 0xfe, 0x24,
	0x29, 0xd6, 0x44, 0xa4, 0xa6, 0x0b, 0x22, 0xf5, 0x6c, 0xe6, 0x47, 0x57, 0xff, 0x7b, 0xf3, 0x4f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x66, 0xcd, 0x08, 0xfd, 0xe0, 0x11, 0x00, 0x00,
}
