package crdt

import (
	"clocksi"
	"proto"
)

type CRDT interface {
	//Note: replicaID may not be required by every CRDT - for those, any value can be passed.
	Initialize(startTs *clocksi.Timestamp, replicaID int16) (newCrdt CRDT)

	Read(args ReadArguments, updsNotYetApplied []*UpdateArguments) (state State)

	Update(args UpdateArguments) (downstreamArgs DownstreamArguments)

	//For now only non-uniform CRDTs need to return upds when downstreaming
	Downstream(updTs clocksi.Timestamp, downstreamArgs DownstreamArguments) (otherDownstreamArgs DownstreamArguments)

	IsOperationWellTyped(args UpdateArguments) (ok bool, err error)

	GetCRDTType() proto.CRDTType
}

//The idea is to include here the methods/data common to every CRDT. For now, there's... nothing
type genericCRDT struct {
}

type State interface {
	GetCRDTType() proto.CRDTType
	GetREADType() proto.READType
}

//Represents the update arguments specific to each CRDT.
type UpdateArguments interface {
	GetCRDTType() proto.CRDTType
}

//Represents the update arguments generated by the prepare phase
type DownstreamArguments interface {
	GetCRDTType() proto.CRDTType
	//Returns false if this operation doesn't need to be replicated for every replica or if it is a no-op
	MustReplicate() bool
}

//Represents the read arguments specific to each CRDT.
type ReadArguments interface {
	GetCRDTType() proto.CRDTType
	GetREADType() proto.READType
}

//Represents a read of the whole state
type StateReadArguments struct {
}

func (args StateReadArguments) GetCRDTType() proto.CRDTType { return -1 }

func (args StateReadArguments) GetREADType() proto.READType { return proto.READType_FULL }

type NoOp struct{}

func (op NoOp) GetCRDTType() proto.CRDTType { return -1 }

func (op NoOp) MustReplicate() bool { return false }

type ArgsError struct {
	err  string
	args UpdateArguments
}

func (crdt genericCRDT) initialize() (newCrdt genericCRDT) {
	return genericCRDT{}
}

//Note that this only copies the generic part
func (crdt genericCRDT) copy() (copyCrdt genericCRDT) {
	return genericCRDT{}
}
