// Code generated by protoc-gen-go. DO NOT EDIT.
// source: antidote.proto

package antidote

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CRDTType int32

const (
	CRDTType_COUNTER     CRDTType = 3
	CRDTType_ORSET       CRDTType = 4
	CRDTType_LWWREG      CRDTType = 5
	CRDTType_MVREG       CRDTType = 6
	CRDTType_GMAP        CRDTType = 8
	CRDTType_RWSET       CRDTType = 10
	CRDTType_RRMAP       CRDTType = 11
	CRDTType_FATCOUNTER  CRDTType = 12
	CRDTType_FLAG_EW     CRDTType = 13
	CRDTType_FLAG_DW     CRDTType = 14
	CRDTType_TOPK        CRDTType = 1
	CRDTType_TOPK_RMV    CRDTType = 2
	CRDTType_AVG         CRDTType = 7
	CRDTType_LEADERBOARD CRDTType = 9
	CRDTType_MAXMIN      CRDTType = 0
	CRDTType_ORMAP       CRDTType = 15
)

var CRDTType_name = map[int32]string{
	3:  "COUNTER",
	4:  "ORSET",
	5:  "LWWREG",
	6:  "MVREG",
	8:  "GMAP",
	10: "RWSET",
	11: "RRMAP",
	12: "FATCOUNTER",
	13: "FLAG_EW",
	14: "FLAG_DW",
	1:  "TOPK",
	2:  "TOPK_RMV",
	7:  "AVG",
	9:  "LEADERBOARD",
	0:  "MAXMIN",
	15: "ORMAP",
}

var CRDTType_value = map[string]int32{
	"COUNTER":     3,
	"ORSET":       4,
	"LWWREG":      5,
	"MVREG":       6,
	"GMAP":        8,
	"RWSET":       10,
	"RRMAP":       11,
	"FATCOUNTER":  12,
	"FLAG_EW":     13,
	"FLAG_DW":     14,
	"TOPK":        1,
	"TOPK_RMV":    2,
	"AVG":         7,
	"LEADERBOARD": 9,
	"MAXMIN":      0,
	"ORMAP":       15,
}

func (x CRDTType) Enum() *CRDTType {
	p := new(CRDTType)
	*p = x
	return p
}

func (x CRDTType) String() string {
	return proto.EnumName(CRDTType_name, int32(x))
}

func (x *CRDTType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CRDTType_value, data, "CRDTType")
	if err != nil {
		return err
	}
	*x = CRDTType(value)
	return nil
}

func (CRDTType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{0}
}

type ApbSetUpdate_SetOpType int32

const (
	ApbSetUpdate_ADD    ApbSetUpdate_SetOpType = 1
	ApbSetUpdate_REMOVE ApbSetUpdate_SetOpType = 2
)

var ApbSetUpdate_SetOpType_name = map[int32]string{
	1: "ADD",
	2: "REMOVE",
}

var ApbSetUpdate_SetOpType_value = map[string]int32{
	"ADD":    1,
	"REMOVE": 2,
}

func (x ApbSetUpdate_SetOpType) Enum() *ApbSetUpdate_SetOpType {
	p := new(ApbSetUpdate_SetOpType)
	*p = x
	return p
}

func (x ApbSetUpdate_SetOpType) String() string {
	return proto.EnumName(ApbSetUpdate_SetOpType_name, int32(x))
}

func (x *ApbSetUpdate_SetOpType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ApbSetUpdate_SetOpType_value, data, "ApbSetUpdate_SetOpType")
	if err != nil {
		return err
	}
	*x = ApbSetUpdate_SetOpType(value)
	return nil
}

func (ApbSetUpdate_SetOpType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{3, 0}
}

// Riak Error response
type ApbErrorResp struct {
	Errmsg               []byte   `protobuf:"bytes,1,req,name=errmsg" json:"errmsg,omitempty"`
	Errcode              *uint32  `protobuf:"varint,2,req,name=errcode" json:"errcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApbErrorResp) Reset()         { *m = ApbErrorResp{} }
func (m *ApbErrorResp) String() string { return proto.CompactTextString(m) }
func (*ApbErrorResp) ProtoMessage()    {}
func (*ApbErrorResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{0}
}

func (m *ApbErrorResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbErrorResp.Unmarshal(m, b)
}
func (m *ApbErrorResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbErrorResp.Marshal(b, m, deterministic)
}
func (m *ApbErrorResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbErrorResp.Merge(m, src)
}
func (m *ApbErrorResp) XXX_Size() int {
	return xxx_messageInfo_ApbErrorResp.Size(m)
}
func (m *ApbErrorResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbErrorResp.DiscardUnknown(m)
}

var xxx_messageInfo_ApbErrorResp proto.InternalMessageInfo

func (m *ApbErrorResp) GetErrmsg() []byte {
	if m != nil {
		return m.Errmsg
	}
	return nil
}

func (m *ApbErrorResp) GetErrcode() uint32 {
	if m != nil && m.Errcode != nil {
		return *m.Errcode
	}
	return 0
}

// Counter increment request
type ApbCounterUpdate struct {
	// inc indicates the value to be incremented. To decrement, use a negative value. If no value is given, it will be considered as an increment by 1
	Inc                  *int64   `protobuf:"zigzag64,1,opt,name=inc" json:"inc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApbCounterUpdate) Reset()         { *m = ApbCounterUpdate{} }
func (m *ApbCounterUpdate) String() string { return proto.CompactTextString(m) }
func (*ApbCounterUpdate) ProtoMessage()    {}
func (*ApbCounterUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{1}
}

func (m *ApbCounterUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbCounterUpdate.Unmarshal(m, b)
}
func (m *ApbCounterUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbCounterUpdate.Marshal(b, m, deterministic)
}
func (m *ApbCounterUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbCounterUpdate.Merge(m, src)
}
func (m *ApbCounterUpdate) XXX_Size() int {
	return xxx_messageInfo_ApbCounterUpdate.Size(m)
}
func (m *ApbCounterUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbCounterUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ApbCounterUpdate proto.InternalMessageInfo

func (m *ApbCounterUpdate) GetInc() int64 {
	if m != nil && m.Inc != nil {
		return *m.Inc
	}
	return 0
}

// Response operation
type ApbGetCounterResp struct {
	Value                *int32   `protobuf:"zigzag32,1,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApbGetCounterResp) Reset()         { *m = ApbGetCounterResp{} }
func (m *ApbGetCounterResp) String() string { return proto.CompactTextString(m) }
func (*ApbGetCounterResp) ProtoMessage()    {}
func (*ApbGetCounterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{2}
}

func (m *ApbGetCounterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbGetCounterResp.Unmarshal(m, b)
}
func (m *ApbGetCounterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbGetCounterResp.Marshal(b, m, deterministic)
}
func (m *ApbGetCounterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbGetCounterResp.Merge(m, src)
}
func (m *ApbGetCounterResp) XXX_Size() int {
	return xxx_messageInfo_ApbGetCounterResp.Size(m)
}
func (m *ApbGetCounterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbGetCounterResp.DiscardUnknown(m)
}

var xxx_messageInfo_ApbGetCounterResp proto.InternalMessageInfo

func (m *ApbGetCounterResp) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

// Set updates request
type ApbSetUpdate struct {
	Optype               *ApbSetUpdate_SetOpType `protobuf:"varint,1,req,name=optype,enum=ApbSetUpdate_SetOpType" json:"optype,omitempty"`
	Adds                 [][]byte                `protobuf:"bytes,2,rep,name=adds" json:"adds,omitempty"`
	Rems                 [][]byte                `protobuf:"bytes,3,rep,name=rems" json:"rems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ApbSetUpdate) Reset()         { *m = ApbSetUpdate{} }
func (m *ApbSetUpdate) String() string { return proto.CompactTextString(m) }
func (*ApbSetUpdate) ProtoMessage()    {}
func (*ApbSetUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{3}
}

func (m *ApbSetUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbSetUpdate.Unmarshal(m, b)
}
func (m *ApbSetUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbSetUpdate.Marshal(b, m, deterministic)
}
func (m *ApbSetUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbSetUpdate.Merge(m, src)
}
func (m *ApbSetUpdate) XXX_Size() int {
	return xxx_messageInfo_ApbSetUpdate.Size(m)
}
func (m *ApbSetUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbSetUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ApbSetUpdate proto.InternalMessageInfo

func (m *ApbSetUpdate) GetOptype() ApbSetUpdate_SetOpType {
	if m != nil && m.Optype != nil {
		return *m.Optype
	}
	return ApbSetUpdate_ADD
}

func (m *ApbSetUpdate) GetAdds() [][]byte {
	if m != nil {
		return m.Adds
	}
	return nil
}

func (m *ApbSetUpdate) GetRems() [][]byte {
	if m != nil {
		return m.Rems
	}
	return nil
}

// Get set request
type ApbGetSetResp struct {
	Value                [][]byte `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApbGetSetResp) Reset()         { *m = ApbGetSetResp{} }
func (m *ApbGetSetResp) String() string { return proto.CompactTextString(m) }
func (*ApbGetSetResp) ProtoMessage()    {}
func (*ApbGetSetResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{4}
}

func (m *ApbGetSetResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbGetSetResp.Unmarshal(m, b)
}
func (m *ApbGetSetResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbGetSetResp.Marshal(b, m, deterministic)
}
func (m *ApbGetSetResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbGetSetResp.Merge(m, src)
}
func (m *ApbGetSetResp) XXX_Size() int {
	return xxx_messageInfo_ApbGetSetResp.Size(m)
}
func (m *ApbGetSetResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbGetSetResp.DiscardUnknown(m)
}

var xxx_messageInfo_ApbGetSetResp proto.InternalMessageInfo

func (m *ApbGetSetResp) GetValue() [][]byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// Register update
type ApbRegUpdate struct {
	Value                []byte   `protobuf:"bytes,1,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApbRegUpdate) Reset()         { *m = ApbRegUpdate{} }
func (m *ApbRegUpdate) String() string { return proto.CompactTextString(m) }
func (*ApbRegUpdate) ProtoMessage()    {}
func (*ApbRegUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{5}
}

func (m *ApbRegUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbRegUpdate.Unmarshal(m, b)
}
func (m *ApbRegUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbRegUpdate.Marshal(b, m, deterministic)
}
func (m *ApbRegUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbRegUpdate.Merge(m, src)
}
func (m *ApbRegUpdate) XXX_Size() int {
	return xxx_messageInfo_ApbRegUpdate.Size(m)
}
func (m *ApbRegUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbRegUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ApbRegUpdate proto.InternalMessageInfo

func (m *ApbRegUpdate) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// Response operation
type ApbGetRegResp struct {
	Value                []byte   `protobuf:"bytes,1,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApbGetRegResp) Reset()         { *m = ApbGetRegResp{} }
func (m *ApbGetRegResp) String() string { return proto.CompactTextString(m) }
func (*ApbGetRegResp) ProtoMessage()    {}
func (*ApbGetRegResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{6}
}

func (m *ApbGetRegResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbGetRegResp.Unmarshal(m, b)
}
func (m *ApbGetRegResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbGetRegResp.Marshal(b, m, deterministic)
}
func (m *ApbGetRegResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbGetRegResp.Merge(m, src)
}
func (m *ApbGetRegResp) XXX_Size() int {
	return xxx_messageInfo_ApbGetRegResp.Size(m)
}
func (m *ApbGetRegResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbGetRegResp.DiscardUnknown(m)
}

var xxx_messageInfo_ApbGetRegResp proto.InternalMessageInfo

func (m *ApbGetRegResp) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// response:
type ApbGetMVRegResp struct {
	Values               [][]byte `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApbGetMVRegResp) Reset()         { *m = ApbGetMVRegResp{} }
func (m *ApbGetMVRegResp) String() string { return proto.CompactTextString(m) }
func (*ApbGetMVRegResp) ProtoMessage()    {}
func (*ApbGetMVRegResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{7}
}

func (m *ApbGetMVRegResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbGetMVRegResp.Unmarshal(m, b)
}
func (m *ApbGetMVRegResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbGetMVRegResp.Marshal(b, m, deterministic)
}
func (m *ApbGetMVRegResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbGetMVRegResp.Merge(m, src)
}
func (m *ApbGetMVRegResp) XXX_Size() int {
	return xxx_messageInfo_ApbGetMVRegResp.Size(m)
}
func (m *ApbGetMVRegResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbGetMVRegResp.DiscardUnknown(m)
}

var xxx_messageInfo_ApbGetMVRegResp proto.InternalMessageInfo

func (m *ApbGetMVRegResp) GetValues() [][]byte {
	if m != nil {
		return m.Values
	}
	return nil
}

type ApbMapKey struct {
	Key                  []byte    `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Type                 *CRDTType `protobuf:"varint,2,req,name=type,enum=CRDTType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ApbMapKey) Reset()         { *m = ApbMapKey{} }
func (m *ApbMapKey) String() string { return proto.CompactTextString(m) }
func (*ApbMapKey) ProtoMessage()    {}
func (*ApbMapKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{8}
}

func (m *ApbMapKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbMapKey.Unmarshal(m, b)
}
func (m *ApbMapKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbMapKey.Marshal(b, m, deterministic)
}
func (m *ApbMapKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbMapKey.Merge(m, src)
}
func (m *ApbMapKey) XXX_Size() int {
	return xxx_messageInfo_ApbMapKey.Size(m)
}
func (m *ApbMapKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbMapKey.DiscardUnknown(m)
}

var xxx_messageInfo_ApbMapKey proto.InternalMessageInfo

func (m *ApbMapKey) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ApbMapKey) GetType() CRDTType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return CRDTType_COUNTER
}

type ApbMapUpdate struct {
	Updates              []*ApbMapNestedUpdate `protobuf:"bytes,1,rep,name=updates" json:"updates,omitempty"`
	RemovedKeys          []*ApbMapKey          `protobuf:"bytes,2,rep,name=removedKeys" json:"removedKeys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ApbMapUpdate) Reset()         { *m = ApbMapUpdate{} }
func (m *ApbMapUpdate) String() string { return proto.CompactTextString(m) }
func (*ApbMapUpdate) ProtoMessage()    {}
func (*ApbMapUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{9}
}

func (m *ApbMapUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbMapUpdate.Unmarshal(m, b)
}
func (m *ApbMapUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbMapUpdate.Marshal(b, m, deterministic)
}
func (m *ApbMapUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbMapUpdate.Merge(m, src)
}
func (m *ApbMapUpdate) XXX_Size() int {
	return xxx_messageInfo_ApbMapUpdate.Size(m)
}
func (m *ApbMapUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbMapUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ApbMapUpdate proto.InternalMessageInfo

func (m *ApbMapUpdate) GetUpdates() []*ApbMapNestedUpdate {
	if m != nil {
		return m.Updates
	}
	return nil
}

func (m *ApbMapUpdate) GetRemovedKeys() []*ApbMapKey {
	if m != nil {
		return m.RemovedKeys
	}
	return nil
}

type ApbMapNestedUpdate struct {
	Key                  *ApbMapKey          `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Update               *ApbUpdateOperation `protobuf:"bytes,2,req,name=update" json:"update,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ApbMapNestedUpdate) Reset()         { *m = ApbMapNestedUpdate{} }
func (m *ApbMapNestedUpdate) String() string { return proto.CompactTextString(m) }
func (*ApbMapNestedUpdate) ProtoMessage()    {}
func (*ApbMapNestedUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{10}
}

func (m *ApbMapNestedUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbMapNestedUpdate.Unmarshal(m, b)
}
func (m *ApbMapNestedUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbMapNestedUpdate.Marshal(b, m, deterministic)
}
func (m *ApbMapNestedUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbMapNestedUpdate.Merge(m, src)
}
func (m *ApbMapNestedUpdate) XXX_Size() int {
	return xxx_messageInfo_ApbMapNestedUpdate.Size(m)
}
func (m *ApbMapNestedUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbMapNestedUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ApbMapNestedUpdate proto.InternalMessageInfo

func (m *ApbMapNestedUpdate) GetKey() *ApbMapKey {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ApbMapNestedUpdate) GetUpdate() *ApbUpdateOperation {
	if m != nil {
		return m.Update
	}
	return nil
}

type ApbGetMapResp struct {
	Entries              []*ApbMapEntry `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ApbGetMapResp) Reset()         { *m = ApbGetMapResp{} }
func (m *ApbGetMapResp) String() string { return proto.CompactTextString(m) }
func (*ApbGetMapResp) ProtoMessage()    {}
func (*ApbGetMapResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{11}
}

func (m *ApbGetMapResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbGetMapResp.Unmarshal(m, b)
}
func (m *ApbGetMapResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbGetMapResp.Marshal(b, m, deterministic)
}
func (m *ApbGetMapResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbGetMapResp.Merge(m, src)
}
func (m *ApbGetMapResp) XXX_Size() int {
	return xxx_messageInfo_ApbGetMapResp.Size(m)
}
func (m *ApbGetMapResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbGetMapResp.DiscardUnknown(m)
}

var xxx_messageInfo_ApbGetMapResp proto.InternalMessageInfo

func (m *ApbGetMapResp) GetEntries() []*ApbMapEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type ApbMapEntry struct {
	Key                  *ApbMapKey         `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value                *ApbReadObjectResp `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ApbMapEntry) Reset()         { *m = ApbMapEntry{} }
func (m *ApbMapEntry) String() string { return proto.CompactTextString(m) }
func (*ApbMapEntry) ProtoMessage()    {}
func (*ApbMapEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{12}
}

func (m *ApbMapEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbMapEntry.Unmarshal(m, b)
}
func (m *ApbMapEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbMapEntry.Marshal(b, m, deterministic)
}
func (m *ApbMapEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbMapEntry.Merge(m, src)
}
func (m *ApbMapEntry) XXX_Size() int {
	return xxx_messageInfo_ApbMapEntry.Size(m)
}
func (m *ApbMapEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbMapEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ApbMapEntry proto.InternalMessageInfo

func (m *ApbMapEntry) GetKey() *ApbMapKey {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ApbMapEntry) GetValue() *ApbReadObjectResp {
	if m != nil {
		return m.Value
	}
	return nil
}

type ApbFlagUpdate struct {
	Value                *bool    `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApbFlagUpdate) Reset()         { *m = ApbFlagUpdate{} }
func (m *ApbFlagUpdate) String() string { return proto.CompactTextString(m) }
func (*ApbFlagUpdate) ProtoMessage()    {}
func (*ApbFlagUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{13}
}

func (m *ApbFlagUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbFlagUpdate.Unmarshal(m, b)
}
func (m *ApbFlagUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbFlagUpdate.Marshal(b, m, deterministic)
}
func (m *ApbFlagUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbFlagUpdate.Merge(m, src)
}
func (m *ApbFlagUpdate) XXX_Size() int {
	return xxx_messageInfo_ApbFlagUpdate.Size(m)
}
func (m *ApbFlagUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbFlagUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ApbFlagUpdate proto.InternalMessageInfo

func (m *ApbFlagUpdate) GetValue() bool {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return false
}

type ApbGetFlagResp struct {
	Value                *bool    `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApbGetFlagResp) Reset()         { *m = ApbGetFlagResp{} }
func (m *ApbGetFlagResp) String() string { return proto.CompactTextString(m) }
func (*ApbGetFlagResp) ProtoMessage()    {}
func (*ApbGetFlagResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{14}
}

func (m *ApbGetFlagResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbGetFlagResp.Unmarshal(m, b)
}
func (m *ApbGetFlagResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbGetFlagResp.Marshal(b, m, deterministic)
}
func (m *ApbGetFlagResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbGetFlagResp.Merge(m, src)
}
func (m *ApbGetFlagResp) XXX_Size() int {
	return xxx_messageInfo_ApbGetFlagResp.Size(m)
}
func (m *ApbGetFlagResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbGetFlagResp.DiscardUnknown(m)
}

var xxx_messageInfo_ApbGetFlagResp proto.InternalMessageInfo

func (m *ApbGetFlagResp) GetValue() bool {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return false
}

// General reset operation
type ApbCrdtReset struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApbCrdtReset) Reset()         { *m = ApbCrdtReset{} }
func (m *ApbCrdtReset) String() string { return proto.CompactTextString(m) }
func (*ApbCrdtReset) ProtoMessage()    {}
func (*ApbCrdtReset) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{15}
}

func (m *ApbCrdtReset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbCrdtReset.Unmarshal(m, b)
}
func (m *ApbCrdtReset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbCrdtReset.Marshal(b, m, deterministic)
}
func (m *ApbCrdtReset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbCrdtReset.Merge(m, src)
}
func (m *ApbCrdtReset) XXX_Size() int {
	return xxx_messageInfo_ApbCrdtReset.Size(m)
}
func (m *ApbCrdtReset) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbCrdtReset.DiscardUnknown(m)
}

var xxx_messageInfo_ApbCrdtReset proto.InternalMessageInfo

// Response operation
type ApbOperationResp struct {
	Success              *bool    `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	Errorcode            *uint32  `protobuf:"varint,2,opt,name=errorcode" json:"errorcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApbOperationResp) Reset()         { *m = ApbOperationResp{} }
func (m *ApbOperationResp) String() string { return proto.CompactTextString(m) }
func (*ApbOperationResp) ProtoMessage()    {}
func (*ApbOperationResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{16}
}

func (m *ApbOperationResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbOperationResp.Unmarshal(m, b)
}
func (m *ApbOperationResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbOperationResp.Marshal(b, m, deterministic)
}
func (m *ApbOperationResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbOperationResp.Merge(m, src)
}
func (m *ApbOperationResp) XXX_Size() int {
	return xxx_messageInfo_ApbOperationResp.Size(m)
}
func (m *ApbOperationResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbOperationResp.DiscardUnknown(m)
}

var xxx_messageInfo_ApbOperationResp proto.InternalMessageInfo

func (m *ApbOperationResp) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *ApbOperationResp) GetErrorcode() uint32 {
	if m != nil && m.Errorcode != nil {
		return *m.Errorcode
	}
	return 0
}

// Topk-rmv updates request
type ApbTopkRmvUpdate struct {
	Adds                 []*ApbIntPair `protobuf:"bytes,1,rep,name=adds" json:"adds,omitempty"`
	Rems                 []int32       `protobuf:"zigzag32,2,rep,name=rems" json:"rems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ApbTopkRmvUpdate) Reset()         { *m = ApbTopkRmvUpdate{} }
func (m *ApbTopkRmvUpdate) String() string { return proto.CompactTextString(m) }
func (*ApbTopkRmvUpdate) ProtoMessage()    {}
func (*ApbTopkRmvUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{17}
}

func (m *ApbTopkRmvUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbTopkRmvUpdate.Unmarshal(m, b)
}
func (m *ApbTopkRmvUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbTopkRmvUpdate.Marshal(b, m, deterministic)
}
func (m *ApbTopkRmvUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbTopkRmvUpdate.Merge(m, src)
}
func (m *ApbTopkRmvUpdate) XXX_Size() int {
	return xxx_messageInfo_ApbTopkRmvUpdate.Size(m)
}
func (m *ApbTopkRmvUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbTopkRmvUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ApbTopkRmvUpdate proto.InternalMessageInfo

func (m *ApbTopkRmvUpdate) GetAdds() []*ApbIntPair {
	if m != nil {
		return m.Adds
	}
	return nil
}

func (m *ApbTopkRmvUpdate) GetRems() []int32 {
	if m != nil {
		return m.Rems
	}
	return nil
}

//Topk updates request
type ApbTopkUpdate struct {
	PlayerId             *int64   `protobuf:"zigzag64,1,req,name=playerId" json:"playerId,omitempty"`
	Score                *int64   `protobuf:"zigzag64,2,req,name=score" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApbTopkUpdate) Reset()         { *m = ApbTopkUpdate{} }
func (m *ApbTopkUpdate) String() string { return proto.CompactTextString(m) }
func (*ApbTopkUpdate) ProtoMessage()    {}
func (*ApbTopkUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{18}
}

func (m *ApbTopkUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbTopkUpdate.Unmarshal(m, b)
}
func (m *ApbTopkUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbTopkUpdate.Marshal(b, m, deterministic)
}
func (m *ApbTopkUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbTopkUpdate.Merge(m, src)
}
func (m *ApbTopkUpdate) XXX_Size() int {
	return xxx_messageInfo_ApbTopkUpdate.Size(m)
}
func (m *ApbTopkUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbTopkUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ApbTopkUpdate proto.InternalMessageInfo

func (m *ApbTopkUpdate) GetPlayerId() int64 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *ApbTopkUpdate) GetScore() int64 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

//
//message ApbGetTopkResp {
//repeated sint32 values = 1;
//}
type ApbGetTopkResp struct {
	Values               []*ApbIntPair `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ApbGetTopkResp) Reset()         { *m = ApbGetTopkResp{} }
func (m *ApbGetTopkResp) String() string { return proto.CompactTextString(m) }
func (*ApbGetTopkResp) ProtoMessage()    {}
func (*ApbGetTopkResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{19}
}

func (m *ApbGetTopkResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbGetTopkResp.Unmarshal(m, b)
}
func (m *ApbGetTopkResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbGetTopkResp.Marshal(b, m, deterministic)
}
func (m *ApbGetTopkResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbGetTopkResp.Merge(m, src)
}
func (m *ApbGetTopkResp) XXX_Size() int {
	return xxx_messageInfo_ApbGetTopkResp.Size(m)
}
func (m *ApbGetTopkResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbGetTopkResp.DiscardUnknown(m)
}

var xxx_messageInfo_ApbGetTopkResp proto.InternalMessageInfo

func (m *ApbGetTopkResp) GetValues() []*ApbIntPair {
	if m != nil {
		return m.Values
	}
	return nil
}

//Holds a (playerId, score) pair
type ApbIntPair struct {
	PlayerId             *int32   `protobuf:"zigzag32,1,req,name=playerId" json:"playerId,omitempty"`
	Score                *int32   `protobuf:"zigzag32,2,req,name=score" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApbIntPair) Reset()         { *m = ApbIntPair{} }
func (m *ApbIntPair) String() string { return proto.CompactTextString(m) }
func (*ApbIntPair) ProtoMessage()    {}
func (*ApbIntPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{20}
}

func (m *ApbIntPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbIntPair.Unmarshal(m, b)
}
func (m *ApbIntPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbIntPair.Marshal(b, m, deterministic)
}
func (m *ApbIntPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbIntPair.Merge(m, src)
}
func (m *ApbIntPair) XXX_Size() int {
	return xxx_messageInfo_ApbIntPair.Size(m)
}
func (m *ApbIntPair) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbIntPair.DiscardUnknown(m)
}

var xxx_messageInfo_ApbIntPair proto.InternalMessageInfo

func (m *ApbIntPair) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *ApbIntPair) GetScore() int32 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

type ApbLeaderboardUpdate struct {
	Adds                 []*ApbIntPair `protobuf:"bytes,1,rep,name=adds" json:"adds,omitempty"`
	Rems                 []int32       `protobuf:"varint,2,rep,name=rems" json:"rems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ApbLeaderboardUpdate) Reset()         { *m = ApbLeaderboardUpdate{} }
func (m *ApbLeaderboardUpdate) String() string { return proto.CompactTextString(m) }
func (*ApbLeaderboardUpdate) ProtoMessage()    {}
func (*ApbLeaderboardUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{21}
}

func (m *ApbLeaderboardUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbLeaderboardUpdate.Unmarshal(m, b)
}
func (m *ApbLeaderboardUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbLeaderboardUpdate.Marshal(b, m, deterministic)
}
func (m *ApbLeaderboardUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbLeaderboardUpdate.Merge(m, src)
}
func (m *ApbLeaderboardUpdate) XXX_Size() int {
	return xxx_messageInfo_ApbLeaderboardUpdate.Size(m)
}
func (m *ApbLeaderboardUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbLeaderboardUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ApbLeaderboardUpdate proto.InternalMessageInfo

func (m *ApbLeaderboardUpdate) GetAdds() []*ApbIntPair {
	if m != nil {
		return m.Adds
	}
	return nil
}

func (m *ApbLeaderboardUpdate) GetRems() []int32 {
	if m != nil {
		return m.Rems
	}
	return nil
}

type ApbGetLeaderboardResp struct {
	Values               []int32  `protobuf:"varint,1,rep,name=values" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApbGetLeaderboardResp) Reset()         { *m = ApbGetLeaderboardResp{} }
func (m *ApbGetLeaderboardResp) String() string { return proto.CompactTextString(m) }
func (*ApbGetLeaderboardResp) ProtoMessage()    {}
func (*ApbGetLeaderboardResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{22}
}

func (m *ApbGetLeaderboardResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbGetLeaderboardResp.Unmarshal(m, b)
}
func (m *ApbGetLeaderboardResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbGetLeaderboardResp.Marshal(b, m, deterministic)
}
func (m *ApbGetLeaderboardResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbGetLeaderboardResp.Merge(m, src)
}
func (m *ApbGetLeaderboardResp) XXX_Size() int {
	return xxx_messageInfo_ApbGetLeaderboardResp.Size(m)
}
func (m *ApbGetLeaderboardResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbGetLeaderboardResp.DiscardUnknown(m)
}

var xxx_messageInfo_ApbGetLeaderboardResp proto.InternalMessageInfo

func (m *ApbGetLeaderboardResp) GetValues() []int32 {
	if m != nil {
		return m.Values
	}
	return nil
}

type ApbAverageUpdate struct {
	Value                *int64   `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
	NValues              *int64   `protobuf:"varint,2,opt,name=nValues" json:"nValues,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApbAverageUpdate) Reset()         { *m = ApbAverageUpdate{} }
func (m *ApbAverageUpdate) String() string { return proto.CompactTextString(m) }
func (*ApbAverageUpdate) ProtoMessage()    {}
func (*ApbAverageUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{23}
}

func (m *ApbAverageUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbAverageUpdate.Unmarshal(m, b)
}
func (m *ApbAverageUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbAverageUpdate.Marshal(b, m, deterministic)
}
func (m *ApbAverageUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbAverageUpdate.Merge(m, src)
}
func (m *ApbAverageUpdate) XXX_Size() int {
	return xxx_messageInfo_ApbAverageUpdate.Size(m)
}
func (m *ApbAverageUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbAverageUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ApbAverageUpdate proto.InternalMessageInfo

func (m *ApbAverageUpdate) GetValue() int64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *ApbAverageUpdate) GetNValues() int64 {
	if m != nil && m.NValues != nil {
		return *m.NValues
	}
	return 0
}

type ApbGetAverageResp struct {
	Avg                  *float64 `protobuf:"fixed64,1,req,name=avg" json:"avg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApbGetAverageResp) Reset()         { *m = ApbGetAverageResp{} }
func (m *ApbGetAverageResp) String() string { return proto.CompactTextString(m) }
func (*ApbGetAverageResp) ProtoMessage()    {}
func (*ApbGetAverageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{24}
}

func (m *ApbGetAverageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbGetAverageResp.Unmarshal(m, b)
}
func (m *ApbGetAverageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbGetAverageResp.Marshal(b, m, deterministic)
}
func (m *ApbGetAverageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbGetAverageResp.Merge(m, src)
}
func (m *ApbGetAverageResp) XXX_Size() int {
	return xxx_messageInfo_ApbGetAverageResp.Size(m)
}
func (m *ApbGetAverageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbGetAverageResp.DiscardUnknown(m)
}

var xxx_messageInfo_ApbGetAverageResp proto.InternalMessageInfo

func (m *ApbGetAverageResp) GetAvg() float64 {
	if m != nil && m.Avg != nil {
		return *m.Avg
	}
	return 0
}

type ApbMaxMinUpdate struct {
	Value                *int64   `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
	IsMax                *bool    `protobuf:"varint,2,req,name=isMax" json:"isMax,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApbMaxMinUpdate) Reset()         { *m = ApbMaxMinUpdate{} }
func (m *ApbMaxMinUpdate) String() string { return proto.CompactTextString(m) }
func (*ApbMaxMinUpdate) ProtoMessage()    {}
func (*ApbMaxMinUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{25}
}

func (m *ApbMaxMinUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbMaxMinUpdate.Unmarshal(m, b)
}
func (m *ApbMaxMinUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbMaxMinUpdate.Marshal(b, m, deterministic)
}
func (m *ApbMaxMinUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbMaxMinUpdate.Merge(m, src)
}
func (m *ApbMaxMinUpdate) XXX_Size() int {
	return xxx_messageInfo_ApbMaxMinUpdate.Size(m)
}
func (m *ApbMaxMinUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbMaxMinUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ApbMaxMinUpdate proto.InternalMessageInfo

func (m *ApbMaxMinUpdate) GetValue() int64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *ApbMaxMinUpdate) GetIsMax() bool {
	if m != nil && m.IsMax != nil {
		return *m.IsMax
	}
	return false
}

type ApbGetMaxMinResp struct {
	Value                *int64   `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApbGetMaxMinResp) Reset()         { *m = ApbGetMaxMinResp{} }
func (m *ApbGetMaxMinResp) String() string { return proto.CompactTextString(m) }
func (*ApbGetMaxMinResp) ProtoMessage()    {}
func (*ApbGetMaxMinResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{26}
}

func (m *ApbGetMaxMinResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbGetMaxMinResp.Unmarshal(m, b)
}
func (m *ApbGetMaxMinResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbGetMaxMinResp.Marshal(b, m, deterministic)
}
func (m *ApbGetMaxMinResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbGetMaxMinResp.Merge(m, src)
}
func (m *ApbGetMaxMinResp) XXX_Size() int {
	return xxx_messageInfo_ApbGetMaxMinResp.Size(m)
}
func (m *ApbGetMaxMinResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbGetMaxMinResp.DiscardUnknown(m)
}

var xxx_messageInfo_ApbGetMaxMinResp proto.InternalMessageInfo

func (m *ApbGetMaxMinResp) GetValue() int64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

// Properties parameters of a transaction
type ApbTxnProperties struct {
	ReadWrite            *uint32  `protobuf:"varint,1,opt,name=read_write,json=readWrite" json:"read_write,omitempty"`
	RedBlue              *uint32  `protobuf:"varint,2,opt,name=red_blue,json=redBlue" json:"red_blue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApbTxnProperties) Reset()         { *m = ApbTxnProperties{} }
func (m *ApbTxnProperties) String() string { return proto.CompactTextString(m) }
func (*ApbTxnProperties) ProtoMessage()    {}
func (*ApbTxnProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{27}
}

func (m *ApbTxnProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbTxnProperties.Unmarshal(m, b)
}
func (m *ApbTxnProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbTxnProperties.Marshal(b, m, deterministic)
}
func (m *ApbTxnProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbTxnProperties.Merge(m, src)
}
func (m *ApbTxnProperties) XXX_Size() int {
	return xxx_messageInfo_ApbTxnProperties.Size(m)
}
func (m *ApbTxnProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbTxnProperties.DiscardUnknown(m)
}

var xxx_messageInfo_ApbTxnProperties proto.InternalMessageInfo

func (m *ApbTxnProperties) GetReadWrite() uint32 {
	if m != nil && m.ReadWrite != nil {
		return *m.ReadWrite
	}
	return 0
}

func (m *ApbTxnProperties) GetRedBlue() uint32 {
	if m != nil && m.RedBlue != nil {
		return *m.RedBlue
	}
	return 0
}

// Object (Key) representation
type ApbBoundObject struct {
	Key                  []byte    `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Type                 *CRDTType `protobuf:"varint,2,req,name=type,enum=CRDTType" json:"type,omitempty"`
	Bucket               []byte    `protobuf:"bytes,3,req,name=bucket" json:"bucket,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ApbBoundObject) Reset()         { *m = ApbBoundObject{} }
func (m *ApbBoundObject) String() string { return proto.CompactTextString(m) }
func (*ApbBoundObject) ProtoMessage()    {}
func (*ApbBoundObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{28}
}

func (m *ApbBoundObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbBoundObject.Unmarshal(m, b)
}
func (m *ApbBoundObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbBoundObject.Marshal(b, m, deterministic)
}
func (m *ApbBoundObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbBoundObject.Merge(m, src)
}
func (m *ApbBoundObject) XXX_Size() int {
	return xxx_messageInfo_ApbBoundObject.Size(m)
}
func (m *ApbBoundObject) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbBoundObject.DiscardUnknown(m)
}

var xxx_messageInfo_ApbBoundObject proto.InternalMessageInfo

func (m *ApbBoundObject) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ApbBoundObject) GetType() CRDTType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return CRDTType_COUNTER
}

func (m *ApbBoundObject) GetBucket() []byte {
	if m != nil {
		return m.Bucket
	}
	return nil
}

// Objects to be read
type ApbReadObjects struct {
	Boundobjects          []*ApbBoundObject `protobuf:"bytes,1,rep,name=boundobjects" json:"boundobjects,omitempty"`
	TransactionDescriptor []byte            `protobuf:"bytes,2,req,name=transaction_descriptor,json=transactionDescriptor" json:"transaction_descriptor,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}          `json:"-"`
	XXX_unrecognized      []byte            `json:"-"`
	XXX_sizecache         int32             `json:"-"`
}

func (m *ApbReadObjects) Reset()         { *m = ApbReadObjects{} }
func (m *ApbReadObjects) String() string { return proto.CompactTextString(m) }
func (*ApbReadObjects) ProtoMessage()    {}
func (*ApbReadObjects) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{29}
}

func (m *ApbReadObjects) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbReadObjects.Unmarshal(m, b)
}
func (m *ApbReadObjects) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbReadObjects.Marshal(b, m, deterministic)
}
func (m *ApbReadObjects) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbReadObjects.Merge(m, src)
}
func (m *ApbReadObjects) XXX_Size() int {
	return xxx_messageInfo_ApbReadObjects.Size(m)
}
func (m *ApbReadObjects) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbReadObjects.DiscardUnknown(m)
}

var xxx_messageInfo_ApbReadObjects proto.InternalMessageInfo

func (m *ApbReadObjects) GetBoundobjects() []*ApbBoundObject {
	if m != nil {
		return m.Boundobjects
	}
	return nil
}

func (m *ApbReadObjects) GetTransactionDescriptor() []byte {
	if m != nil {
		return m.TransactionDescriptor
	}
	return nil
}

// An Object to be updated with specified operation
type ApbUpdateOp struct {
	Boundobject          *ApbBoundObject     `protobuf:"bytes,1,req,name=boundobject" json:"boundobject,omitempty"`
	Operation            *ApbUpdateOperation `protobuf:"bytes,2,req,name=operation" json:"operation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ApbUpdateOp) Reset()         { *m = ApbUpdateOp{} }
func (m *ApbUpdateOp) String() string { return proto.CompactTextString(m) }
func (*ApbUpdateOp) ProtoMessage()    {}
func (*ApbUpdateOp) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{30}
}

func (m *ApbUpdateOp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbUpdateOp.Unmarshal(m, b)
}
func (m *ApbUpdateOp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbUpdateOp.Marshal(b, m, deterministic)
}
func (m *ApbUpdateOp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbUpdateOp.Merge(m, src)
}
func (m *ApbUpdateOp) XXX_Size() int {
	return xxx_messageInfo_ApbUpdateOp.Size(m)
}
func (m *ApbUpdateOp) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbUpdateOp.DiscardUnknown(m)
}

var xxx_messageInfo_ApbUpdateOp proto.InternalMessageInfo

func (m *ApbUpdateOp) GetBoundobject() *ApbBoundObject {
	if m != nil {
		return m.Boundobject
	}
	return nil
}

func (m *ApbUpdateOp) GetOperation() *ApbUpdateOperation {
	if m != nil {
		return m.Operation
	}
	return nil
}

type ApbUpdateOperation struct {
	Counterop            *ApbCounterUpdate     `protobuf:"bytes,1,opt,name=counterop" json:"counterop,omitempty"`
	Setop                *ApbSetUpdate         `protobuf:"bytes,2,opt,name=setop" json:"setop,omitempty"`
	Regop                *ApbRegUpdate         `protobuf:"bytes,3,opt,name=regop" json:"regop,omitempty"`
	Mapop                *ApbMapUpdate         `protobuf:"bytes,5,opt,name=mapop" json:"mapop,omitempty"`
	Resetop              *ApbCrdtReset         `protobuf:"bytes,6,opt,name=resetop" json:"resetop,omitempty"`
	Flagop               *ApbFlagUpdate        `protobuf:"bytes,7,opt,name=flagop" json:"flagop,omitempty"`
	Maxminop             *ApbMaxMinUpdate      `protobuf:"bytes,11,opt,name=maxminop" json:"maxminop,omitempty"`
	Topkrmvop            *ApbTopkRmvUpdate     `protobuf:"bytes,12,opt,name=topkrmvop" json:"topkrmvop,omitempty"`
	Topkop               *ApbTopkUpdate        `protobuf:"bytes,13,opt,name=topkop" json:"topkop,omitempty"`
	Leaderboardop        *ApbLeaderboardUpdate `protobuf:"bytes,14,opt,name=leaderboardop" json:"leaderboardop,omitempty"`
	Avgop                *ApbAverageUpdate     `protobuf:"bytes,15,opt,name=avgop" json:"avgop,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ApbUpdateOperation) Reset()         { *m = ApbUpdateOperation{} }
func (m *ApbUpdateOperation) String() string { return proto.CompactTextString(m) }
func (*ApbUpdateOperation) ProtoMessage()    {}
func (*ApbUpdateOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{31}
}

func (m *ApbUpdateOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbUpdateOperation.Unmarshal(m, b)
}
func (m *ApbUpdateOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbUpdateOperation.Marshal(b, m, deterministic)
}
func (m *ApbUpdateOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbUpdateOperation.Merge(m, src)
}
func (m *ApbUpdateOperation) XXX_Size() int {
	return xxx_messageInfo_ApbUpdateOperation.Size(m)
}
func (m *ApbUpdateOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbUpdateOperation.DiscardUnknown(m)
}

var xxx_messageInfo_ApbUpdateOperation proto.InternalMessageInfo

func (m *ApbUpdateOperation) GetCounterop() *ApbCounterUpdate {
	if m != nil {
		return m.Counterop
	}
	return nil
}

func (m *ApbUpdateOperation) GetSetop() *ApbSetUpdate {
	if m != nil {
		return m.Setop
	}
	return nil
}

func (m *ApbUpdateOperation) GetRegop() *ApbRegUpdate {
	if m != nil {
		return m.Regop
	}
	return nil
}

func (m *ApbUpdateOperation) GetMapop() *ApbMapUpdate {
	if m != nil {
		return m.Mapop
	}
	return nil
}

func (m *ApbUpdateOperation) GetResetop() *ApbCrdtReset {
	if m != nil {
		return m.Resetop
	}
	return nil
}

func (m *ApbUpdateOperation) GetFlagop() *ApbFlagUpdate {
	if m != nil {
		return m.Flagop
	}
	return nil
}

func (m *ApbUpdateOperation) GetMaxminop() *ApbMaxMinUpdate {
	if m != nil {
		return m.Maxminop
	}
	return nil
}

func (m *ApbUpdateOperation) GetTopkrmvop() *ApbTopkRmvUpdate {
	if m != nil {
		return m.Topkrmvop
	}
	return nil
}

func (m *ApbUpdateOperation) GetTopkop() *ApbTopkUpdate {
	if m != nil {
		return m.Topkop
	}
	return nil
}

func (m *ApbUpdateOperation) GetLeaderboardop() *ApbLeaderboardUpdate {
	if m != nil {
		return m.Leaderboardop
	}
	return nil
}

func (m *ApbUpdateOperation) GetAvgop() *ApbAverageUpdate {
	if m != nil {
		return m.Avgop
	}
	return nil
}

// Objects to be updated
type ApbUpdateObjects struct {
	Updates               []*ApbUpdateOp `protobuf:"bytes,1,rep,name=updates" json:"updates,omitempty"`
	TransactionDescriptor []byte         `protobuf:"bytes,2,req,name=transaction_descriptor,json=transactionDescriptor" json:"transaction_descriptor,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}       `json:"-"`
	XXX_unrecognized      []byte         `json:"-"`
	XXX_sizecache         int32          `json:"-"`
}

func (m *ApbUpdateObjects) Reset()         { *m = ApbUpdateObjects{} }
func (m *ApbUpdateObjects) String() string { return proto.CompactTextString(m) }
func (*ApbUpdateObjects) ProtoMessage()    {}
func (*ApbUpdateObjects) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{32}
}

func (m *ApbUpdateObjects) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbUpdateObjects.Unmarshal(m, b)
}
func (m *ApbUpdateObjects) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbUpdateObjects.Marshal(b, m, deterministic)
}
func (m *ApbUpdateObjects) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbUpdateObjects.Merge(m, src)
}
func (m *ApbUpdateObjects) XXX_Size() int {
	return xxx_messageInfo_ApbUpdateObjects.Size(m)
}
func (m *ApbUpdateObjects) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbUpdateObjects.DiscardUnknown(m)
}

var xxx_messageInfo_ApbUpdateObjects proto.InternalMessageInfo

func (m *ApbUpdateObjects) GetUpdates() []*ApbUpdateOp {
	if m != nil {
		return m.Updates
	}
	return nil
}

func (m *ApbUpdateObjects) GetTransactionDescriptor() []byte {
	if m != nil {
		return m.TransactionDescriptor
	}
	return nil
}

// Start Transaction
type ApbStartTransaction struct {
	Timestamp            []byte            `protobuf:"bytes,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Properties           *ApbTxnProperties `protobuf:"bytes,2,opt,name=properties" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ApbStartTransaction) Reset()         { *m = ApbStartTransaction{} }
func (m *ApbStartTransaction) String() string { return proto.CompactTextString(m) }
func (*ApbStartTransaction) ProtoMessage()    {}
func (*ApbStartTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{33}
}

func (m *ApbStartTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbStartTransaction.Unmarshal(m, b)
}
func (m *ApbStartTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbStartTransaction.Marshal(b, m, deterministic)
}
func (m *ApbStartTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbStartTransaction.Merge(m, src)
}
func (m *ApbStartTransaction) XXX_Size() int {
	return xxx_messageInfo_ApbStartTransaction.Size(m)
}
func (m *ApbStartTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbStartTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_ApbStartTransaction proto.InternalMessageInfo

func (m *ApbStartTransaction) GetTimestamp() []byte {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *ApbStartTransaction) GetProperties() *ApbTxnProperties {
	if m != nil {
		return m.Properties
	}
	return nil
}

// Abort Transaction
type ApbAbortTransaction struct {
	TransactionDescriptor []byte   `protobuf:"bytes,1,req,name=transaction_descriptor,json=transactionDescriptor" json:"transaction_descriptor,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *ApbAbortTransaction) Reset()         { *m = ApbAbortTransaction{} }
func (m *ApbAbortTransaction) String() string { return proto.CompactTextString(m) }
func (*ApbAbortTransaction) ProtoMessage()    {}
func (*ApbAbortTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{34}
}

func (m *ApbAbortTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbAbortTransaction.Unmarshal(m, b)
}
func (m *ApbAbortTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbAbortTransaction.Marshal(b, m, deterministic)
}
func (m *ApbAbortTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbAbortTransaction.Merge(m, src)
}
func (m *ApbAbortTransaction) XXX_Size() int {
	return xxx_messageInfo_ApbAbortTransaction.Size(m)
}
func (m *ApbAbortTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbAbortTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_ApbAbortTransaction proto.InternalMessageInfo

func (m *ApbAbortTransaction) GetTransactionDescriptor() []byte {
	if m != nil {
		return m.TransactionDescriptor
	}
	return nil
}

// Commit Transaction
type ApbCommitTransaction struct {
	TransactionDescriptor []byte   `protobuf:"bytes,1,req,name=transaction_descriptor,json=transactionDescriptor" json:"transaction_descriptor,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *ApbCommitTransaction) Reset()         { *m = ApbCommitTransaction{} }
func (m *ApbCommitTransaction) String() string { return proto.CompactTextString(m) }
func (*ApbCommitTransaction) ProtoMessage()    {}
func (*ApbCommitTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{35}
}

func (m *ApbCommitTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbCommitTransaction.Unmarshal(m, b)
}
func (m *ApbCommitTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbCommitTransaction.Marshal(b, m, deterministic)
}
func (m *ApbCommitTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbCommitTransaction.Merge(m, src)
}
func (m *ApbCommitTransaction) XXX_Size() int {
	return xxx_messageInfo_ApbCommitTransaction.Size(m)
}
func (m *ApbCommitTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbCommitTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_ApbCommitTransaction proto.InternalMessageInfo

func (m *ApbCommitTransaction) GetTransactionDescriptor() []byte {
	if m != nil {
		return m.TransactionDescriptor
	}
	return nil
}

type ApbStaticUpdateObjects struct {
	Transaction          *ApbStartTransaction `protobuf:"bytes,1,req,name=transaction" json:"transaction,omitempty"`
	Updates              []*ApbUpdateOp       `protobuf:"bytes,2,rep,name=updates" json:"updates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ApbStaticUpdateObjects) Reset()         { *m = ApbStaticUpdateObjects{} }
func (m *ApbStaticUpdateObjects) String() string { return proto.CompactTextString(m) }
func (*ApbStaticUpdateObjects) ProtoMessage()    {}
func (*ApbStaticUpdateObjects) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{36}
}

func (m *ApbStaticUpdateObjects) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbStaticUpdateObjects.Unmarshal(m, b)
}
func (m *ApbStaticUpdateObjects) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbStaticUpdateObjects.Marshal(b, m, deterministic)
}
func (m *ApbStaticUpdateObjects) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbStaticUpdateObjects.Merge(m, src)
}
func (m *ApbStaticUpdateObjects) XXX_Size() int {
	return xxx_messageInfo_ApbStaticUpdateObjects.Size(m)
}
func (m *ApbStaticUpdateObjects) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbStaticUpdateObjects.DiscardUnknown(m)
}

var xxx_messageInfo_ApbStaticUpdateObjects proto.InternalMessageInfo

func (m *ApbStaticUpdateObjects) GetTransaction() *ApbStartTransaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *ApbStaticUpdateObjects) GetUpdates() []*ApbUpdateOp {
	if m != nil {
		return m.Updates
	}
	return nil
}

type ApbStaticReadObjects struct {
	Transaction          *ApbStartTransaction `protobuf:"bytes,1,req,name=transaction" json:"transaction,omitempty"`
	Objects              []*ApbBoundObject    `protobuf:"bytes,2,rep,name=objects" json:"objects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ApbStaticReadObjects) Reset()         { *m = ApbStaticReadObjects{} }
func (m *ApbStaticReadObjects) String() string { return proto.CompactTextString(m) }
func (*ApbStaticReadObjects) ProtoMessage()    {}
func (*ApbStaticReadObjects) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{37}
}

func (m *ApbStaticReadObjects) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbStaticReadObjects.Unmarshal(m, b)
}
func (m *ApbStaticReadObjects) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbStaticReadObjects.Marshal(b, m, deterministic)
}
func (m *ApbStaticReadObjects) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbStaticReadObjects.Merge(m, src)
}
func (m *ApbStaticReadObjects) XXX_Size() int {
	return xxx_messageInfo_ApbStaticReadObjects.Size(m)
}
func (m *ApbStaticReadObjects) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbStaticReadObjects.DiscardUnknown(m)
}

var xxx_messageInfo_ApbStaticReadObjects proto.InternalMessageInfo

func (m *ApbStaticReadObjects) GetTransaction() *ApbStartTransaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *ApbStaticReadObjects) GetObjects() []*ApbBoundObject {
	if m != nil {
		return m.Objects
	}
	return nil
}

//Start transaction response
type ApbStartTransactionResp struct {
	Success               *bool    `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	TransactionDescriptor []byte   `protobuf:"bytes,2,opt,name=transaction_descriptor,json=transactionDescriptor" json:"transaction_descriptor,omitempty"`
	Errorcode             *uint32  `protobuf:"varint,3,opt,name=errorcode" json:"errorcode,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *ApbStartTransactionResp) Reset()         { *m = ApbStartTransactionResp{} }
func (m *ApbStartTransactionResp) String() string { return proto.CompactTextString(m) }
func (*ApbStartTransactionResp) ProtoMessage()    {}
func (*ApbStartTransactionResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{38}
}

func (m *ApbStartTransactionResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbStartTransactionResp.Unmarshal(m, b)
}
func (m *ApbStartTransactionResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbStartTransactionResp.Marshal(b, m, deterministic)
}
func (m *ApbStartTransactionResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbStartTransactionResp.Merge(m, src)
}
func (m *ApbStartTransactionResp) XXX_Size() int {
	return xxx_messageInfo_ApbStartTransactionResp.Size(m)
}
func (m *ApbStartTransactionResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbStartTransactionResp.DiscardUnknown(m)
}

var xxx_messageInfo_ApbStartTransactionResp proto.InternalMessageInfo

func (m *ApbStartTransactionResp) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *ApbStartTransactionResp) GetTransactionDescriptor() []byte {
	if m != nil {
		return m.TransactionDescriptor
	}
	return nil
}

func (m *ApbStartTransactionResp) GetErrorcode() uint32 {
	if m != nil && m.Errorcode != nil {
		return *m.Errorcode
	}
	return 0
}

//Read Objects Response
type ApbReadObjectResp struct {
	// one of the following:
	Counter              *ApbGetCounterResp     `protobuf:"bytes,1,opt,name=counter" json:"counter,omitempty"`
	Set                  *ApbGetSetResp         `protobuf:"bytes,2,opt,name=set" json:"set,omitempty"`
	Reg                  *ApbGetRegResp         `protobuf:"bytes,3,opt,name=reg" json:"reg,omitempty"`
	Mvreg                *ApbGetMVRegResp       `protobuf:"bytes,4,opt,name=mvreg" json:"mvreg,omitempty"`
	Map                  *ApbGetMapResp         `protobuf:"bytes,6,opt,name=map" json:"map,omitempty"`
	Flag                 *ApbGetFlagResp        `protobuf:"bytes,7,opt,name=flag" json:"flag,omitempty"`
	Maxmin               *ApbGetMaxMinResp      `protobuf:"bytes,12,opt,name=maxmin" json:"maxmin,omitempty"`
	Topk                 *ApbGetTopkResp        `protobuf:"bytes,13,opt,name=topk" json:"topk,omitempty"`
	Leadb                *ApbGetLeaderboardResp `protobuf:"bytes,14,opt,name=leadb" json:"leadb,omitempty"`
	Avg                  *ApbGetAverageResp     `protobuf:"bytes,15,opt,name=avg" json:"avg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ApbReadObjectResp) Reset()         { *m = ApbReadObjectResp{} }
func (m *ApbReadObjectResp) String() string { return proto.CompactTextString(m) }
func (*ApbReadObjectResp) ProtoMessage()    {}
func (*ApbReadObjectResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{39}
}

func (m *ApbReadObjectResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbReadObjectResp.Unmarshal(m, b)
}
func (m *ApbReadObjectResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbReadObjectResp.Marshal(b, m, deterministic)
}
func (m *ApbReadObjectResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbReadObjectResp.Merge(m, src)
}
func (m *ApbReadObjectResp) XXX_Size() int {
	return xxx_messageInfo_ApbReadObjectResp.Size(m)
}
func (m *ApbReadObjectResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbReadObjectResp.DiscardUnknown(m)
}

var xxx_messageInfo_ApbReadObjectResp proto.InternalMessageInfo

func (m *ApbReadObjectResp) GetCounter() *ApbGetCounterResp {
	if m != nil {
		return m.Counter
	}
	return nil
}

func (m *ApbReadObjectResp) GetSet() *ApbGetSetResp {
	if m != nil {
		return m.Set
	}
	return nil
}

func (m *ApbReadObjectResp) GetReg() *ApbGetRegResp {
	if m != nil {
		return m.Reg
	}
	return nil
}

func (m *ApbReadObjectResp) GetMvreg() *ApbGetMVRegResp {
	if m != nil {
		return m.Mvreg
	}
	return nil
}

func (m *ApbReadObjectResp) GetMap() *ApbGetMapResp {
	if m != nil {
		return m.Map
	}
	return nil
}

func (m *ApbReadObjectResp) GetFlag() *ApbGetFlagResp {
	if m != nil {
		return m.Flag
	}
	return nil
}

func (m *ApbReadObjectResp) GetMaxmin() *ApbGetMaxMinResp {
	if m != nil {
		return m.Maxmin
	}
	return nil
}

func (m *ApbReadObjectResp) GetTopk() *ApbGetTopkResp {
	if m != nil {
		return m.Topk
	}
	return nil
}

func (m *ApbReadObjectResp) GetLeadb() *ApbGetLeaderboardResp {
	if m != nil {
		return m.Leadb
	}
	return nil
}

func (m *ApbReadObjectResp) GetAvg() *ApbGetAverageResp {
	if m != nil {
		return m.Avg
	}
	return nil
}

type ApbReadObjectsResp struct {
	Success              *bool                `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	Objects              []*ApbReadObjectResp `protobuf:"bytes,2,rep,name=objects" json:"objects,omitempty"`
	Errorcode            *uint32              `protobuf:"varint,3,opt,name=errorcode" json:"errorcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ApbReadObjectsResp) Reset()         { *m = ApbReadObjectsResp{} }
func (m *ApbReadObjectsResp) String() string { return proto.CompactTextString(m) }
func (*ApbReadObjectsResp) ProtoMessage()    {}
func (*ApbReadObjectsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{40}
}

func (m *ApbReadObjectsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbReadObjectsResp.Unmarshal(m, b)
}
func (m *ApbReadObjectsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbReadObjectsResp.Marshal(b, m, deterministic)
}
func (m *ApbReadObjectsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbReadObjectsResp.Merge(m, src)
}
func (m *ApbReadObjectsResp) XXX_Size() int {
	return xxx_messageInfo_ApbReadObjectsResp.Size(m)
}
func (m *ApbReadObjectsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbReadObjectsResp.DiscardUnknown(m)
}

var xxx_messageInfo_ApbReadObjectsResp proto.InternalMessageInfo

func (m *ApbReadObjectsResp) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *ApbReadObjectsResp) GetObjects() []*ApbReadObjectResp {
	if m != nil {
		return m.Objects
	}
	return nil
}

func (m *ApbReadObjectsResp) GetErrorcode() uint32 {
	if m != nil && m.Errorcode != nil {
		return *m.Errorcode
	}
	return 0
}

// Commit Response
type ApbCommitResp struct {
	Success              *bool    `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	CommitTime           []byte   `protobuf:"bytes,2,opt,name=commit_time,json=commitTime" json:"commit_time,omitempty"`
	Errorcode            *uint32  `protobuf:"varint,3,opt,name=errorcode" json:"errorcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApbCommitResp) Reset()         { *m = ApbCommitResp{} }
func (m *ApbCommitResp) String() string { return proto.CompactTextString(m) }
func (*ApbCommitResp) ProtoMessage()    {}
func (*ApbCommitResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{41}
}

func (m *ApbCommitResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbCommitResp.Unmarshal(m, b)
}
func (m *ApbCommitResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbCommitResp.Marshal(b, m, deterministic)
}
func (m *ApbCommitResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbCommitResp.Merge(m, src)
}
func (m *ApbCommitResp) XXX_Size() int {
	return xxx_messageInfo_ApbCommitResp.Size(m)
}
func (m *ApbCommitResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbCommitResp.DiscardUnknown(m)
}

var xxx_messageInfo_ApbCommitResp proto.InternalMessageInfo

func (m *ApbCommitResp) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *ApbCommitResp) GetCommitTime() []byte {
	if m != nil {
		return m.CommitTime
	}
	return nil
}

func (m *ApbCommitResp) GetErrorcode() uint32 {
	if m != nil && m.Errorcode != nil {
		return *m.Errorcode
	}
	return 0
}

type ApbStaticReadObjectsResp struct {
	Objects              *ApbReadObjectsResp `protobuf:"bytes,1,req,name=objects" json:"objects,omitempty"`
	Committime           *ApbCommitResp      `protobuf:"bytes,2,req,name=committime" json:"committime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ApbStaticReadObjectsResp) Reset()         { *m = ApbStaticReadObjectsResp{} }
func (m *ApbStaticReadObjectsResp) String() string { return proto.CompactTextString(m) }
func (*ApbStaticReadObjectsResp) ProtoMessage()    {}
func (*ApbStaticReadObjectsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{42}
}

func (m *ApbStaticReadObjectsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbStaticReadObjectsResp.Unmarshal(m, b)
}
func (m *ApbStaticReadObjectsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbStaticReadObjectsResp.Marshal(b, m, deterministic)
}
func (m *ApbStaticReadObjectsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbStaticReadObjectsResp.Merge(m, src)
}
func (m *ApbStaticReadObjectsResp) XXX_Size() int {
	return xxx_messageInfo_ApbStaticReadObjectsResp.Size(m)
}
func (m *ApbStaticReadObjectsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbStaticReadObjectsResp.DiscardUnknown(m)
}

var xxx_messageInfo_ApbStaticReadObjectsResp proto.InternalMessageInfo

func (m *ApbStaticReadObjectsResp) GetObjects() *ApbReadObjectsResp {
	if m != nil {
		return m.Objects
	}
	return nil
}

func (m *ApbStaticReadObjectsResp) GetCommittime() *ApbCommitResp {
	if m != nil {
		return m.Committime
	}
	return nil
}

//Replica connection
type ApbConnectReplica struct {
	Id                   *int64   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApbConnectReplica) Reset()         { *m = ApbConnectReplica{} }
func (m *ApbConnectReplica) String() string { return proto.CompactTextString(m) }
func (*ApbConnectReplica) ProtoMessage()    {}
func (*ApbConnectReplica) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{43}
}

func (m *ApbConnectReplica) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbConnectReplica.Unmarshal(m, b)
}
func (m *ApbConnectReplica) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbConnectReplica.Marshal(b, m, deterministic)
}
func (m *ApbConnectReplica) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbConnectReplica.Merge(m, src)
}
func (m *ApbConnectReplica) XXX_Size() int {
	return xxx_messageInfo_ApbConnectReplica.Size(m)
}
func (m *ApbConnectReplica) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbConnectReplica.DiscardUnknown(m)
}

var xxx_messageInfo_ApbConnectReplica proto.InternalMessageInfo

func (m *ApbConnectReplica) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type ApbConnectReplicaResp struct {
	KnownIDs             []int64  `protobuf:"varint,1,rep,name=knownIDs" json:"knownIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApbConnectReplicaResp) Reset()         { *m = ApbConnectReplicaResp{} }
func (m *ApbConnectReplicaResp) String() string { return proto.CompactTextString(m) }
func (*ApbConnectReplicaResp) ProtoMessage()    {}
func (*ApbConnectReplicaResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d48018c08bbbb3, []int{44}
}

func (m *ApbConnectReplicaResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApbConnectReplicaResp.Unmarshal(m, b)
}
func (m *ApbConnectReplicaResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApbConnectReplicaResp.Marshal(b, m, deterministic)
}
func (m *ApbConnectReplicaResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApbConnectReplicaResp.Merge(m, src)
}
func (m *ApbConnectReplicaResp) XXX_Size() int {
	return xxx_messageInfo_ApbConnectReplicaResp.Size(m)
}
func (m *ApbConnectReplicaResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ApbConnectReplicaResp.DiscardUnknown(m)
}

var xxx_messageInfo_ApbConnectReplicaResp proto.InternalMessageInfo

func (m *ApbConnectReplicaResp) GetKnownIDs() []int64 {
	if m != nil {
		return m.KnownIDs
	}
	return nil
}

func init() {
	proto.RegisterEnum("CRDTType", CRDTType_name, CRDTType_value)
	proto.RegisterEnum("ApbSetUpdate_SetOpType", ApbSetUpdate_SetOpType_name, ApbSetUpdate_SetOpType_value)
	proto.RegisterType((*ApbErrorResp)(nil), "ApbErrorResp")
	proto.RegisterType((*ApbCounterUpdate)(nil), "ApbCounterUpdate")
	proto.RegisterType((*ApbGetCounterResp)(nil), "ApbGetCounterResp")
	proto.RegisterType((*ApbSetUpdate)(nil), "ApbSetUpdate")
	proto.RegisterType((*ApbGetSetResp)(nil), "ApbGetSetResp")
	proto.RegisterType((*ApbRegUpdate)(nil), "ApbRegUpdate")
	proto.RegisterType((*ApbGetRegResp)(nil), "ApbGetRegResp")
	proto.RegisterType((*ApbGetMVRegResp)(nil), "ApbGetMVRegResp")
	proto.RegisterType((*ApbMapKey)(nil), "ApbMapKey")
	proto.RegisterType((*ApbMapUpdate)(nil), "ApbMapUpdate")
	proto.RegisterType((*ApbMapNestedUpdate)(nil), "ApbMapNestedUpdate")
	proto.RegisterType((*ApbGetMapResp)(nil), "ApbGetMapResp")
	proto.RegisterType((*ApbMapEntry)(nil), "ApbMapEntry")
	proto.RegisterType((*ApbFlagUpdate)(nil), "ApbFlagUpdate")
	proto.RegisterType((*ApbGetFlagResp)(nil), "ApbGetFlagResp")
	proto.RegisterType((*ApbCrdtReset)(nil), "ApbCrdtReset")
	proto.RegisterType((*ApbOperationResp)(nil), "ApbOperationResp")
	proto.RegisterType((*ApbTopkRmvUpdate)(nil), "ApbTopkRmvUpdate")
	proto.RegisterType((*ApbTopkUpdate)(nil), "ApbTopkUpdate")
	proto.RegisterType((*ApbGetTopkResp)(nil), "ApbGetTopkResp")
	proto.RegisterType((*ApbIntPair)(nil), "ApbIntPair")
	proto.RegisterType((*ApbLeaderboardUpdate)(nil), "ApbLeaderboardUpdate")
	proto.RegisterType((*ApbGetLeaderboardResp)(nil), "ApbGetLeaderboardResp")
	proto.RegisterType((*ApbAverageUpdate)(nil), "ApbAverageUpdate")
	proto.RegisterType((*ApbGetAverageResp)(nil), "ApbGetAverageResp")
	proto.RegisterType((*ApbMaxMinUpdate)(nil), "ApbMaxMinUpdate")
	proto.RegisterType((*ApbGetMaxMinResp)(nil), "ApbGetMaxMinResp")
	proto.RegisterType((*ApbTxnProperties)(nil), "ApbTxnProperties")
	proto.RegisterType((*ApbBoundObject)(nil), "ApbBoundObject")
	proto.RegisterType((*ApbReadObjects)(nil), "ApbReadObjects")
	proto.RegisterType((*ApbUpdateOp)(nil), "ApbUpdateOp")
	proto.RegisterType((*ApbUpdateOperation)(nil), "ApbUpdateOperation")
	proto.RegisterType((*ApbUpdateObjects)(nil), "ApbUpdateObjects")
	proto.RegisterType((*ApbStartTransaction)(nil), "ApbStartTransaction")
	proto.RegisterType((*ApbAbortTransaction)(nil), "ApbAbortTransaction")
	proto.RegisterType((*ApbCommitTransaction)(nil), "ApbCommitTransaction")
	proto.RegisterType((*ApbStaticUpdateObjects)(nil), "ApbStaticUpdateObjects")
	proto.RegisterType((*ApbStaticReadObjects)(nil), "ApbStaticReadObjects")
	proto.RegisterType((*ApbStartTransactionResp)(nil), "ApbStartTransactionResp")
	proto.RegisterType((*ApbReadObjectResp)(nil), "ApbReadObjectResp")
	proto.RegisterType((*ApbReadObjectsResp)(nil), "ApbReadObjectsResp")
	proto.RegisterType((*ApbCommitResp)(nil), "ApbCommitResp")
	proto.RegisterType((*ApbStaticReadObjectsResp)(nil), "ApbStaticReadObjectsResp")
	proto.RegisterType((*ApbConnectReplica)(nil), "ApbConnectReplica")
	proto.RegisterType((*ApbConnectReplicaResp)(nil), "ApbConnectReplicaResp")
}

func init() { proto.RegisterFile("antidote.proto", fileDescriptor_97d48018c08bbbb3) }

var fileDescriptor_97d48018c08bbbb3 = []byte{
	// 1661 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0xfd, 0x52, 0x1b, 0xc9,
	0x11, 0x8f, 0x24, 0xf4, 0xd5, 0xfa, 0x60, 0x19, 0x63, 0xac, 0xb8, 0x9c, 0x98, 0x5a, 0x6c, 0x0c,
	0x09, 0x5e, 0x97, 0x71, 0x39, 0xf9, 0x23, 0xe5, 0x54, 0x16, 0x24, 0x53, 0x04, 0x64, 0x51, 0x83,
	0x0c, 0xa9, 0xfc, 0xa3, 0x5a, 0x69, 0xc7, 0x78, 0x03, 0xbb, 0x33, 0x99, 0x5d, 0x64, 0x74, 0x75,
	0x0f, 0x70, 0xf7, 0x06, 0xf7, 0x52, 0xf7, 0x32, 0xf7, 0x04, 0x57, 0xf3, 0xb1, 0x5f, 0x42, 0x86,
	0x3a, 0xd7, 0xfd, 0x37, 0x33, 0xfd, 0xdb, 0xee, 0x9e, 0x9e, 0xee, 0x5f, 0xb7, 0x04, 0x6d, 0x27,
	0x88, 0x3c, 0x97, 0x46, 0xc4, 0x62, 0x9c, 0x46, 0xd4, 0xfc, 0x17, 0x34, 0x6d, 0x36, 0xee, 0x71,
	0x4e, 0x39, 0x26, 0x21, 0x43, 0x6b, 0x50, 0x21, 0x9c, 0xfb, 0xe1, 0x45, 0xa7, 0xb0, 0x5e, 0xdc,
	0x6a, 0x62, 0xbd, 0x43, 0x1d, 0xa8, 0x12, 0xce, 0x27, 0xd4, 0x25, 0x9d, 0xe2, 0x7a, 0x71, 0xab,
	0x85, 0xe3, 0xad, 0xf9, 0x0c, 0x0c, 0x9b, 0x8d, 0xf7, 0xe9, 0x75, 0x10, 0x11, 0xfe, 0x91, 0xb9,
	0x4e, 0x44, 0x90, 0x01, 0x25, 0x2f, 0x98, 0x74, 0x0a, 0xeb, 0x85, 0x2d, 0x84, 0xc5, 0xd2, 0xdc,
	0x86, 0x15, 0x9b, 0x8d, 0x0f, 0x48, 0xa4, 0x81, 0xd2, 0xd8, 0x2a, 0x94, 0xa7, 0xce, 0xd5, 0x35,
	0x91, 0xb6, 0x56, 0xb0, 0xda, 0x98, 0x3f, 0x16, 0xa4, 0x4f, 0xa7, 0x24, 0xd2, 0xda, 0x5e, 0x41,
	0x85, 0xb2, 0x68, 0xc6, 0x14, 0xae, 0xbd, 0xfb, 0xc8, 0xca, 0x8a, 0xad, 0x53, 0x12, 0x0d, 0xd8,
	0x70, 0xc6, 0x08, 0xd6, 0x30, 0x84, 0x60, 0xc9, 0x71, 0xdd, 0xb0, 0x53, 0x5c, 0x2f, 0x6d, 0x35,
	0xb1, 0x5c, 0x8b, 0x33, 0x4e, 0xfc, 0xb0, 0x53, 0x52, 0x67, 0x62, 0x6d, 0xae, 0x43, 0x3d, 0xf9,
	0x18, 0x55, 0xa1, 0x64, 0x77, 0xbb, 0x46, 0x01, 0x01, 0x54, 0x70, 0xaf, 0x3f, 0x38, 0xeb, 0x19,
	0x45, 0xf3, 0x39, 0xb4, 0x94, 0xdb, 0xa7, 0x24, 0x9a, 0x77, 0x59, 0xe8, 0xd1, 0x2e, 0x3f, 0x93,
	0x1e, 0x63, 0x72, 0xa1, 0x3d, 0xce, 0x5d, 0x2c, 0x41, 0x25, 0xca, 0x30, 0xb9, 0xb8, 0x7d, 0xff,
	0x04, 0xb6, 0x0d, 0xcb, 0x0a, 0xd6, 0x3f, 0x8b, 0x81, 0x6b, 0x50, 0x91, 0xb2, 0x50, 0x9b, 0xd5,
	0x3b, 0xf3, 0x1d, 0xd4, 0x6d, 0x36, 0xee, 0x3b, 0xec, 0x88, 0xcc, 0x44, 0xd0, 0x2f, 0xc9, 0x4c,
	0xeb, 0x12, 0x4b, 0xf4, 0x67, 0x58, 0x92, 0x61, 0x2b, 0xca, 0xb0, 0x81, 0xb5, 0x8f, 0xbb, 0xc3,
	0x91, 0x38, 0xc1, 0xf2, 0xdc, 0xbc, 0x94, 0x6e, 0xf7, 0x1d, 0xa6, 0xdd, 0x7e, 0x09, 0xd5, 0x6b,
	0xb9, 0x52, 0x76, 0x1a, 0xbb, 0x0f, 0x2c, 0x25, 0xff, 0x40, 0xc2, 0x88, 0xb8, 0x0a, 0x85, 0x63,
	0x0c, 0xda, 0x81, 0x06, 0x27, 0x3e, 0x9d, 0x12, 0xf7, 0x88, 0xcc, 0x54, 0xb4, 0x1b, 0xbb, 0x60,
	0x25, 0x1e, 0xe1, 0xac, 0xd8, 0x1c, 0x01, 0xba, 0xad, 0x0c, 0x3d, 0x49, 0x9d, 0xce, 0x7f, 0x2b,
	0x2f, 0xf0, 0x57, 0xa8, 0x28, 0x63, 0xf2, 0x0a, 0xda, 0x1f, 0xf5, 0xe5, 0x80, 0x11, 0xee, 0x44,
	0x1e, 0x0d, 0xb0, 0x86, 0x98, 0x7f, 0x8f, 0xc3, 0xdb, 0x77, 0x98, 0x8c, 0xda, 0x26, 0x54, 0x49,
	0x10, 0x71, 0x2f, 0xb9, 0x4e, 0x53, 0xeb, 0xef, 0x05, 0x11, 0x9f, 0xe1, 0x58, 0x68, 0x7e, 0x84,
	0x46, 0xe6, 0xfc, 0x1e, 0x97, 0xb6, 0xe2, 0x37, 0x53, 0x1e, 0x21, 0x4b, 0x3e, 0xbc, 0xe3, 0x0e,
	0xc6, 0xff, 0x23, 0x13, 0x99, 0x23, 0xf9, 0xe7, 0x7e, 0x7f, 0xe5, 0x2c, 0xcc, 0x8a, 0x5a, 0x0c,
	0xdb, 0x84, 0xb6, 0x72, 0x5b, 0x20, 0x6f, 0xa7, 0x45, 0x82, 0x6b, 0xcb, 0xc7, 0xda, 0xe7, 0xae,
	0x30, 0x42, 0x22, 0xf3, 0xdf, 0xb2, 0xee, 0xd2, 0x30, 0x88, 0x2f, 0x3b, 0x50, 0x0d, 0xaf, 0x27,
	0x13, 0x12, 0x86, 0xfa, 0xdb, 0x78, 0x8b, 0x9e, 0x40, 0x9d, 0x88, 0x22, 0xd7, 0x15, 0x5c, 0xd8,
	0x6a, 0xe1, 0xf4, 0xc0, 0x3c, 0x90, 0xba, 0x86, 0x94, 0x5d, 0x62, 0x7f, 0xaa, 0xbd, 0x7d, 0xaa,
	0x8b, 0x48, 0x85, 0xae, 0x21, 0xee, 0x79, 0x18, 0x44, 0x27, 0x8e, 0xc7, 0xe7, 0x2a, 0x4a, 0xbc,
	0xfb, 0x8a, 0xae, 0x28, 0x5b, 0xde, 0x59, 0x28, 0xd2, 0x5a, 0x1e, 0x43, 0x8d, 0x5d, 0x39, 0x33,
	0xc2, 0x0f, 0x5d, 0xe9, 0x12, 0xc2, 0xc9, 0x5e, 0xdc, 0x33, 0x9c, 0x50, 0xae, 0x42, 0x89, 0xb0,
	0xda, 0x98, 0x6f, 0xe3, 0x78, 0x48, 0x77, 0xc4, 0xad, 0x36, 0x72, 0xd9, 0x3f, 0xe7, 0x4b, 0x5c,
	0x0a, 0xff, 0x04, 0x48, 0x4f, 0x6f, 0x99, 0x5d, 0xf9, 0x9a, 0xd9, 0x95, 0xd8, 0xec, 0x11, 0xac,
	0xda, 0x6c, 0x7c, 0x4c, 0x1c, 0x97, 0xf0, 0x31, 0x75, 0xb8, 0xfb, 0x2d, 0x61, 0x28, 0xeb, 0x30,
	0xbc, 0x82, 0x87, 0xea, 0x0e, 0x19, 0x7d, 0x0b, 0x0a, 0xb9, 0x9c, 0x78, 0xbf, 0x27, 0x1f, 0xc0,
	0x9e, 0x12, 0xee, 0x5c, 0x90, 0x45, 0xe9, 0x52, 0xd2, 0x69, 0x20, 0x9e, 0x38, 0x38, 0x53, 0x2a,
	0xc4, 0x33, 0x96, 0x70, 0xbc, 0x35, 0x9f, 0xc7, 0x14, 0xab, 0xd5, 0x48, 0x83, 0x06, 0x94, 0x9c,
	0xa9, 0x22, 0xf3, 0x02, 0x16, 0x4b, 0xf3, 0x9d, 0xa4, 0x97, 0xbe, 0x73, 0xd3, 0xf7, 0x82, 0x3b,
	0x2d, 0xad, 0x42, 0xd9, 0x0b, 0xfb, 0xce, 0x8d, 0x8c, 0x53, 0x0d, 0xab, 0x8d, 0xb9, 0x25, 0x3d,
	0x95, 0x55, 0x26, 0x34, 0xdc, 0x4e, 0xd8, 0xf8, 0x7b, 0xf3, 0x58, 0x25, 0xd5, 0x4d, 0x70, 0xc2,
	0x29, 0x23, 0x3c, 0xf2, 0x48, 0x88, 0xfe, 0x04, 0xc0, 0x89, 0xe3, 0x8e, 0xbe, 0x70, 0x2f, 0x22,
	0xb2, 0x3f, 0xb4, 0x70, 0x5d, 0x9c, 0x9c, 0x8b, 0x03, 0xf4, 0x47, 0xa8, 0x71, 0xe2, 0x8e, 0xc6,
	0xaa, 0xbe, 0x84, 0xb0, 0xca, 0x89, 0xbb, 0x27, 0xb4, 0xfd, 0x57, 0xa6, 0xc5, 0x1e, 0xbd, 0x0e,
	0x74, 0xa9, 0xfd, 0x76, 0xbe, 0x13, 0xd1, 0x1f, 0x5f, 0x4f, 0x2e, 0x49, 0xd4, 0x29, 0xa9, 0xe6,
	0xa6, 0x76, 0xe6, 0xf7, 0x52, 0x77, 0x5a, 0xc5, 0x21, 0x7a, 0x03, 0xcd, 0xb1, 0x30, 0x45, 0xd5,
	0x5e, 0xbf, 0xfe, 0xb2, 0x95, 0x77, 0x01, 0xe7, 0x40, 0xe8, 0x2d, 0xac, 0x45, 0xdc, 0x09, 0x42,
	0x67, 0x22, 0x0a, 0x72, 0xe4, 0x92, 0x70, 0xc2, 0x3d, 0x16, 0x51, 0x2e, 0x1d, 0x6a, 0xe2, 0x87,
	0x19, 0x69, 0x37, 0x11, 0x9a, 0xa1, 0xa4, 0x9f, 0x98, 0xd5, 0xd0, 0x6b, 0x68, 0x64, 0xb4, 0x6a,
	0x1a, 0xba, 0x65, 0x39, 0x8b, 0x41, 0xaf, 0xa1, 0x4e, 0x63, 0x1e, 0xb8, 0x8b, 0x29, 0x53, 0x94,
	0xf9, 0x4b, 0x49, 0xd2, 0xf1, 0x1c, 0x02, 0xbd, 0x82, 0xfa, 0x44, 0x35, 0x68, 0xca, 0xe4, 0xf3,
	0x34, 0x76, 0x57, 0xac, 0xf9, 0xf6, 0x8e, 0x53, 0x0c, 0xda, 0x80, 0x72, 0x48, 0x22, 0xca, 0xe4,
	0x73, 0x35, 0x76, 0x5b, 0xb9, 0xd6, 0x8c, 0x95, 0x4c, 0x80, 0x38, 0xb9, 0xa0, 0xac, 0x53, 0x4a,
	0x41, 0x49, 0xb3, 0xc4, 0x4a, 0x26, 0x40, 0xbe, 0xc3, 0x28, 0xeb, 0x94, 0x53, 0x50, 0xd2, 0x9a,
	0xb0, 0x92, 0xa1, 0x17, 0x50, 0xe5, 0x44, 0x19, 0xac, 0xa4, 0xb0, 0x84, 0x14, 0x71, 0x2c, 0x45,
	0x9b, 0x50, 0xf9, 0x74, 0xe5, 0x08, 0x9b, 0x55, 0x89, 0x6b, 0x5b, 0x39, 0x2e, 0xc6, 0x5a, 0x8a,
	0x76, 0xa0, 0xe6, 0x3b, 0x37, 0xbe, 0x17, 0x50, 0xd6, 0x69, 0x48, 0xa4, 0x61, 0xcd, 0x95, 0x07,
	0x4e, 0x10, 0x22, 0x3c, 0x11, 0x65, 0x97, 0xdc, 0x9f, 0x52, 0xd6, 0x69, 0xa6, 0xe1, 0xc9, 0x31,
	0x27, 0x4e, 0x31, 0xc2, 0x0d, 0xb1, 0xa1, 0xac, 0xd3, 0x4a, 0xdd, 0x48, 0xe9, 0x11, 0x6b, 0x29,
	0xfa, 0x07, 0xb4, 0xae, 0x52, 0xaa, 0xa0, 0xac, 0xd3, 0x96, 0xf0, 0x87, 0xd6, 0x22, 0x4e, 0xc2,
	0x79, 0x2c, 0x7a, 0x01, 0x65, 0x67, 0x2a, 0xae, 0xba, 0x9c, 0x7a, 0x94, 0xa3, 0x12, 0xac, 0xe4,
	0xe6, 0xff, 0x65, 0x45, 0xea, 0x37, 0xd7, 0x49, 0xbb, 0x39, 0xdf, 0xf3, 0x9b, 0xd9, 0xcc, 0x49,
	0x9b, 0xfd, 0x37, 0x26, 0xf7, 0x27, 0x78, 0x20, 0x32, 0x22, 0x72, 0x78, 0x34, 0x4c, 0x01, 0xa2,
	0x1d, 0x45, 0x9e, 0x4f, 0xc2, 0xc8, 0xf1, 0x55, 0x9e, 0x35, 0x71, 0x7a, 0x80, 0x5e, 0x03, 0xb0,
	0x84, 0x33, 0x74, 0x66, 0xa9, 0x38, 0x67, 0xc9, 0x04, 0x67, 0x40, 0xe6, 0xb1, 0xb4, 0x63, 0x8f,
	0x69, 0xde, 0xce, 0xd7, 0xbd, 0x2e, 0xdc, 0xe5, 0x75, 0x5f, 0x36, 0x83, 0x7d, 0xea, 0xfb, 0xde,
	0xef, 0xa1, 0xee, 0x06, 0xd6, 0x54, 0x10, 0x22, 0x6f, 0x92, 0x8f, 0xfe, 0xdf, 0xa0, 0x91, 0xf9,
	0x44, 0x17, 0xfb, 0xaa, 0xb5, 0x20, 0x64, 0x38, 0x0b, 0xcc, 0xbe, 0x5a, 0xf1, 0x8e, 0x57, 0x33,
	0x67, 0xf2, 0x22, 0xca, 0x72, 0x96, 0xdf, 0xbe, 0xd5, 0xee, 0x36, 0x54, 0x63, 0x4a, 0x2c, 0x2e,
	0xa6, 0xc4, 0x58, 0x6e, 0xfe, 0x50, 0x80, 0x47, 0x8b, 0xf4, 0xdd, 0x3d, 0xa7, 0xdc, 0x95, 0x66,
	0x85, 0xaf, 0x46, 0x38, 0x3f, 0xde, 0x94, 0xe6, 0xc7, 0x9b, 0x9f, 0x4a, 0xb2, 0x35, 0xe6, 0xc7,
	0x34, 0xb4, 0x03, 0x55, 0xcd, 0x63, 0x9a, 0xe9, 0xe4, 0x2c, 0x97, 0xff, 0x89, 0x82, 0x63, 0x08,
	0x5a, 0x87, 0x52, 0x48, 0x22, 0x9d, 0x8c, 0x6d, 0x2b, 0xf7, 0xab, 0x00, 0x0b, 0x91, 0x40, 0x70,
	0x72, 0xa1, 0x39, 0x2e, 0x46, 0xe8, 0x09, 0x1e, 0x0b, 0x11, 0xda, 0x84, 0xb2, 0x3f, 0x15, 0x98,
	0xa5, 0x94, 0x69, 0xb2, 0x73, 0x3e, 0x56, 0x62, 0xa1, 0xc9, 0x77, 0x62, 0x86, 0x8b, 0x35, 0xe9,
	0xa9, 0x16, 0x0b, 0x11, 0xda, 0x80, 0x25, 0x41, 0x60, 0x9a, 0xdc, 0x96, 0xad, 0xfc, 0x04, 0x89,
	0xa5, 0x10, 0x6d, 0x43, 0x45, 0x31, 0x57, 0x96, 0xaa, 0x72, 0x9d, 0x1b, 0x6b, 0x80, 0xd0, 0x27,
	0x98, 0x48, 0xb3, 0x54, 0xac, 0x2f, 0x9e, 0xc0, 0xb0, 0x14, 0xa2, 0x1d, 0x28, 0x0b, 0xe2, 0x19,
	0x6b, 0x72, 0x5a, 0xb3, 0x16, 0xce, 0x38, 0x58, 0x81, 0xd0, 0x33, 0x35, 0x79, 0x2c, 0xe7, 0x42,
	0x9b, 0x19, 0x4d, 0xd4, 0x34, 0xf2, 0x9d, 0x6c, 0x43, 0x99, 0xd4, 0xbc, 0x27, 0x3f, 0x76, 0xe6,
	0x13, 0x70, 0xd1, 0x00, 0x1e, 0x43, 0xee, 0x49, 0x8b, 0xcf, 0x72, 0x58, 0x55, 0x55, 0x7e, 0x8f,
	0xd9, 0xa7, 0xd0, 0x98, 0x48, 0xdc, 0x48, 0xb0, 0x94, 0xce, 0x45, 0x50, 0x47, 0x43, 0xcf, 0x27,
	0xf7, 0x58, 0x9a, 0x41, 0x67, 0x51, 0x19, 0x4a, 0xa3, 0x2f, 0xd3, 0x1b, 0x15, 0xd2, 0xd6, 0x3d,
	0x87, 0x4a, 0xaf, 0x64, 0x81, 0x36, 0xab, 0x1d, 0x29, 0xc6, 0x29, 0x92, 0xde, 0x03, 0x67, 0x10,
	0xe6, 0x86, 0x4c, 0xfd, 0x7d, 0x1a, 0x04, 0x32, 0x3a, 0xec, 0xca, 0x9b, 0x38, 0xa8, 0x0d, 0x45,
	0xcf, 0xd5, 0xd3, 0x5a, 0xd1, 0x73, 0xcd, 0x37, 0x72, 0x5e, 0xcd, 0x83, 0xa4, 0x73, 0x8f, 0xa1,
	0x76, 0x19, 0xd0, 0x2f, 0xc1, 0x61, 0x57, 0xb5, 0x87, 0x12, 0x4e, 0xf6, 0x7f, 0xf9, 0xb9, 0x00,
	0xf5, 0x64, 0xc2, 0x42, 0x0d, 0xa8, 0xee, 0x0f, 0x3e, 0x7e, 0x18, 0xf6, 0xb0, 0x51, 0x42, 0x75,
	0x28, 0x0f, 0xf0, 0x69, 0x6f, 0x68, 0x2c, 0x89, 0x5f, 0xd3, 0xc7, 0xe7, 0xe7, 0xb8, 0x77, 0x60,
	0x94, 0xc5, 0x71, 0xff, 0x4c, 0x2c, 0x2b, 0xa8, 0x06, 0x4b, 0x07, 0x7d, 0xfb, 0xc4, 0xa8, 0x89,
	0x43, 0x7c, 0x2e, 0xb0, 0x20, 0x97, 0x58, 0x9c, 0x36, 0x50, 0x1b, 0xe0, 0xbd, 0x3d, 0x8c, 0x35,
	0x36, 0x85, 0xfa, 0xf7, 0xc7, 0xf6, 0xc1, 0xa8, 0x77, 0x6e, 0xb4, 0x92, 0x4d, 0xf7, 0xdc, 0x68,
	0x0b, 0x4d, 0xc3, 0xc1, 0xc9, 0x91, 0x51, 0x40, 0x4d, 0xa8, 0x89, 0xd5, 0x08, 0xf7, 0xcf, 0x8c,
	0xa2, 0xfc, 0x3d, 0x7f, 0x76, 0x60, 0x54, 0xd1, 0x32, 0x34, 0x8e, 0x7b, 0x76, 0xb7, 0x87, 0xf7,
	0x06, 0x36, 0xee, 0x1a, 0x75, 0xe1, 0x52, 0xdf, 0xfe, 0x4f, 0xff, 0xf0, 0x83, 0xf1, 0x07, 0xe5,
	0xa9, 0x30, 0xb9, 0xbc, 0xf7, 0x1c, 0x1e, 0x4d, 0xa8, 0x6f, 0x8d, 0x9d, 0xf0, 0x33, 0xb5, 0xb8,
	0xe7, 0x5c, 0xaa, 0xbf, 0x48, 0xc6, 0xd7, 0x9f, 0xf6, 0xc0, 0xd6, 0xff, 0x9a, 0x9c, 0xec, 0xfd,
	0x1a, 0x00, 0x00, 0xff, 0xff, 0xe0, 0xba, 0xc6, 0x21, 0x42, 0x11, 0x00, 0x00,
}
