// Code generated by protoc-gen-go. DO NOT EDIT.
// source: replicator.proto

package antidote

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProtoStableClock struct {
	SenderID             *int64   `protobuf:"varint,1,req,name=senderID" json:"senderID,omitempty"`
	ReplicaTs            *int64   `protobuf:"varint,2,req,name=replicaTs" json:"replicaTs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoStableClock) Reset()         { *m = ProtoStableClock{} }
func (m *ProtoStableClock) String() string { return proto.CompactTextString(m) }
func (*ProtoStableClock) ProtoMessage()    {}
func (*ProtoStableClock) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{0}
}

func (m *ProtoStableClock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoStableClock.Unmarshal(m, b)
}
func (m *ProtoStableClock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoStableClock.Marshal(b, m, deterministic)
}
func (m *ProtoStableClock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoStableClock.Merge(m, src)
}
func (m *ProtoStableClock) XXX_Size() int {
	return xxx_messageInfo_ProtoStableClock.Size(m)
}
func (m *ProtoStableClock) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoStableClock.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoStableClock proto.InternalMessageInfo

func (m *ProtoStableClock) GetSenderID() int64 {
	if m != nil && m.SenderID != nil {
		return *m.SenderID
	}
	return 0
}

func (m *ProtoStableClock) GetReplicaTs() int64 {
	if m != nil && m.ReplicaTs != nil {
		return *m.ReplicaTs
	}
	return 0
}

type ProtoReplicatePart struct {
	SenderID             *int64          `protobuf:"varint,1,req,name=senderID" json:"senderID,omitempty"`
	Txn                  *ProtoRemoteTxn `protobuf:"bytes,2,req,name=txn" json:"txn,omitempty"`
	PartitionID          *int64          `protobuf:"varint,3,req,name=partitionID" json:"partitionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ProtoReplicatePart) Reset()         { *m = ProtoReplicatePart{} }
func (m *ProtoReplicatePart) String() string { return proto.CompactTextString(m) }
func (*ProtoReplicatePart) ProtoMessage()    {}
func (*ProtoReplicatePart) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{1}
}

func (m *ProtoReplicatePart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoReplicatePart.Unmarshal(m, b)
}
func (m *ProtoReplicatePart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoReplicatePart.Marshal(b, m, deterministic)
}
func (m *ProtoReplicatePart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoReplicatePart.Merge(m, src)
}
func (m *ProtoReplicatePart) XXX_Size() int {
	return xxx_messageInfo_ProtoReplicatePart.Size(m)
}
func (m *ProtoReplicatePart) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoReplicatePart.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoReplicatePart proto.InternalMessageInfo

func (m *ProtoReplicatePart) GetSenderID() int64 {
	if m != nil && m.SenderID != nil {
		return *m.SenderID
	}
	return 0
}

func (m *ProtoReplicatePart) GetTxn() *ProtoRemoteTxn {
	if m != nil {
		return m.Txn
	}
	return nil
}

func (m *ProtoReplicatePart) GetPartitionID() int64 {
	if m != nil && m.PartitionID != nil {
		return *m.PartitionID
	}
	return 0
}

type ProtoRemoteTxn struct {
	Timestamp            []byte                `protobuf:"bytes,1,req,name=timestamp" json:"timestamp,omitempty"`
	Upds                 []*ProtoDownstreamUpd `protobuf:"bytes,2,rep,name=upds" json:"upds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ProtoRemoteTxn) Reset()         { *m = ProtoRemoteTxn{} }
func (m *ProtoRemoteTxn) String() string { return proto.CompactTextString(m) }
func (*ProtoRemoteTxn) ProtoMessage()    {}
func (*ProtoRemoteTxn) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{2}
}

func (m *ProtoRemoteTxn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoRemoteTxn.Unmarshal(m, b)
}
func (m *ProtoRemoteTxn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoRemoteTxn.Marshal(b, m, deterministic)
}
func (m *ProtoRemoteTxn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoRemoteTxn.Merge(m, src)
}
func (m *ProtoRemoteTxn) XXX_Size() int {
	return xxx_messageInfo_ProtoRemoteTxn.Size(m)
}
func (m *ProtoRemoteTxn) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoRemoteTxn.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoRemoteTxn proto.InternalMessageInfo

func (m *ProtoRemoteTxn) GetTimestamp() []byte {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *ProtoRemoteTxn) GetUpds() []*ProtoDownstreamUpd {
	if m != nil {
		return m.Upds
	}
	return nil
}

type ProtoDownstreamUpd struct {
	KeyParams            *ApbBoundObject         `protobuf:"bytes,1,req,name=keyParams" json:"keyParams,omitempty"`
	CounterOp            *ProtoCounterDownstream `protobuf:"bytes,2,opt,name=counterOp" json:"counterOp,omitempty"`
	SetOp                *ProtoSetDownstream     `protobuf:"bytes,3,opt,name=setOp" json:"setOp,omitempty"`
	TopkrmvOp            *ProtoTopKRmvDownstream `protobuf:"bytes,4,opt,name=topkrmvOp" json:"topkrmvOp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ProtoDownstreamUpd) Reset()         { *m = ProtoDownstreamUpd{} }
func (m *ProtoDownstreamUpd) String() string { return proto.CompactTextString(m) }
func (*ProtoDownstreamUpd) ProtoMessage()    {}
func (*ProtoDownstreamUpd) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{3}
}

func (m *ProtoDownstreamUpd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoDownstreamUpd.Unmarshal(m, b)
}
func (m *ProtoDownstreamUpd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoDownstreamUpd.Marshal(b, m, deterministic)
}
func (m *ProtoDownstreamUpd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoDownstreamUpd.Merge(m, src)
}
func (m *ProtoDownstreamUpd) XXX_Size() int {
	return xxx_messageInfo_ProtoDownstreamUpd.Size(m)
}
func (m *ProtoDownstreamUpd) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoDownstreamUpd.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoDownstreamUpd proto.InternalMessageInfo

func (m *ProtoDownstreamUpd) GetKeyParams() *ApbBoundObject {
	if m != nil {
		return m.KeyParams
	}
	return nil
}

func (m *ProtoDownstreamUpd) GetCounterOp() *ProtoCounterDownstream {
	if m != nil {
		return m.CounterOp
	}
	return nil
}

func (m *ProtoDownstreamUpd) GetSetOp() *ProtoSetDownstream {
	if m != nil {
		return m.SetOp
	}
	return nil
}

func (m *ProtoDownstreamUpd) GetTopkrmvOp() *ProtoTopKRmvDownstream {
	if m != nil {
		return m.TopkrmvOp
	}
	return nil
}

type ProtoCounterDownstream struct {
	IsInc                *bool    `protobuf:"varint,1,req,name=isInc" json:"isInc,omitempty"`
	Change               *int32   `protobuf:"varint,2,req,name=change" json:"change,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoCounterDownstream) Reset()         { *m = ProtoCounterDownstream{} }
func (m *ProtoCounterDownstream) String() string { return proto.CompactTextString(m) }
func (*ProtoCounterDownstream) ProtoMessage()    {}
func (*ProtoCounterDownstream) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{4}
}

func (m *ProtoCounterDownstream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoCounterDownstream.Unmarshal(m, b)
}
func (m *ProtoCounterDownstream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoCounterDownstream.Marshal(b, m, deterministic)
}
func (m *ProtoCounterDownstream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoCounterDownstream.Merge(m, src)
}
func (m *ProtoCounterDownstream) XXX_Size() int {
	return xxx_messageInfo_ProtoCounterDownstream.Size(m)
}
func (m *ProtoCounterDownstream) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoCounterDownstream.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoCounterDownstream proto.InternalMessageInfo

func (m *ProtoCounterDownstream) GetIsInc() bool {
	if m != nil && m.IsInc != nil {
		return *m.IsInc
	}
	return false
}

func (m *ProtoCounterDownstream) GetChange() int32 {
	if m != nil && m.Change != nil {
		return *m.Change
	}
	return 0
}

type ProtoSetDownstream struct {
	Adds                 []*ProtoValueUnique  `protobuf:"bytes,1,rep,name=adds" json:"adds,omitempty"`
	Rems                 []*ProtoValueUniques `protobuf:"bytes,2,rep,name=rems" json:"rems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ProtoSetDownstream) Reset()         { *m = ProtoSetDownstream{} }
func (m *ProtoSetDownstream) String() string { return proto.CompactTextString(m) }
func (*ProtoSetDownstream) ProtoMessage()    {}
func (*ProtoSetDownstream) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{5}
}

func (m *ProtoSetDownstream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoSetDownstream.Unmarshal(m, b)
}
func (m *ProtoSetDownstream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoSetDownstream.Marshal(b, m, deterministic)
}
func (m *ProtoSetDownstream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoSetDownstream.Merge(m, src)
}
func (m *ProtoSetDownstream) XXX_Size() int {
	return xxx_messageInfo_ProtoSetDownstream.Size(m)
}
func (m *ProtoSetDownstream) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoSetDownstream.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoSetDownstream proto.InternalMessageInfo

func (m *ProtoSetDownstream) GetAdds() []*ProtoValueUnique {
	if m != nil {
		return m.Adds
	}
	return nil
}

func (m *ProtoSetDownstream) GetRems() []*ProtoValueUniques {
	if m != nil {
		return m.Rems
	}
	return nil
}

type ProtoTopKRmvDownstream struct {
	Adds                 []*ProtoTopKElement `protobuf:"bytes,1,rep,name=adds" json:"adds,omitempty"`
	Rems                 []*ProtoTopKIdVc    `protobuf:"bytes,2,rep,name=rems" json:"rems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ProtoTopKRmvDownstream) Reset()         { *m = ProtoTopKRmvDownstream{} }
func (m *ProtoTopKRmvDownstream) String() string { return proto.CompactTextString(m) }
func (*ProtoTopKRmvDownstream) ProtoMessage()    {}
func (*ProtoTopKRmvDownstream) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{6}
}

func (m *ProtoTopKRmvDownstream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoTopKRmvDownstream.Unmarshal(m, b)
}
func (m *ProtoTopKRmvDownstream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoTopKRmvDownstream.Marshal(b, m, deterministic)
}
func (m *ProtoTopKRmvDownstream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoTopKRmvDownstream.Merge(m, src)
}
func (m *ProtoTopKRmvDownstream) XXX_Size() int {
	return xxx_messageInfo_ProtoTopKRmvDownstream.Size(m)
}
func (m *ProtoTopKRmvDownstream) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoTopKRmvDownstream.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoTopKRmvDownstream proto.InternalMessageInfo

func (m *ProtoTopKRmvDownstream) GetAdds() []*ProtoTopKElement {
	if m != nil {
		return m.Adds
	}
	return nil
}

func (m *ProtoTopKRmvDownstream) GetRems() []*ProtoTopKIdVc {
	if m != nil {
		return m.Rems
	}
	return nil
}

type ProtoValueUnique struct {
	Value                []byte   `protobuf:"bytes,1,req,name=value" json:"value,omitempty"`
	Unique               *uint64  `protobuf:"varint,2,req,name=unique" json:"unique,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoValueUnique) Reset()         { *m = ProtoValueUnique{} }
func (m *ProtoValueUnique) String() string { return proto.CompactTextString(m) }
func (*ProtoValueUnique) ProtoMessage()    {}
func (*ProtoValueUnique) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{7}
}

func (m *ProtoValueUnique) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoValueUnique.Unmarshal(m, b)
}
func (m *ProtoValueUnique) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoValueUnique.Marshal(b, m, deterministic)
}
func (m *ProtoValueUnique) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoValueUnique.Merge(m, src)
}
func (m *ProtoValueUnique) XXX_Size() int {
	return xxx_messageInfo_ProtoValueUnique.Size(m)
}
func (m *ProtoValueUnique) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoValueUnique.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoValueUnique proto.InternalMessageInfo

func (m *ProtoValueUnique) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ProtoValueUnique) GetUnique() uint64 {
	if m != nil && m.Unique != nil {
		return *m.Unique
	}
	return 0
}

type ProtoValueUniques struct {
	Value                []byte   `protobuf:"bytes,1,req,name=value" json:"value,omitempty"`
	Uniques              []uint64 `protobuf:"varint,2,rep,name=uniques" json:"uniques,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoValueUniques) Reset()         { *m = ProtoValueUniques{} }
func (m *ProtoValueUniques) String() string { return proto.CompactTextString(m) }
func (*ProtoValueUniques) ProtoMessage()    {}
func (*ProtoValueUniques) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{8}
}

func (m *ProtoValueUniques) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoValueUniques.Unmarshal(m, b)
}
func (m *ProtoValueUniques) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoValueUniques.Marshal(b, m, deterministic)
}
func (m *ProtoValueUniques) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoValueUniques.Merge(m, src)
}
func (m *ProtoValueUniques) XXX_Size() int {
	return xxx_messageInfo_ProtoValueUniques.Size(m)
}
func (m *ProtoValueUniques) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoValueUniques.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoValueUniques proto.InternalMessageInfo

func (m *ProtoValueUniques) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ProtoValueUniques) GetUniques() []uint64 {
	if m != nil {
		return m.Uniques
	}
	return nil
}

type ProtoTopKElement struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Score                *int32   `protobuf:"varint,2,req,name=score" json:"score,omitempty"`
	Ts                   *int64   `protobuf:"varint,3,req,name=ts" json:"ts,omitempty"`
	ReplicaID            *int64   `protobuf:"varint,4,req,name=replicaID" json:"replicaID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoTopKElement) Reset()         { *m = ProtoTopKElement{} }
func (m *ProtoTopKElement) String() string { return proto.CompactTextString(m) }
func (*ProtoTopKElement) ProtoMessage()    {}
func (*ProtoTopKElement) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{9}
}

func (m *ProtoTopKElement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoTopKElement.Unmarshal(m, b)
}
func (m *ProtoTopKElement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoTopKElement.Marshal(b, m, deterministic)
}
func (m *ProtoTopKElement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoTopKElement.Merge(m, src)
}
func (m *ProtoTopKElement) XXX_Size() int {
	return xxx_messageInfo_ProtoTopKElement.Size(m)
}
func (m *ProtoTopKElement) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoTopKElement.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoTopKElement proto.InternalMessageInfo

func (m *ProtoTopKElement) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ProtoTopKElement) GetScore() int32 {
	if m != nil && m.Score != nil {
		return *m.Score
	}
	return 0
}

func (m *ProtoTopKElement) GetTs() int64 {
	if m != nil && m.Ts != nil {
		return *m.Ts
	}
	return 0
}

func (m *ProtoTopKElement) GetReplicaID() int64 {
	if m != nil && m.ReplicaID != nil {
		return *m.ReplicaID
	}
	return 0
}

type ProtoTopKIdVc struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Vc                   []byte   `protobuf:"bytes,2,req,name=vc" json:"vc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoTopKIdVc) Reset()         { *m = ProtoTopKIdVc{} }
func (m *ProtoTopKIdVc) String() string { return proto.CompactTextString(m) }
func (*ProtoTopKIdVc) ProtoMessage()    {}
func (*ProtoTopKIdVc) Descriptor() ([]byte, []int) {
	return fileDescriptor_e741e2c5586b74b6, []int{10}
}

func (m *ProtoTopKIdVc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoTopKIdVc.Unmarshal(m, b)
}
func (m *ProtoTopKIdVc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoTopKIdVc.Marshal(b, m, deterministic)
}
func (m *ProtoTopKIdVc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoTopKIdVc.Merge(m, src)
}
func (m *ProtoTopKIdVc) XXX_Size() int {
	return xxx_messageInfo_ProtoTopKIdVc.Size(m)
}
func (m *ProtoTopKIdVc) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoTopKIdVc.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoTopKIdVc proto.InternalMessageInfo

func (m *ProtoTopKIdVc) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ProtoTopKIdVc) GetVc() []byte {
	if m != nil {
		return m.Vc
	}
	return nil
}

func init() {
	proto.RegisterType((*ProtoStableClock)(nil), "ProtoStableClock")
	proto.RegisterType((*ProtoReplicatePart)(nil), "ProtoReplicatePart")
	proto.RegisterType((*ProtoRemoteTxn)(nil), "ProtoRemoteTxn")
	proto.RegisterType((*ProtoDownstreamUpd)(nil), "ProtoDownstreamUpd")
	proto.RegisterType((*ProtoCounterDownstream)(nil), "ProtoCounterDownstream")
	proto.RegisterType((*ProtoSetDownstream)(nil), "ProtoSetDownstream")
	proto.RegisterType((*ProtoTopKRmvDownstream)(nil), "ProtoTopKRmvDownstream")
	proto.RegisterType((*ProtoValueUnique)(nil), "ProtoValueUnique")
	proto.RegisterType((*ProtoValueUniques)(nil), "ProtoValueUniques")
	proto.RegisterType((*ProtoTopKElement)(nil), "ProtoTopKElement")
	proto.RegisterType((*ProtoTopKIdVc)(nil), "ProtoTopKIdVc")
}

func init() { proto.RegisterFile("replicator.proto", fileDescriptor_e741e2c5586b74b6) }

var fileDescriptor_e741e2c5586b74b6 = []byte{
	// 533 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0x5f, 0x6f, 0xd3, 0x3e,
	0x14, 0x55, 0xd3, 0xf4, 0xf7, 0x6b, 0x6f, 0x47, 0xd9, 0x0c, 0x1a, 0xd1, 0xc4, 0x43, 0x89, 0x04,
	0x94, 0x07, 0x86, 0x54, 0x89, 0x77, 0x58, 0x0b, 0x52, 0x04, 0x52, 0x2b, 0xaf, 0x1b, 0x12, 0x6f,
	0xae, 0x63, 0x20, 0xb4, 0xb1, 0x8d, 0xed, 0x94, 0xf1, 0x5d, 0xf9, 0x30, 0xc8, 0x7f, 0xba, 0x24,
	0xea, 0xe0, 0xad, 0xc7, 0xf7, 0xf8, 0x9c, 0x73, 0xaf, 0x7b, 0x03, 0xc7, 0x8a, 0xc9, 0x6d, 0x41,
	0x89, 0x11, 0xea, 0x5c, 0x2a, 0x61, 0xc4, 0xd9, 0x88, 0x70, 0x53, 0xe4, 0xc2, 0x30, 0x8f, 0xd3,
	0x8f, 0x70, 0xbc, 0xb4, 0x3f, 0x2e, 0x0d, 0x59, 0x6f, 0xd9, 0x6c, 0x2b, 0xe8, 0x06, 0x9d, 0x41,
	0x5f, 0x33, 0x9e, 0x33, 0x95, 0xcd, 0x93, 0xce, 0x38, 0x9a, 0x74, 0xf1, 0x2d, 0x46, 0x8f, 0x61,
	0x10, 0x34, 0x57, 0x3a, 0x89, 0x5c, 0xb1, 0x3e, 0x48, 0x2b, 0x40, 0x4e, 0x0d, 0x07, 0x5b, 0xb6,
	0x24, 0xca, 0xfc, 0x53, 0xef, 0x09, 0x74, 0xcd, 0x0d, 0x77, 0x4a, 0xc3, 0xe9, 0xfd, 0xf3, 0x70,
	0xbb, 0x14, 0x86, 0xad, 0x6e, 0x38, 0xb6, 0x35, 0x34, 0x86, 0xa1, 0x24, 0xca, 0x14, 0xa6, 0x10,
	0x3c, 0x9b, 0x27, 0x5d, 0xa7, 0xd0, 0x3c, 0x4a, 0x3f, 0xc1, 0xa8, 0x7d, 0xd1, 0xc6, 0x34, 0x45,
	0xc9, 0xb4, 0x21, 0xa5, 0x74, 0x9e, 0x47, 0xb8, 0x3e, 0x40, 0xcf, 0x21, 0xae, 0x64, 0x6e, 0xf3,
	0x77, 0x27, 0xc3, 0xe9, 0x03, 0xef, 0x3a, 0x17, 0x3f, 0xb9, 0x36, 0x8a, 0x91, 0xf2, 0x4a, 0xe6,
	0xd8, 0x11, 0xd2, 0xdf, 0x9d, 0xd0, 0x50, 0xab, 0x88, 0x5e, 0xc2, 0x60, 0xc3, 0x7e, 0x2d, 0x89,
	0x22, 0xa5, 0x76, 0xea, 0x36, 0xfa, 0x5b, 0xb9, 0xbe, 0x10, 0x15, 0xcf, 0x17, 0xeb, 0xef, 0x8c,
	0x1a, 0x5c, 0x33, 0xd0, 0x6b, 0x18, 0x50, 0x51, 0x71, 0xc3, 0xd4, 0x42, 0x26, 0xd1, 0xb8, 0x33,
	0x19, 0x4e, 0x1f, 0x79, 0xcf, 0x99, 0x3f, 0xae, 0xd5, 0x71, 0xcd, 0x44, 0x2f, 0xa0, 0xa7, 0x99,
	0x59, 0xc8, 0xa4, 0xeb, 0xae, 0x84, 0x98, 0x97, 0xcc, 0x34, 0xe8, 0x9e, 0x61, 0x1d, 0x8c, 0x90,
	0x1b, 0x55, 0xee, 0x16, 0x32, 0x89, 0x9b, 0x0e, 0x2b, 0x21, 0x3f, 0xe0, 0x72, 0xd7, 0x74, 0xb8,
	0x65, 0xa6, 0xef, 0xe1, 0xf4, 0xee, 0x18, 0xe8, 0x21, 0xf4, 0x0a, 0x9d, 0x71, 0xea, 0xba, 0xeb,
	0x63, 0x0f, 0xd0, 0x29, 0xfc, 0x47, 0xbf, 0x11, 0xfe, 0x95, 0xb9, 0xf7, 0xea, 0xe1, 0x80, 0x52,
	0x1a, 0xa6, 0xd4, 0xca, 0x86, 0x9e, 0x42, 0x4c, 0xf2, 0xdc, 0x0e, 0xc8, 0x4e, 0xf9, 0xc4, 0xe7,
	0xb9, 0x26, 0xdb, 0x8a, 0x5d, 0xf1, 0xe2, 0x47, 0xc5, 0xb0, 0x2b, 0xa3, 0x67, 0x10, 0x2b, 0x56,
	0xee, 0x1f, 0x03, 0x1d, 0xd0, 0x34, 0x76, 0xf5, 0x94, 0x86, 0xb0, 0x07, 0x1d, 0xdd, 0x6d, 0x64,
	0x69, 0xef, 0xb6, 0xac, 0x64, 0xdc, 0x04, 0xa3, 0xb4, 0x65, 0x34, 0xaa, 0x69, 0x59, 0x7e, 0x4d,
	0x83, 0xc9, 0x9b, 0xb0, 0x0e, 0x0d, 0x7f, 0x3b, 0x8b, 0x9d, 0x85, 0xe1, 0x7f, 0xe4, 0x81, 0x9d,
	0x45, 0xe5, 0xea, 0x6e, 0x16, 0x31, 0x0e, 0x28, 0x9d, 0xc1, 0xc9, 0x41, 0x07, 0x7f, 0x91, 0x48,
	0xe0, 0x7f, 0x7f, 0xc9, 0x67, 0x8a, 0xf1, 0x1e, 0xa6, 0x5f, 0x42, 0x8c, 0x46, 0x13, 0x68, 0x04,
	0x51, 0x91, 0x3b, 0x81, 0x1e, 0x8e, 0x8a, 0xdc, 0x6a, 0x6a, 0x2a, 0xd4, 0xfe, 0x2d, 0x3c, 0xb0,
	0x2c, 0xa3, 0xc3, 0x8e, 0x44, 0x46, 0x37, 0xf6, 0x35, 0x9b, 0x27, 0x71, 0x6b, 0x5f, 0xb3, 0x79,
	0xfa, 0x0a, 0xee, 0xb5, 0xa6, 0x70, 0x60, 0x32, 0x82, 0x68, 0x47, 0x9d, 0xc3, 0x11, 0x8e, 0x76,
	0xf4, 0x02, 0x3e, 0xf7, 0xf7, 0x1f, 0x90, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3f, 0xa3, 0x15,
	0xa7, 0x5d, 0x04, 0x00, 0x00,
}
